LESSONS = [
    {
        "concept_slug": "linux",
        "title": "Linux Fundamentals for Security",
        "slug": "deep-linux-fundamentals",
        "description": "Master Linux kernel vs userspace architecture, package management, process control, and the essential commands every security professional needs.",
        "hook": "Every server you'll ever pentest is probably running Linux. If you can't navigate a terminal, you're already blind.",
        "problem": "Most security tools are Linux-native, yet beginners treat Linux like a black box instead of understanding how the kernel, userspace, and package managers actually work together.",
        "explanation": "Linux splits into kernel space (hardware, memory, scheduling) and userspace (everything you interact with). Distros like Ubuntu, CentOS, and Kali bundle different tools and package managers like apt and yum to manage software. Users, groups, and process management form the core of system administration.",
        "real_world_example": "A SOC analyst uses 'ps aux | grep nginx' to find rogue processes, 'kill -9' to stop a compromised service, and 'systemctl' to restart hardened services — all fundamental Linux skills.",
        "summary": "Linux is the backbone of servers and security tools. Understanding kernel vs userspace, package management, users/groups, and process control is non-negotiable for any security role.",
        "curiosity_hook": "Did you know the Linux kernel is actually monolithic, not microkernel? That design choice has massive security implications we'll explore later.",
        "dialogue": [
            {"speaker": "Peter", "text": "Okay so what even IS Linux? Is it an operating system or what?"},
            {"speaker": "Stewie", "text": "Linux is technically just the kernel — the core that talks to your hardware and manages memory."},
            {"speaker": "Peter", "text": "Wait so Ubuntu and Kali aren't Linux?"},
            {"speaker": "Stewie", "text": "They're Linux distros. They bundle the kernel with userspace tools, a package manager, and a desktop environment."},
            {"speaker": "Peter", "text": "So what's the difference between apt and yum then?"},
            {"speaker": "Stewie", "text": "Different package managers for different distros. APT is Debian-based, YUM is Red Hat-based. Same job, different syntax."},
            {"speaker": "Peter", "text": "Got it. And how do I see what processes are running?"},
            {"speaker": "Stewie", "text": "Use 'ps aux' for a snapshot or 'top' for a live view. Both show PID, CPU usage, and who owns each process."},
            {"speaker": "Peter", "text": "What if I need to kill a sketchy process?"},
            {"speaker": "Stewie", "text": "Use 'kill' with the PID. Try SIGTERM first, SIGKILL only as a last resort — it can't clean up after itself."},
            {"speaker": "Peter", "text": "Why does everyone say Linux dominates servers?"},
            {"speaker": "Stewie", "text": "It's free, stable, customizable, and most security tools are built for it. Ninety-six percent of the top million servers run Linux."},
        ],
        "learning_objectives": [
            "Distinguish between the Linux kernel and userspace components",
            "Compare major distros and their package managers (apt, yum)",
            "Manage users, groups, and processes with core Linux commands",
            "Explain why Linux dominates server and security tool ecosystems"
        ],
        "quiz_questions": [
            {
                "question": "What is the Linux kernel responsible for?",
                "answers": [
                    {"id": "a", "text": "Managing hardware, memory, and process scheduling", "correct": True},
                    {"id": "b", "text": "Providing the graphical desktop environment", "correct": False},
                    {"id": "c", "text": "Installing software packages automatically", "correct": False},
                    {"id": "d", "text": "Running web browsers and applications", "correct": False},
                ],
            },
            {
                "question": "Which package manager is used by Debian-based distros like Ubuntu?",
                "answers": [
                    {"id": "a", "text": "yum", "correct": False},
                    {"id": "b", "text": "apt", "correct": True},
                    {"id": "c", "text": "pacman", "correct": False},
                    {"id": "d", "text": "zypper", "correct": False},
                ],
            },
            {
                "question": "What does 'ps aux' display?",
                "answers": [
                    {"id": "a", "text": "A list of all running processes with detailed info", "correct": True},
                    {"id": "b", "text": "System memory usage over time", "correct": False},
                    {"id": "c", "text": "Network connections and open ports", "correct": False},
                    {"id": "d", "text": "Disk usage for all mounted filesystems", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "linux-filesystem",
        "title": "Linux Filesystem Hierarchy & Security",
        "slug": "deep-linux-filesystem-security",
        "description": "Explore the FHS directory structure, file types, permissions pitfalls, and why certain directories are prime targets for attackers.",
        "hook": "Attackers don't break into systems — they walk through misconfigured directories. Understanding the filesystem is your first line of defense.",
        "problem": "Security teams often focus on network defenses while ignoring filesystem-level risks like world-writable directories, sticky bit misconfigurations, and unprotected /tmp and /var paths that are commonly exploited.",
        "explanation": "The Linux FHS organizes system files into predictable locations: /etc for configs, /var for logs, /tmp for temporary files, /proc for kernel interfaces. File types include regular files, directories, symlinks, and device files. Mounting points defined in /etc/fstab control how filesystems are accessed at boot.",
        "real_world_example": "An attacker plants a script in /tmp because it's world-writable. Without the sticky bit or proper permissions, any user can execute it — making /tmp and /var/www/uploads classic attack vectors in production environments.",
        "summary": "The Linux filesystem follows a strict hierarchy. Knowing what lives where — and what permissions apply — is critical for hardening systems and detecting tampering.",
        "curiosity_hook": "The /proc filesystem doesn't store data on disk at all. It's a live window into the kernel's memory — and attackers use it to extract credentials in real time.",
        "dialogue": [
            {"speaker": "Peter", "text": "Why does Linux have so many folders? What's wrong with just putting everything in one place?"},
            {"speaker": "Stewie", "text": "The FHS standardizes where things go. /etc has configs, /var has logs, /tmp has temporary junk. It's organized chaos."},
            {"speaker": "Peter", "text": "Okay but what about /home and /root? Aren't they the same thing?"},
            {"speaker": "Stewie", "text": "/home is for regular users. /root is the superuser's home. Never confuse them — /root often has stricter permissions."},
            {"speaker": "Peter", "text": "I've heard /tmp is dangerous. Why?"},
            {"speaker": "Stewie", "text": "It's world-writable by default. Anyone can drop files there. Attackers love staging payloads in /tmp for that reason."},
            {"speaker": "Peter", "text": "What's /proc then? Is that where configs live?"},
            {"speaker": "Stewie", "text": "No. /proc is a virtual filesystem. It's a live interface to kernel data — processes, memory, hardware info. It exists only in RAM."},
            {"speaker": "Peter", "text": "So can attackers use /proc to steal stuff?"},
            {"speaker": "Stewie", "text": "Absolutely. /proc/self/environ leaks environment variables. /proc/[pid]/maps can expose loaded libraries and memory layout."},
            {"speaker": "Peter", "text": "What about symlinks? Are those just shortcuts?"},
            {"speaker": "Stewie", "text": "Think of them as pointers. A symlink in /tmp pointing to /etc/shadow could let an attacker read the password file if a root process follows it."},
        ],
        "learning_objectives": [
            "Navigate the FHS hierarchy and identify the purpose of key directories",
            "Distinguish between regular files, directories, symlinks, and device files",
            "Recognize filesystem-based attack vectors in /tmp, /var, and /proc",
            "Apply security hardening measures like sticky bits and file integrity monitoring"
        ],
        "quiz_questions": [
            {
                "question": "Which directory is a virtual filesystem providing live kernel data?",
                "answers": [
                    {"id": "a", "text": "/etc", "correct": False},
                    {"id": "b", "text": "/var", "correct": False},
                    {"id": "c", "text": "/proc", "correct": True},
                    {"id": "d", "text": "/tmp", "correct": False},
                ],
            },
            {
                "question": "Why is /tmp commonly exploited by attackers?",
                "answers": [
                    {"id": "a", "text": "It contains system configuration files", "correct": False},
                    {"id": "b", "text": "It is world-writable by default, allowing any user to store files", "correct": True},
                    {"id": "c", "text": "It automatically runs scripts at boot", "correct": False},
                    {"id": "d", "text": "It stores user password hashes", "correct": False},
                ],
            },
            {
                "question": "What does the sticky bit do on a directory?",
                "answers": [
                    {"id": "a", "text": "It makes the directory invisible to other users", "correct": False},
                    {"id": "b", "text": "It prevents users from deleting files they don't own", "correct": True},
                    {"id": "c", "text": "It encrypts all files inside the directory", "correct": False},
                    {"id": "d", "text": "It mounts the directory as read-only", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "bash",
        "title": "Bash Scripting for Security Automation",
        "slug": "deep-bash-scripting-security",
        "description": "Learn Bash syntax, piping, cron automation, and how to write security scripts for log monitoring, port scanning, and incident response.",
        "hook": "Security pros don't click buttons — they write scripts. Bash is the glue that turns manual tasks into automated defenses.",
        "problem": "Knowing individual commands isn't enough. Without scripting skills, security teams waste hours on repetitive tasks that could be automated in seconds with Bash.",
        "explanation": "Bash uses variables, conditionals (if/else), loops (for/while), and pipelines to chain commands. Cron enables scheduled automation. Security scripts can monitor logs for suspicious activity, scan open ports, audit user accounts, and respond to incidents — all from the command line.",
        "real_world_example": "A one-liner like 'netstat -tlnp | grep ESTABLISHED | wc -l' instantly counts active connections, while a cron job running a port scan every five minutes can detect unauthorized listeners before they become breaches.",
        "summary": "Bash scripting transforms you from a command-typist into an automation engineer. From cron jobs to incident response one-liners, scripting is the force multiplier for security work.",
        "curiosity_hook": "Shell injection vulnerabilities happen when user input gets passed directly into Bash commands — and they're still in the OWASP Top 10. Understanding Bash is a defensive skill too.",
        "dialogue": [
            {"speaker": "Peter", "text": "I can type commands in a terminal. Why do I need to learn scripting?"},
            {"speaker": "Stewie", "text": "Because typing the same ten commands every morning isn't a workflow — it's a hostage situation."},
            {"speaker": "Peter", "text": "Fair point. So what's the basic syntax like?"},
            {"speaker": "Stewie", "text": "Variables use name=value with no spaces. Conditionals use if-then-else. Loops use for or while. Pretty standard stuff."},
            {"speaker": "Peter", "text": "What about piping? I keep hearing about pipes."},
            {"speaker": "Stewie", "text": "Pipes take the output of one command and feed it as input to the next. It's how you chain small tools into powerful workflows."},
            {"speaker": "Peter", "text": "Can you show me an example for security?"},
            {"speaker": "Stewie", "text": "Try grep for 'Failed password' in auth.log, pipe to awk to grab the IP, then sort and count. Instant brute-force detector."},
            {"speaker": "Peter", "text": "That's actually really cool. What about automating this?"},
            {"speaker": "Stewie", "text": "Use cron. 'crontab -e' opens the editor. You can run that script every five minutes with a single line."},
            {"speaker": "Peter", "text": "What's shell injection? You mentioned it's dangerous."},
            {"speaker": "Stewie", "text": "It's when unsanitized input gets passed into a shell command. A user could inject 'rm -rf /' into a filename field and destroy your system."},
        ],
        "learning_objectives": [
            "Write Bash scripts using variables, conditionals, and loops",
            "Chain commands with pipes and redirection for data processing",
            "Automate security tasks with cron jobs and scheduled scripts",
            "Identify and prevent shell injection vulnerabilities"
        ],
        "quiz_questions": [
            {
                "question": "What does the pipe operator (|) do in Bash?",
                "answers": [
                    {"id": "a", "text": "Runs two commands at the same time in parallel", "correct": False},
                    {"id": "b", "text": "Feeds the output of one command as input to the next", "correct": True},
                    {"id": "c", "text": "Creates a new directory on the filesystem", "correct": False},
                    {"id": "d", "text": "Redirects output to a file instead of the terminal", "correct": False},
                ],
            },
            {
                "question": "How do you schedule a script to run every 5 minutes using cron?",
                "answers": [
                    {"id": "a", "text": "*/5 * * * * /path/to/script.sh", "correct": True},
                    {"id": "b", "text": "5 * * * * /path/to/script.sh", "correct": False},
                    {"id": "c", "text": "0 */5 * * * /path/to/script.sh", "correct": False},
                    {"id": "d", "text": "* * * * 5 /path/to/script.sh", "correct": False},
                ],
            },
            {
                "question": "What is a common way to prevent shell injection in Bash scripts?",
                "answers": [
                    {"id": "a", "text": "Using echo instead of variable expansion", "correct": False},
                    {"id": "b", "text": "Always quoting variables and validating user input", "correct": True},
                    {"id": "c", "text": "Running scripts as the root user only", "correct": False},
                    {"id": "d", "text": "Disabling Bash and using Python instead", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "systemd",
        "title": "Systemd & Service Security",
        "slug": "deep-systemd-security",
        "description": "Understand systemd unit files, service management, journal logging, cgroups, and how to harden services against common attack vectors.",
        "hook": "Most Linux breaches don't start at the network — they start with a poorly configured service. Systemd is where you lock things down.",
        "problem": "Systemd replaced init on most modern Linux distros, yet many admins still treat service configuration as an afterthought. Poorly sandboxed services are one of the most common persistence and privilege escalation vectors.",
        "explanation": "Systemd manages services through unit files that define how processes start, stop, and behave. Key concepts include systemctl for service control, journal for centralized logging, cgroups for resource isolation, and sandboxing directives like ProtectSystem, PrivateTmp, and NoNewPrivileges to limit what a service can access.",
        "real_world_example": "An attacker installs a malicious systemd service with 'Type=simple' that auto-restarts on failure, runs as root, and has full filesystem access. Hardening that same service with sandboxing directives would have contained the blast radius significantly.",
        "summary": "Systemd is the backbone of modern Linux service management. Hardening unit files with sandboxing, resource limits, and proper logging is essential for both defense and incident detection.",
        "curiosity_hook": "Systemd can activate services on demand using socket activation — the service only starts when a network connection arrives. This reduces attack surface by keeping unused services dormant.",
        "dialogue": [
            {"speaker": "Peter", "text": "What exactly is systemd? I keep seeing systemctl commands everywhere."},
            {"speaker": "Stewie", "text": "Systemd is the init system on most modern Linux distros. It starts, stops, and manages all background services."},
            {"speaker": "Peter", "text": "So it's basically the thing that boots up all my services?"},
            {"speaker": "Stewie", "text": "Exactly. Each service has a unit file that tells systemd how to run it — what user, what permissions, what resources it can use."},
            {"speaker": "Peter", "text": "Can I see those unit files?"},
            {"speaker": "Stewie", "text": "Run 'systemctl cat service-name' to view one. They're usually in /lib/systemd/system/ or /etc/systemd/system/."},
            {"speaker": "Peter", "text": "What's journal then? Is that different from syslog?"},
            {"speaker": "Stewie", "text": "Journal is systemd's own logging system. Use 'journalctl -u service-name' to see logs for a specific service. It's centralized and structured."},
            {"speaker": "Peter", "text": "How do I lock down a service so it can't wreck my system?"},
            {"speaker": "Stewie", "text": "Add sandboxing directives. ProtectSystem locks the root filesystem, PrivateTmp isolates /tmp, NoNewPrivileges blocks escalation."},
            {"speaker": "Peter", "text": "Why do attackers target systemd services?"},
            {"speaker": "Stewie", "text": "Because a service running as root with auto-restart is the perfect persistence mechanism. It survives reboots and crashes."},
        ],
        "learning_objectives": [
            "Create and modify systemd unit files for service management",
            "Use systemctl and journalctl to control and audit services",
            "Apply sandboxing directives to restrict service capabilities",
            "Understand how cgroups isolate resources and prevent abuse"
        ],
        "quiz_questions": [
            {
                "question": "What does the ProtectSystem directive do in a systemd unit file?",
                "answers": [
                    {"id": "a", "text": "Makes the root filesystem read-only for the service", "correct": True},
                    {"id": "b", "text": "Enables firewall rules for the service", "correct": False},
                    {"id": "c", "text": "Prevents the service from accessing the network", "correct": False},
                    {"id": "d", "text": "Automatically restarts the service on failure", "correct": False},
                ],
            },
            {
                "question": "How do you view logs for a specific systemd service?",
                "answers": [
                    {"id": "a", "text": "cat /var/log/service-name.log", "correct": False},
                    {"id": "b", "text": "journalctl -u service-name", "correct": True},
                    {"id": "c", "text": "systemctl logs service-name", "correct": False},
                    {"id": "d", "text": "dmesg | grep service-name", "correct": False},
                ],
            },
            {
                "question": "Why do attackers use systemd services for persistence?",
                "answers": [
                    {"id": "a", "text": "Systemd services can only run on port 80", "correct": False},
                    {"id": "b", "text": "Services auto-restart and survive reboots, providing reliable persistence", "correct": True},
                    {"id": "c", "text": "Systemd services bypass all firewall rules", "correct": False},
                    {"id": "d", "text": "Unit files are encrypted by default", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "windows-internals",
        "title": "Windows Internals for Security",
        "slug": "deep-windows-internals-security",
        "description": "Dive into the Windows Registry, services, scheduled tasks, Event Logs, LSASS, UAC, and why internals knowledge is critical for both offense and defense.",
        "hook": "You can't defend what you don't understand. Windows internals separate script kiddies from real security professionals.",
        "problem": "Many security practitioners rely on GUI tools without understanding what's happening under the hood. Without knowledge of the Registry, services, LSASS, and Event Logs, they can't detect persistence, investigate breaches, or harden systems effectively.",
        "explanation": "The Windows Registry stores configuration across five hives, with Run keys being common persistence points. The Service Control Manager manages background processes. Scheduled tasks provide another persistence vector. Event Logs record system activity, LSASS handles credential storage, UAC provides privilege escalation controls, and Windows Defender uses kernel-level components for protection.",
        "real_world_example": "A blue team analyst spots a suspicious new value in HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run — a classic persistence mechanism. Without Registry knowledge, this alert would be meaningless noise.",
        "summary": "Windows internals — Registry, services, scheduled tasks, Event Logs, LSASS, and UAC — form the foundation of both attack and defense. Mastering them is non-negotiable for security professionals.",
        "curiosity_hook": "LSASS stores credentials in memory and has been the target of nearly every major Windows credential theft attack, from Mimikatz to kernel-level exploits. Microsoft's response? Credential Guard — but it's not enabled by default.",
        "dialogue": [
            {"speaker": "Peter", "text": "Why should I care about Windows internals? I just use the control panel right?"},
            {"speaker": "Stewie", "text": "The control panel is a pretty facade. Real security work happens in the Registry, service manager, and Event Logs."},
            {"speaker": "Peter", "text": "What even IS the Windows Registry?"},
            {"speaker": "Stewie", "text": "It's a massive hierarchical database storing every system and app configuration. Think of it as Windows' central nervous system."},
            {"speaker": "Peter", "text": "And attackers use it for persistence?"},
            {"speaker": "Stewie", "text": "Exactly. Add a value to the Run keys and your program executes at every login. It's the most common persistence technique on Windows."},
            {"speaker": "Peter", "text": "What about scheduled tasks? Those are just reminders right?"},
            {"speaker": "Stewie", "text": "No. They execute programs on triggers — time, login, system event. Attackers love them because they survive reboots and run with elevated privileges."},
            {"speaker": "Peter", "text": "I've heard of LSASS. What does it actually do?"},
            {"speaker": "Stewie", "text": "It stores authentication credentials in memory. That's why tools like Mimikatz target it — steal LSASS memory, steal every password on the machine."},
            {"speaker": "Peter", "text": "What's UAC then? Is that the annoying popup?"},
            {"speaker": "Stewie", "text": "Yes, and it exists for a reason. It forces apps to request admin privileges explicitly, preventing silent privilege escalation."},
        ],
        "learning_objectives": [
            "Understand the Windows Registry structure and identify persistence mechanisms",
            "Explain Windows services, scheduled tasks, and their security implications",
            "Navigate Windows Event Logs for security investigation and monitoring",
            "Describe LSASS, UAC, and Windows Defender's role in credential protection"
        ],
        "quiz_questions": [
            {
                "question": "Where do attackers commonly place entries for Windows login persistence?",
                "answers": [
                    {"id": "a", "text": "The Desktop folder", "correct": False},
                    {"id": "b", "text": "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", "correct": True},
                    {"id": "c", "text": "The Recycle Bin", "correct": False},
                    {"id": "d", "text": "Program Files directory", "correct": False},
                ],
            },
            {
                "question": "What is the primary security risk of the LSASS process?",
                "answers": [
                    {"id": "a", "text": "It consumes too much CPU on startup", "correct": False},
                    {"id": "b", "text": "It stores authentication credentials in memory, making it a target for credential theft", "correct": True},
                    {"id": "c", "text": "It blocks all incoming network connections", "correct": False},
                    {"id": "d", "text": "It automatically grants admin rights to all users", "correct": False},
                ],
            },
            {
                "question": "What is the purpose of User Account Control (UAC)?",
                "answers": [
                    {"id": "a", "text": "To encrypt all files on the hard drive", "correct": False},
                    {"id": "b", "text": "To force applications to explicitly request administrator privileges", "correct": True},
                    {"id": "c", "text": "To manage Windows Update schedules", "correct": False},
                    {"id": "d", "text": "To block USB devices from being connected", "correct": False},
                ],
            },
        ],
    },
]
