"""SC-100 Learning Path 5 lessons — depth expansion for existing concepts.

Adds one deeper lesson to each of 10 existing SC-100 concepts:
  zero-trust, cloud-frameworks, compliance, security-operations, data-security,
  app-security-arch, resilience, devsecops-arch, privileged-access, ai-security

Same schema as sc100_lp1/2/3/4_lessons.py.
"""

from dialogue_rewriter import rewrite_lessons_dialogues


LESSONS = [
    {
        "concept_slug": "zero-trust",
        "title": "Zero Trust's Hidden Seventh Pillar",
        "slug": "sc100-zero-trust-visibility-automation",
        "description": "Visibility, automation, and orchestration — the pillar that ties all six Zero Trust pillars together.",
        "hook": "Six pillars, six sets of alerts. Without the seventh pillar, your security team drowns in its own signal.",
        "problem": "Each Zero Trust pillar generates its own telemetry. Organizations that deploy the pillars without integration end up with silos of alerts nobody can correlate.",
        "explanation": "Zero Trust spans six technology pillars: identities, endpoints, data, applications, infrastructure, and network. The seventh pillar — visibility, automation, and orchestration — ties them together. Every pillar is both a source of signal and a control plane for enforcement. Without an integrated capability to manage the influx of data, alerts pile up, threats go undetected, and trust cannot be validated per transaction. Automation converts raw signal into consistent response: policy enforcement, threat detection, and remediation run at machine speed. Orchestration coordinates across tools so a signal from one pillar (a risky sign-in) drives a control in another (blocking device access). Microsoft Security Exposure Management and Defender XDR exemplify this: they correlate signals across identity, endpoint, email, and cloud apps into unified posture and response.",
        "real_world_example": "An identity alert flags a user's impossible travel. Orchestration automatically triggers device isolation, revokes sessions, and opens an incident — actions that would take analysts hours if each pillar were monitored separately.",
        "summary": "The seventh pillar is the nervous system of Zero Trust: collect signals from all six pillars, automate response, and orchestrate controls so verification happens continuously and at scale.",
        "curiosity_hook": "Two pillars can agree a user is fine while a third detects an anomaly — correlation across pillars is what catches what single-silo monitoring misses.",
        "dialogue": [
            {"speaker": "Peter", "text": "Six Zero Trust pillars. I've got that. So we're done, right?"},
            {"speaker": "Stewie", "text": "Almost. There's a seventh nobody talks about: visibility, automation, and orchestration."},
            {"speaker": "Peter", "text": "A seventh pillar? What does it do?"},
            {"speaker": "Stewie", "text": "Every pillar generates alerts. This pillar makes sense of all that noise."},
            {"speaker": "Peter", "text": "So it's a dashboard?"},
            {"speaker": "Stewie", "text": "More than that. It integrates signals, automates response, and coordinates controls across tools."},
            {"speaker": "Peter", "text": "Why can't each pillar just monitor itself?"},
            {"speaker": "Stewie", "text": "Because an attack spans pillars. Risky sign-in here, strange device there — only correlation connects them."},
            {"speaker": "Peter", "text": "And automation?"},
            {"speaker": "Stewie", "text": "Response at machine speed. Policy enforcement, detection, and remediation without waiting for a human."},
            {"speaker": "Peter", "text": "Orchestration is different?"},
            {"speaker": "Stewie", "text": "Yes. One signal drives a control in another pillar. Anomaly in identity triggers device isolation."},
            {"speaker": "Peter", "text": "So the seventh pillar is the nervous system."},
            {"speaker": "Stewie", "text": "Exactly. Without it, the other six are just expensive sensors."},
        ],
        "learning_objectives": [
            "Describe the seventh Zero Trust pillar: visibility, automation, orchestration",
            "Explain why cross-pillar correlation is required for detection",
            "Design automated and orchestrated response across Zero Trust pillars",
        ],
        "quiz_questions": [
            {
                "question": "What is the seventh pillar of Zero Trust?",
                "answers": [
                    {"id": "a", "text": "Visibility, automation, and orchestration", "correct": True},
                    {"id": "b", "text": "Encryption and key management", "correct": False},
                    {"id": "c", "text": "Penetration testing", "correct": False},
                    {"id": "d", "text": "Identity governance", "correct": False},
                ],
            },
            {
                "question": "Why must signals be correlated across pillars?",
                "answers": [
                    {"id": "a", "text": "Attacks span multiple pillars and are missed by single-silo monitoring", "correct": True},
                    {"id": "b", "text": "It reduces the number of pillars needed", "correct": False},
                    {"id": "c", "text": "It removes the need for automation", "correct": False},
                    {"id": "d", "text": "It only applies to on-premises networks", "correct": False},
                ],
            },
            {
                "question": "What does orchestration add beyond automation?",
                "answers": [
                    {"id": "a", "text": "Coordinating controls across pillars so one signal drives another's response", "correct": True},
                    {"id": "b", "text": "Patching operating systems", "correct": False},
                    {"id": "c", "text": "Backing up databases", "correct": False},
                    {"id": "d", "text": "Renaming user accounts", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "CAF Secure Methodology & the CIA Triad",
        "slug": "sc100-caf-secure-methodology",
        "description": "How the Cloud Adoption Framework's Secure methodology overlays every phase and maps to confidentiality, integrity, and availability.",
        "hook": "Security is not a phase in cloud adoption — it's an overlay on every phase. Skip it in one and the whole posture leaks.",
        "problem": "Organizations treat security as a step at the end of cloud adoption, leaving gaps in strategy, planning, landing zones, and operations that compound over time.",
        "explanation": "The CAF Secure methodology is an overlay applied across all seven CAF methodologies: Strategy, Plan, Ready, Adopt, Govern, and Manage. In each phase security runs in parallel — define security objectives in Strategy, identify skills gaps in Plan, secure landing zones in Ready, embed controls in Adopt, enforce policies in Govern, and monitor and respond in Manage. Security activities organize around the CIA triad: confidentiality (restrict access through encryption, classification, least privilege), integrity (preserve correctness through hashing, signing, immutable storage, secure update supply chains), and availability (maintain timely access through redundancy, fault tolerance, and recovery). All controls follow Zero Trust: verify explicitly, least privilege, assume breach. The methodology highlights four strategic areas: security posture modernization, incident preparedness and response, CIA triad strategies, and posture sustainment. Security responsibilities span the cloud provider, infrastructure teams, security architecture, SecOps, GRC, and awareness teams — the architect integrates across all of them.",
        "real_world_example": "An org adopting Azure skips security in the Plan phase. Later it discovers no security baselines in landing zones, no logging requirements, and no incident ownership — every later phase has to retrofit what should have been designed in.",
        "summary": "Secure methodology is a parallel overlay on every CAF phase, organized around the CIA triad and Zero Trust, spanning posture modernization, incident preparedness, and sustainment.",
        "curiosity_hook": "The CIA triad is older than the cloud, yet most cloud security failures are still plain confidentiality, integrity, or availability failures in disguise.",
        "dialogue": [
            {"speaker": "Peter", "text": "CAF has phases. Security is one of them, right?"},
            {"speaker": "Stewie", "text": "No. Security is an overlay on every phase. Skip it in one and the whole posture leaks."},
            {"speaker": "Peter", "text": "What does that look like phase by phase?"},
            {"speaker": "Stewie", "text": "Strategy sets security objectives. Plan finds skills gaps. Ready builds secure landing zones."},
            {"speaker": "Peter", "text": "And in Adopt?"},
            {"speaker": "Stewie", "text": "Embed controls during migration. Govern enforces policy. Manage monitors and responds."},
            {"speaker": "Peter", "text": "What organizes all this activity?"},
            {"speaker": "Stewie", "text": "The CIA triad. Confidentiality, integrity, availability. Every control maps to one."},
            {"speaker": "Peter", "text": "Give me an example of integrity."},
            {"speaker": "Stewie", "text": "Hashing, signing, immutable storage, secure update supply chains. Keep data correct."},
            {"speaker": "Peter", "text": "And availability?"},
            {"speaker": "Stewie", "text": "Redundancy, fault tolerance, recovery. Keep services reachable."},
            {"speaker": "Peter", "text": "Zero Trust still applies?"},
            {"speaker": "Stewie", "text": "Always. Verify explicitly, least privilege, assume breach."},
            {"speaker": "Peter", "text": "Who owns all this?"},
            {"speaker": "Stewie", "text": "Provider, platform teams, SecOps, GRC, awareness. Architect integrates them all."},
        ],
        "learning_objectives": [
            "Apply the CAF Secure methodology as an overlay across all phases",
            "Map security controls to confidentiality, integrity, and availability",
            "Identify security roles and responsibilities across the cloud lifecycle",
        ],
        "quiz_questions": [
            {
                "question": "How does the CAF Secure methodology relate to the CAF phases?",
                "answers": [
                    {"id": "a", "text": "It is an overlay applied across all phases", "correct": True},
                    {"id": "b", "text": "It only applies in the Manage phase", "correct": False},
                    {"id": "c", "text": "It replaces the Govern phase", "correct": False},
                    {"id": "d", "text": "It is a separate adoption track", "correct": False},
                ],
            },
            {
                "question": "Which controls support the integrity principle?",
                "answers": [
                    {"id": "a", "text": "Hashing, signing, immutable storage", "correct": True},
                    {"id": "b", "text": "Load balancing only", "correct": False},
                    {"id": "c", "text": "Firewall rules only", "correct": False},
                    {"id": "d", "text": "Password length policies", "correct": False},
                ],
            },
            {
                "question": "Which phase includes establishing secure landing zones?",
                "answers": [
                    {"id": "a", "text": "Ready", "correct": True},
                    {"id": "b", "text": "Strategy", "correct": False},
                    {"id": "c", "text": "Govern", "correct": False},
                    {"id": "d", "text": "Manage", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "compliance",
        "title": "Azure Policy Effects: Enforce or Fail Soft",
        "slug": "sc100-azure-policy-effects",
        "description": "Preventive, detective, corrective, and operational Azure Policy effects and the order they evaluate.",
        "hook": "Pick the wrong policy effect and you either block everything or document nothing. Effect choice is the whole game.",
        "problem": "Architects assign policies without understanding effect semantics, so requirements either block deployments unexpectedly or never actually enforce anything.",
        "explanation": "Azure Policy evaluates resources against JSON rules and responds with effects. Preventive effects stop noncompliance before it happens: Deny blocks resource creation or updates that violate policy, and DenyAction prevents specific lifecycle actions like deletion. Detective effects find noncompliance without blocking: Audit writes a warning to the activity log, and AuditIfNotExists audits when a related resource is missing, such as diagnostic settings. Corrective effects fix things automatically: Modify adds, updates, or removes properties, DeployIfNotExists deploys a related resource when absent, and Append adds properties during creation or update. Operational effects support lifecycle: Disabled turns evaluation off during phased rollout, and Manual requires attestation for controls that cannot be auto-evaluated, like procedural requirements. Effects evaluate in a fixed order: disabled, append/modify, deny, audit, manual, auditIfNotExists, then denyAction. Design guidance: start in audit mode to measure impact, then enforce with deny; use DeployIfNotExists for remediation; reserve Manual for attestation-based controls.",
        "real_world_example": "An org rolls out a 'no public storage access' policy in Audit first. It discovers 40 noncompliant accounts, remediates with DeployIfNotExists, then flips to Deny so new storage is born compliant.",
        "summary": "Choose effects by intent: Deny and DenyAction prevent, Audit and AuditIfNotExists detect, Modify, DeployIfNotExists and Append correct, Disabled and Manual support lifecycle. Evaluate in fixed order.",
        "curiosity_hook": "Policy evaluation runs every 24 hours, but individual resource changes reflect within about 15 minutes — compliance is never a snapshot, it's a stream.",
        "dialogue": [
            {"speaker": "Peter", "text": "So Azure Policy just... blocks bad stuff?"},
            {"speaker": "Stewie", "text": "Depends on the effect. Pick wrong and you block everything or enforce nothing."},
            {"speaker": "Peter", "text": "What blocks?"},
            {"speaker": "Stewie", "text": "Deny stops creation or updates that violate policy. DenyAction stops lifecycle actions like deletion."},
            {"speaker": "Peter", "text": "What if I only want to know, not block?"},
            {"speaker": "Stewie", "text": "Audit writes a warning. AuditIfNotExists flags missing things like diagnostic settings."},
            {"speaker": "Peter", "text": "Can policy fix things automatically?"},
            {"speaker": "Stewie", "text": "Modify changes properties. DeployIfNotExists deploys what's missing. Append adds properties."},
            {"speaker": "Peter", "text": "Any effects for rollout?"},
            {"speaker": "Stewie", "text": "Disabled pauses evaluation. Manual needs attestation for procedural controls."},
            {"speaker": "Peter", "text": "Do effects run in some order?"},
            {"speaker": "Stewie", "text": "Fixed order: disabled, append/modify, deny, audit, manual, auditIfNotExists, denyAction."},
            {"speaker": "Peter", "text": "Best practice for rolling out?"},
            {"speaker": "Stewie", "text": "Audit first, measure impact, remediate, then flip to Deny."},
            {"speaker": "Peter", "text": "So compliance is a journey, not a switch."},
            {"speaker": "Stewie", "text": "Exactly. And evaluation never sleeps — it runs every 24 hours."},
        ],
        "learning_objectives": [
            "Classify Azure Policy effects as preventive, detective, corrective, or operational",
            "Recall the fixed evaluation order of policy effects",
            "Design audit-then-enforce rollout for new policies",
        ],
        "quiz_questions": [
            {
                "question": "Which effect blocks creation of noncompliant resources?",
                "answers": [
                    {"id": "a", "text": "Deny", "correct": True},
                    {"id": "b", "text": "Audit", "correct": False},
                    {"id": "c", "text": "Manual", "correct": False},
                    {"id": "d", "text": "Disabled", "correct": False},
                ],
            },
            {
                "question": "What is the first effect evaluated in Azure Policy?",
                "answers": [
                    {"id": "a", "text": "Disabled", "correct": True},
                    {"id": "b", "text": "Deny", "correct": False},
                    {"id": "c", "text": "Audit", "correct": False},
                    {"id": "d", "text": "DenyAction", "correct": False},
                ],
            },
            {
                "question": "Which effect requires attestation for controls that cannot be evaluated automatically?",
                "answers": [
                    {"id": "a", "text": "Manual", "correct": True},
                    {"id": "b", "text": "Append", "correct": False},
                    {"id": "c", "text": "AuditIfNotExists", "correct": False},
                    {"id": "d", "text": "Modify", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Threat Hunting & Detection Engineering",
        "slug": "sc100-threat-hunting-detection",
        "description": "Proactive hunting, detection rule lifecycle, and how SOC teams map hypotheses to MITRE ATT&CK.",
        "hook": "Detection rules go stale the moment attackers change tactics. Hunting is how you find what your rules never saw.",
        "problem": "SOCs react to alerts from stale rules while attackers adapt. Without proactive hunting and a rule lifecycle, blind spots persist indefinitely.",
        "explanation": "Detection engineering creates, tests, and refines detection rules, while threat hunting proactively searches for compromise before alerts fire. The SOC is organized into teams: blue team defends, red team attacks, and purple team combines both to validate detections. Maturity is measured against CMMI levels from initial to optimizing. Hunting starts with a hypothesis — often grounded in threat intelligence and MITRE ATT&CK — and validates it with queries such as KQL in Microsoft Sentinel. Detection rule lifecycle: develop from an attack hypothesis, tune to reduce false positives, test against known-good and known-bad, deploy, then review as tactics evolve. Automated response playbooks built in Azure Logic Apps execute responses at machine speed. Integrating threat intelligence feeds external context into hunts, turning raw telemetry into prioritized investigation targets.",
        "real_world_example": "A threat intel feed reports a new credential-access technique. The hunt team writes a KQL query for the pattern, finds two compromised accounts the existing rules missed, and ships a new detection rule from the finding.",
        "summary": "Detection engineering manages the rule lifecycle; threat hunting proactively finds what rules miss. Ground both in MITRE ATT&CK, drive with KQL and threat intelligence, and automate response with playbooks.",
        "curiosity_hook": "Purple team is where blue and red stop being rivals — attackers and defenders run the same scenario to see what actually gets detected.",
        "dialogue": [
            {"speaker": "Peter", "text": "Aren't our detection rules enough?"},
            {"speaker": "Stewie", "text": "Rules go stale. Attackers adapt. That's why we hunt."},
            {"speaker": "Peter", "text": "What's the difference between hunting and alerting?"},
            {"speaker": "Stewie", "text": "Alerting waits for a rule to fire. Hunting actively searches for compromise before any alert."},
            {"speaker": "Peter", "text": "How do I start a hunt?"},
            {"speaker": "Stewie", "text": "Hypothesis first. Ground it in threat intel and MITRE ATT&CK, then validate with KQL."},
            {"speaker": "Peter", "text": "Blue and red teams? What about purple?"},
            {"speaker": "Stewie", "text": "Blue defends, red attacks. Purple runs both together to prove what's detected."},
            {"speaker": "Peter", "text": "How mature is our SOC?"},
            {"speaker": "Stewie", "text": "Measure against CMMI. Initial to optimizing. Hunting maturity comes late."},
            {"speaker": "Peter", "text": "What about response?"},
            {"speaker": "Stewie", "text": "Playbooks in Logic Apps automate response at machine speed."},
            {"speaker": "Peter", "text": "Where do rules come from?"},
            {"speaker": "Stewie", "text": "Detection engineering. Develop, tune, test, deploy, then review as tactics change."},
            {"speaker": "Peter", "text": "So hunting feeds new detections?"},
            {"speaker": "Stewie", "text": "Exactly. Every good hunt can ship a new rule."},
        ],
        "learning_objectives": [
            "Explain the detection rule lifecycle and detection engineering",
            "Structure a threat hunt from hypothesis to validation with MITRE ATT&CK",
            "Describe blue, red, and purple team roles and SOC maturity",
        ],
        "quiz_questions": [
            {
                "question": "What starts a threat hunt?",
                "answers": [
                    {"id": "a", "text": "A hypothesis grounded in threat intel and MITRE ATT&CK", "correct": True},
                    {"id": "b", "text": "A random port scan", "correct": False},
                    {"id": "c", "text": "An expired certificate", "correct": False},
                    {"id": "d", "text": "A hardware purchase", "correct": False},
                ],
            },
            {
                "question": "Which team validates detections by combining attack and defense in one scenario?",
                "answers": [
                    {"id": "a", "text": "Purple team", "correct": True},
                    {"id": "b", "text": "Red team", "correct": False},
                    {"id": "c", "text": "Blue team", "correct": False},
                    {"id": "d", "text": "Green team", "correct": False},
                ],
            },
            {
                "question": "What language is commonly used to hunt in Microsoft Sentinel?",
                "answers": [
                    {"id": "a", "text": "KQL", "correct": True},
                    {"id": "b", "text": "SQL", "correct": False},
                    {"id": "c", "text": "GraphQL", "correct": False},
                    {"id": "d", "text": "XPath", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "data-security",
        "title": "Encryption Key Lifecycle Management",
        "slug": "sc100-key-lifecycle-management",
        "description": "Key generation, storage, rotation, and destruction — and why keys are the crown jewels of data protection.",
        "hook": "Encryption without key management is like locking a vault and leaving the key taped underneath.",
        "problem": "Organizations enable encryption but manage keys poorly — hardcoded keys, no rotation, no HSM protection — turning the security control into a liability.",
        "explanation": "Data protection rests on encryption at rest and in transit, but the keys that power it are the true crown jewels. Key lifecycle covers generation, storage, use, rotation, and destruction. High-sensitivity keys belong in hardware security modules (HSMs) with physical and logical protection; cloud-native key services like Azure Key Vault provide managed HSM-backed storage, access policies, and audit logging. Prefer customer-managed keys (CMK) for high-sensitivity data so the organization controls rotation and revocation. Enforce rotation on a schedule and after personnel or incident changes — old keys must not linger. Use separate keys per environment and data classification so a compromise is contained. Restrict access to keys with least privilege and break-glass procedures, and log every key operation for audits. Secure the key service itself: its admin plane is as sensitive as the data it protects. Back up keys and test restore so key loss does not become data loss.",
        "real_world_example": "A company encrypted its database but stored the key in plaintext config. An attacker who read the config decrypted everything. After moving keys to Key Vault with HSM, rotation, and access logging, the same compromise yields ciphertext only.",
        "summary": "Manage keys as crown jewels: HSM-backed storage, customer-managed keys for sensitive data, scheduled rotation, least-privilege access, audit logging, and tested key backup and restore.",
        "curiosity_hook": "If you lose your encryption key, your data is gone forever — key loss is data loss, no matter how many backups you keep.",
        "dialogue": [
            {"speaker": "Peter", "text": "We encrypt everything. Security problem solved?"},
            {"speaker": "Stewie", "text": "Encryption is only as strong as the key management. The key is the crown jewel."},
            {"speaker": "Peter", "text": "Where should keys live?"},
            {"speaker": "Stewie", "text": "HSM-backed storage. Azure Key Vault. Hardware protection plus access control and logging."},
            {"speaker": "Peter", "text": "Who should control the keys?"},
            {"speaker": "Stewie", "text": "For sensitive data, you. Customer-managed keys give you rotation and revocation control."},
            {"speaker": "Peter", "text": "Rotation really matters?"},
            {"speaker": "Stewie", "text": "Yes. On a schedule, and after personnel or incident changes. Old keys must not linger."},
            {"speaker": "Peter", "text": "One key for everything?"},
            {"speaker": "Stewie", "text": "No. Separate keys per environment and data classification. Contain a compromise."},
            {"speaker": "Peter", "text": "Who can touch the keys?"},
            {"speaker": "Stewie", "text": "Least privilege, break-glass procedures, and log every key operation."},
            {"speaker": "Peter", "text": "What if I lose the key?"},
            {"speaker": "Stewie", "text": "Key loss is data loss. Back up keys and test restore."},
            {"speaker": "Peter", "text": "So keys need more protection than the data?"},
            {"speaker": "Stewie", "text": "At least as much. The key opens everything the data protects."},
        ],
        "learning_objectives": [
            "Manage the full key lifecycle: generation, storage, rotation, destruction",
            "Use HSM-backed services and customer-managed keys for sensitive data",
            "Design least-privilege key access, audit logging, and key backup",
        ],
        "quiz_questions": [
            {
                "question": "Where should high-sensitivity keys be stored?",
                "answers": [
                    {"id": "a", "text": "HSM-backed key services like Azure Key Vault", "correct": True},
                    {"id": "b", "text": "Plaintext config files", "correct": False},
                    {"id": "c", "text": "Source code repositories", "correct": False},
                    {"id": "d", "text": "Shared network drives", "correct": False},
                ],
            },
            {
                "question": "Why use customer-managed keys for sensitive data?",
                "answers": [
                    {"id": "a", "text": "To control rotation and revocation", "correct": True},
                    {"id": "b", "text": "To speed up encryption", "correct": False},
                    {"id": "c", "text": "To reduce storage costs", "correct": False},
                    {"id": "d", "text": "To avoid all encryption", "correct": False},
                ],
            },
            {
                "question": "What is the consequence of losing an encryption key?",
                "answers": [
                    {"id": "a", "text": "The encrypted data becomes unrecoverable", "correct": True},
                    {"id": "b", "text": "Nothing changes", "correct": False},
                    {"id": "c", "text": "A new key is issued automatically", "correct": False},
                    {"id": "d", "text": "The data decrypts automatically", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "app-security-arch",
        "title": "OWASP Top 10 & Secure Coding",
        "slug": "sc100-owasp-secure-coding",
        "description": "Turning the OWASP Top 10 into concrete secure-coding practices: input validation, output encoding, access control, and more.",
        "hook": "Injection is still king after twenty years. The fix isn't a tool — it's how you write the code.",
        "problem": "Developers ship features before security, and the same classes of application flaws — injection, broken access control — dominate breaches year after year.",
        "explanation": "The OWASP Top 10 catalogs the most critical web application risks, led by broken access control and injection. Secure coding converts these into disciplines. Input validation: never trust input — validate type, length, range, and format server-side, and treat all user data as hostile. Output encoding: encode output in the correct context (HTML, URL, JavaScript) to neutralize stored and reflected XSS. Parameterized queries defeat SQL injection by separating code from data. Access control: enforce authorization server-side on every request, never rely on client-side checks, and fail closed. Secrets: never hardcode credentials; use secret stores and workload identity. Authentication and session management: use secure defaults, protect session cookies, and enforce MFA. Defense in depth adds Web Application Firewalls and Content Security Policy, but they supplement — never replace — secure code. Integrate static analysis (SAST) and dependency scanning (SCA) into CI to catch flaws early.",
        "real_world_example": "A search box concatenates user input into a SQL query. An attacker types a crafted string that dumps the user table. The fix is a parameterized query — one line that separates data from command.",
        "summary": "Secure coding means validating all input, encoding all output, using parameterized queries, enforcing server-side access control, protecting secrets, and catching flaws early with SAST and SCA.",
        "curiosity_hook": "The number one OWASP risk isn't injection anymore — it's broken access control, because authorization bugs are silent while injection bugs are loud.",
        "dialogue": [
            {"speaker": "Peter", "text": "What's the OWASP Top 10?"},
            {"speaker": "Stewie", "text": "The ten most critical web app risks. Broken access control and injection lead the list."},
            {"speaker": "Peter", "text": "How do I stop injection?"},
            {"speaker": "Stewie", "text": "Parameterized queries. Separate code from data so input can't become commands."},
            {"speaker": "Peter", "text": "And XSS?"},
            {"speaker": "Stewie", "text": "Output encoding in the right context. HTML, URL, JavaScript — each needs its own escape."},
            {"speaker": "Peter", "text": "What about user input?"},
            {"speaker": "Stewie", "text": "Validate everything server-side. Type, length, range, format. Treat input as hostile."},
            {"speaker": "Peter", "text": "Access control?"},
            {"speaker": "Stewie", "text": "Enforce authorization on every request, server-side, and fail closed. Never trust the client."},
            {"speaker": "Peter", "text": "Secrets in code?"},
            {"speaker": "Stewie", "text": "Never. Use secret stores and workload identity instead of hardcoded credentials."},
            {"speaker": "Peter", "text": "Don't firewalls fix this?"},
            {"speaker": "Stewie", "text": "WAFs and CSP supplement secure code. They never replace it."},
            {"speaker": "Peter", "text": "How do I catch flaws early?"},
            {"speaker": "Stewie", "text": "SAST for static analysis, SCA for dependencies, both in CI."},
        ],
        "learning_objectives": [
            "Apply input validation and output encoding to prevent injection and XSS",
            "Enforce server-side access control and fail-closed authorization",
            "Use SAST, SCA, and secret scanning to catch flaws in CI",
        ],
        "quiz_questions": [
            {
                "question": "What is the primary defense against SQL injection?",
                "answers": [
                    {"id": "a", "text": "Parameterized queries", "correct": True},
                    {"id": "b", "text": "Longer passwords", "correct": False},
                    {"id": "c", "text": "More CPU", "correct": False},
                    {"id": "d", "text": "Client-side validation only", "correct": False},
                ],
            },
            {
                "question": "Which OWASP risk currently leads the Top 10?",
                "answers": [
                    {"id": "a", "text": "Broken access control", "correct": True},
                    {"id": "b", "text": "Hardware failure", "correct": False},
                    {"id": "c", "text": "Network latency", "correct": False},
                    {"id": "d", "text": "Disk space", "correct": False},
                ],
            },
            {
                "question": "Where must authorization be enforced?",
                "answers": [
                    {"id": "a", "text": "On every server-side request, failing closed", "correct": True},
                    {"id": "b", "text": "Only in the browser", "correct": False},
                    {"id": "c", "text": "Only on login", "correct": False},
                    {"id": "d", "text": "Never, rely on obscurity", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Ransomware: The Three-Phase Defense",
        "slug": "sc100-ransomware-three-phase",
        "description": "Microsoft's ransomware playbook: prepare recovery, limit scope, and harden entry — in that priority order.",
        "hook": "Ransomware math is simple: the harder recovery is, the more you pay. Prepare first, harden second.",
        "problem": "Organizations invest in prevention while ignoring recovery, so when ransomware strikes they cannot restore and end up paying — or losing everything.",
        "explanation": "Microsoft's ransomware guidance uses three phases in priority order. Phase 1: prepare your recovery plan. Make it harder to access or encrypt key data and easier to recover without paying. Prioritize BCDR: restore the entire enterprise from immutable storage. Identify business-critical systems in priority order — identity, human life, financial, product enablement, security monitoring. Back up all critical data automatically, protect backups against deliberate erasure and encryption, and exercise the BC/DR plan regularly. Phase 2: limit the scope of damage. Prioritize privileged access protection: end-to-end session security with Conditional Access, protect and monitor identity systems, mitigate lateral traversal by randomizing local account passwords and isolating service accounts, secure privileged accounts with MFA and passwordless, and use PAWs. Detect and respond: integrate XDR, monitor for adversaries disabling security controls, and rapidly isolate impacted devices. Phase 3: make it hard to get in — email security, endpoint protection, identity MFA, secure remote access, and patching. Do not let Phase 3 slow Phases 1 and 2.",
        "real_world_example": "Ransomware encrypts a hospital's servers. Because identity systems were backed up to immutable storage and the BC/DR plan was drilled, the hospital restores in hours without paying — while a rival that skipped backups pays millions.",
        "summary": "Prepare recovery first (immutable backups, BCDR, exercised plans), then limit blast radius (privileged access, XDR, isolation), then harden entry. Recovery readiness beats prevention polish.",
        "curiosity_hook": "Most ransomware victims never intended to pay — they just had no recoverable backup, so paying was the only option.",
        "dialogue": [
            {"speaker": "Peter", "text": "Ransomware plan. Stop them from getting in, right?"},
            {"speaker": "Stewie", "text": "Wrong order. Recovery comes first. Hardening second."},
            {"speaker": "Peter", "text": "Why recovery first?"},
            {"speaker": "Stewie", "text": "If you can't restore, attackers win even when prevention fails. Immutable backups change the math."},
            {"speaker": "Peter", "text": "What do we back up first?"},
            {"speaker": "Stewie", "text": "Identity systems. Then human life, financial, product enablement, security monitoring."},
            {"speaker": "Peter", "text": "Phase two?"},
            {"speaker": "Stewie", "text": "Limit the blast radius. Protect privileged access, stop lateral movement, isolate infected devices fast."},
            {"speaker": "Peter", "text": "Lateral movement?"},
            {"speaker": "Stewie", "text": "Randomize local admin passwords, isolate service accounts, secure privileged accounts with MFA."},
            {"speaker": "Peter", "text": "Phase three?"},
            {"speaker": "Stewie", "text": "Make entry hard. Email security, endpoint protection, MFA, secure remote access, patching."},
            {"speaker": "Peter", "text": "So prevention is last?"},
            {"speaker": "Stewie", "text": "Not last, but never at the expense of phases one and two. Recovery readiness wins."},
            {"speaker": "Peter", "text": "How often do we test recovery?"},
            {"speaker": "Stewie", "text": "Regularly. An untested restore is just a hope."},
        ],
        "learning_objectives": [
            "Order ransomware defense: recovery, blast radius, then hardening",
            "Design immutable, tested backups for business-critical systems",
            "Apply privileged access protection and rapid isolation during incidents",
        ],
        "quiz_questions": [
            {
                "question": "What is the first priority in Microsoft's ransomware guidance?",
                "answers": [
                    {"id": "a", "text": "Preparing the recovery plan and BCDR", "correct": True},
                    {"id": "b", "text": "Deploying more firewalls", "correct": False},
                    {"id": "c", "text": "Blocking all email", "correct": False},
                    {"id": "d", "text": "Increasing log retention", "correct": False},
                ],
            },
            {
                "question": "Why are immutable backups critical against ransomware?",
                "answers": [
                    {"id": "a", "text": "They cannot be deleted or modified during retention", "correct": True},
                    {"id": "b", "text": "They are faster to create", "correct": False},
                    {"id": "c", "text": "They require no storage", "correct": False},
                    {"id": "d", "text": "They remove the need for MFA", "correct": False},
                ],
            },
            {
                "question": "What mitigates lateral traversal during a ransomware attack?",
                "answers": [
                    {"id": "a", "text": "Randomizing local admin passwords and isolating service accounts", "correct": True},
                    {"id": "b", "text": "Increasing user privileges", "correct": False},
                    {"id": "c", "text": "Disabling all logging", "correct": False},
                    {"id": "d", "text": "Removing antivirus", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "devsecops-arch",
        "title": "Securing CI/CD Pipelines",
        "slug": "sc100-cicd-pipeline-security",
        "description": "The four-stage control model and concrete pipeline controls: design, code, pipeline, and operations.",
        "hook": "Your pipeline has more privileges than your admins. Secure it like the production system it is.",
        "problem": "CI/CD pipelines hold secrets and deploy privileges, but teams treat them as infrastructure, leaving them open to supply chain compromise and secret theft.",
        "explanation": "The CAF identifies a four-stage control model for DevSecOps. Secure the design: threat modeling, IDE security plugins, pre-commit hooks, and peer review. Secure the code: vulnerability scanning in centralized repositories with remediation. Secure the pipeline: build and release pipelines that automate and standardize secure deployment. Secure operations: manage security in production with infrastructure as code and monitoring. Concrete pipeline controls: separate build, test, and deploy stages; enforce branch protection and require pull request reviews; run SAST, dependency scanning, and secret scanning in CI; scan IaC before deployment; require environment-based deployment approvals for production; sign and verify build artifacts; and use workload identity federation for service connections instead of stored secrets. Apply Zero Trust to the pipeline: verify every pipeline action, scope service identities with least privilege, and isolate pipeline environments assuming breach.",
        "real_world_example": "A pipeline stored a production key in a variable group. An attacker who read the repo used it to deploy a backdoored container. After switching to workload identity federation and scanning for secrets in CI, the same read yields nothing deployable.",
        "summary": "Secure pipelines across four stages — design, code, pipeline, operations — with branch protection, scans in CI, artifact signing, environment approvals, and workload identity instead of stored secrets.",
        "curiosity_hook": "A supply chain attack isn't about your code at all — it's about the build tools, dependencies, and pipeline that produce it.",
        "dialogue": [
            {"speaker": "Peter", "text": "Pipelines build our software. Why do they need security?"},
            {"speaker": "Stewie", "text": "Because they hold deploy privileges and secrets. Attackers love pipelines."},
            {"speaker": "Peter", "text": "What's the control model?"},
            {"speaker": "Stewie", "text": "Four stages: secure design, secure code, secure pipeline, secure operations."},
            {"speaker": "Peter", "text": "Secure design?"},
            {"speaker": "Stewie", "text": "Threat modeling, IDE plugins, pre-commit hooks, peer review. Catch it before it's written."},
            {"speaker": "Peter", "text": "Secure code?"},
            {"speaker": "Stewie", "text": "Vulnerability scanning in central repos, with actual remediation."},
            {"speaker": "Peter", "text": "And the pipeline itself?"},
            {"speaker": "Stewie", "text": "Separate build, test, deploy. Branch protection, PR reviews, scans in CI, IaC scanning."},
            {"speaker": "Peter", "text": "Deployment approval?"},
            {"speaker": "Stewie", "text": "Environment-based approvals for production. And sign and verify artifacts."},
            {"speaker": "Peter", "text": "Stored secrets in pipelines?"},
            {"speaker": "Stewie", "text": "No. Workload identity federation instead. Nothing to steal."},
            {"speaker": "Peter", "text": "Zero Trust in pipelines?"},
            {"speaker": "Stewie", "text": "Verify every action, least privilege for service identities, isolate environments."},
        ],
        "learning_objectives": [
            "Apply the four-stage DevSecOps control model",
            "Design branch protection, CI scans, artifact signing, and approvals",
            "Replace stored pipeline secrets with workload identity federation",
        ],
        "quiz_questions": [
            {
                "question": "What replaces stored secrets for pipeline service connections?",
                "answers": [
                    {"id": "a", "text": "Workload identity federation", "correct": True},
                    {"id": "b", "text": "Hardcoded tokens", "correct": False},
                    {"id": "c", "text": "Shared admin passwords", "correct": False},
                    {"id": "d", "text": "Plaintext keys in repos", "correct": False},
                ],
            },
            {
                "question": "Which stage of the control model includes threat modeling and pre-commit hooks?",
                "answers": [
                    {"id": "a", "text": "Secure the design", "correct": True},
                    {"id": "b", "text": "Secure operations", "correct": False},
                    {"id": "c", "text": "Secure the pipeline", "correct": False},
                    {"id": "d", "text": "Secure the code", "correct": False},
                ],
            },
            {
                "question": "Why sign and verify build artifacts?",
                "answers": [
                    {"id": "a", "text": "To prove integrity and detect tampering", "correct": True},
                    {"id": "b", "text": "To speed up builds", "correct": False},
                    {"id": "c", "text": "To reduce storage", "correct": False},
                    {"id": "d", "text": "To bypass testing", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "privileged-access",
        "title": "Tiered Administration & PAWs",
        "slug": "sc100-tiered-admin-paw",
        "description": "The tiered admin model, privileged access workstations, and protecting the identity plane from credential theft.",
        "hook": "One admin desktop on the internet can hand an attacker the keys to everything. Tier your admin plane like a bank vault.",
        "problem": "Admins perform privileged tasks from the same workstations they browse and read email on, so one compromise of a desktop becomes compromise of the entire directory.",
        "explanation": "The tiered admin model separates administrative access by impact. Tier 0 covers identity and control plane: domain controllers, Entra tenant, and identity infrastructure — the highest impact. Tier 1 covers servers and applications. Tier 2 covers user workstations and standard devices. Administrators use accounts from the tier of the systems they manage, and higher-tier credentials never touch lower-tier devices. Privileged Access Workstations (PAWs) are hardened, dedicated machines for Tier 0 and Tier 1 administration, blocking browsing, email, and other high-risk activity. Combined controls: phishing-resistant MFA and passwordless for privileged accounts, Privileged Identity Management for just-in-time elevation, Conditional Access gating admin portals to compliant managed devices, break-glass accounts monitored heavily and tested on a schedule, and continuous monitoring of identity systems. Mitigate lateral traversal by randomizing local account passwords and isolating service accounts so a stolen credential cannot hop tiers.",
        "real_world_example": "A phished admin signs in from a personal laptop. Because admin portals are gated by Conditional Access to PAWs and elevation is just-in-time through PIM, the attacker gets nothing — the session is blocked before any privilege activates.",
        "summary": "Separate admin access into tiers, do privileged work only from PAWs, require phishing-resistant MFA and just-in-time elevation, and monitor the identity plane continuously.",
        "curiosity_hook": "Tier 0 isn't about servers — it's about the identity plane itself. Compromise it and every tier below is already lost.",
        "dialogue": [
            {"speaker": "Peter", "text": "Admins manage everything. What could go wrong?"},
            {"speaker": "Stewie", "text": "Admins browsing email on the same machine that holds the keys. That's what."},
            {"speaker": "Peter", "text": "What's the fix?"},
            {"speaker": "Stewie", "text": "The tiered admin model. Separate access by impact."},
            {"speaker": "Peter", "text": "Tiers?"},
            {"speaker": "Stewie", "text": "Tier 0 is identity and control plane. Tier 1 servers and apps. Tier 2 workstations."},
            {"speaker": "Peter", "text": "Why does tier order matter?"},
            {"speaker": "Stewie", "text": "Higher-tier credentials must never touch lower-tier devices. No browsing on the admin box."},
            {"speaker": "Peter", "text": "What about privileged access workstations?"},
            {"speaker": "Stewie", "text": "PAWs. Hardened dedicated machines for Tier 0 and 1 admin. No email, no random browsing."},
            {"speaker": "Peter", "text": "MFA for admins?"},
            {"speaker": "Stewie", "text": "Phishing-resistant MFA and passwordless. Plus PIM for just-in-time elevation."},
            {"speaker": "Peter", "text": "What if Conditional Access locks us out?"},
            {"speaker": "Stewie", "text": "Break-glass accounts, heavily monitored, tested on a schedule."},
            {"speaker": "Peter", "text": "Lateral movement between tiers?"},
            {"speaker": "Stewie", "text": "Randomize local admin passwords and isolate service accounts. Stop the hop."},
            {"speaker": "Peter", "text": "So admin access is a ceremony?"},
            {"speaker": "Stewie", "text": "A deliberate, monitored ceremony. It's the vault door to everything."},
        ],
        "learning_objectives": [
            "Explain the three-tier administrative model and its boundaries",
            "Design privileged access workstations and just-in-time elevation",
            "Protect the identity plane with break-glass, monitoring, and lateral-movement controls",
        ],
        "quiz_questions": [
            {
                "question": "What does Tier 0 in the admin model cover?",
                "answers": [
                    {"id": "a", "text": "Identity and control plane infrastructure", "correct": True},
                    {"id": "b", "text": "Standard user workstations", "correct": False},
                    {"id": "c", "text": "IoT devices", "correct": False},
                    {"id": "d", "text": "Guest Wi-Fi", "correct": False},
                ],
            },
            {
                "question": "What is a PAW?",
                "answers": [
                    {"id": "a", "text": "A hardened dedicated workstation for privileged administration", "correct": True},
                    {"id": "b", "text": "A password audit tool", "correct": False},
                    {"id": "c", "text": "A patch scheduler", "correct": False},
                    {"id": "d", "text": "A firewall appliance", "correct": False},
                ],
            },
            {
                "question": "How do you mitigate lateral movement of a stolen admin credential?",
                "answers": [
                    {"id": "a", "text": "Randomize local admin passwords and isolate service accounts", "correct": True},
                    {"id": "b", "text": "Share one global admin account", "correct": False},
                    {"id": "c", "text": "Disable all logging", "correct": False},
                    {"id": "d", "text": "Grant all users admin rights", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "ai-security",
        "title": "AI Red Teaming & Content Filtering",
        "slug": "sc100-ai-red-teaming",
        "description": "MCSB AI controls AI-1 through AI-7: approved models, layered filtering, meta-prompts, least privilege, and continuous red teaming.",
        "hook": "AI doesn't fail like software. It fails when someone asks the right wrong question — which is exactly what red teaming discovers.",
        "problem": "AI systems have unique attack surfaces — prompt injection, jailbreaks, data exfiltration — that traditional security testing does not cover.",
        "explanation": "MCSB defines AI security controls AI-1 through AI-7. AI-1: use only approved models after formal verification. AI-2: implement multi-layered content filtering across input prompts, processing, and outputs. AI-3: adopt safety meta-prompts to guide model behavior. AI-4: apply least privilege for agent functions. AI-5: ensure human-in-the-loop for critical actions. AI-6: establish monitoring and detection for model inference, API calls, and plugin interactions. AI-7: perform continuous AI red teaming. Red teaming probes the model with adversarial inputs — prompt injection, jailbreaking, adversarial perturbation — to find weaknesses before attackers do. Microsoft's PyRIT (Python Risk Identification Tool) automates this testing. Ground the work in MITRE ATLAS and the OWASP Top 10 for LLM applications. Multi-layered filtering means checking inputs, sanitizing processing, and filtering outputs for harmful or leaked content — a single filter layer is not enough.",
        "real_world_example": "Red teaming reveals that a banking chatbot leaks its system prompt when asked in a specific phrasing. The team adds an output filter and a safety meta-prompt, then retests — the leak is closed before production.",
        "summary": "Apply AI-1 through AI-7: approve models, layer content filters, use meta-prompts, scope agents with least privilege, keep humans in the loop, monitor inference, and red team continuously with PyRIT.",
        "curiosity_hook": "PyRIT is Microsoft's automated red teaming toolkit — it runs thousands of adversarial prompts against a model to find the jailbreak your users might type by accident.",
        "dialogue": [
            {"speaker": "Peter", "text": "Our AI model is smart. What's to attack?"},
            {"speaker": "Stewie", "text": "Prompt injection, jailbreaks, data leaks. AI has a whole new attack surface."},
            {"speaker": "Peter", "text": "What are the MCSB AI controls?"},
            {"speaker": "Stewie", "text": "AI-1 through AI-7. Approved models, content filtering, meta-prompts, and more."},
            {"speaker": "Peter", "text": "Content filtering?"},
            {"speaker": "Stewie", "text": "Multi-layered. Inputs, processing, and outputs. One filter layer is never enough."},
            {"speaker": "Peter", "text": "What are safety meta-prompts?"},
            {"speaker": "Stewie", "text": "Instructions that guide model behavior against manipulation. AI-3."},
            {"speaker": "Peter", "text": "Agents need least privilege too?"},
            {"speaker": "Stewie", "text": "Yes, AI-4. Scope agent functions tightly. And keep humans in the loop for critical actions."},
            {"speaker": "Peter", "text": "Monitoring?"},
            {"speaker": "Stewie", "text": "AI-6. Watch inference, API calls, and plugin interactions for anomalies."},
            {"speaker": "Peter", "text": "How do we test all this?"},
            {"speaker": "Stewie", "text": "Continuous red teaming, AI-7. PyRIT automates the adversarial prompts."},
            {"speaker": "Peter", "text": "Ground it in frameworks?"},
            {"speaker": "Stewie", "text": "MITRE ATLAS and OWASP Top 10 for LLM apps."},
            {"speaker": "Peter", "text": "So AI security is a discipline, not a checkbox."},
            {"speaker": "Stewie", "text": "Exactly. And it never stops — the models keep learning new tricks."},
        ],
        "learning_objectives": [
            "Apply MCSB AI controls AI-1 through AI-7",
            "Design multi-layered content filtering and safety meta-prompts",
            "Use continuous red teaming with PyRIT grounded in MITRE ATLAS",
        ],
        "quiz_questions": [
            {
                "question": "Which MCSB AI control requires multi-layered content filtering?",
                "answers": [
                    {"id": "a", "text": "AI-2", "correct": True},
                    {"id": "b", "text": "AI-1", "correct": False},
                    {"id": "c", "text": "AI-5", "correct": False},
                    {"id": "d", "text": "AI-7", "correct": False},
                ],
            },
            {
                "question": "What tool automates AI red teaming?",
                "answers": [
                    {"id": "a", "text": "PyRIT", "correct": True},
                    {"id": "b", "text": "Nmap", "correct": False},
                    {"id": "c", "text": "Wireshark", "correct": False},
                    {"id": "d", "text": "Burp Suite", "correct": False},
                ],
            },
            {
                "question": "Which AI control keeps humans in the loop for critical actions?",
                "answers": [
                    {"id": "a", "text": "AI-5", "correct": True},
                    {"id": "b", "text": "AI-2", "correct": False},
                    {"id": "c", "text": "AI-3", "correct": False},
                    {"id": "d", "text": "AI-6", "correct": False},
                ],
            },
        ],
    },
]
LESSONS = rewrite_lessons_dialogues(LESSONS)
