from dialogue_rewriter import rewrite_lessons_dialogues


LESSONS = [
    {
        "concept_slug": "compliance",
        "title": "Translate Compliance Into Security Controls",
        "slug": "sc100-compliance-control-mapping",
        "category": "compliance",
        "difficulty": 4,
        "hook": "Auditors do not want vibes. They want proof that a requirement became a control.",
        "description": "How architects turn regulatory obligations into practical controls, owners, evidence, and validation.",
        "dialogue": [
            {"speaker": "Peter", "text": "So compliance says protect customer data. That sounds... vague."},
            {"speaker": "Stewie", "text": "Exactly. The architect translates that vague requirement into specific security controls."},
            {"speaker": "Peter", "text": "Like encryption?"},
            {"speaker": "Stewie", "text": "Encryption, access reviews, logging, retention, data loss prevention, and evidence collection."},
            {"speaker": "Peter", "text": "Evidence collection?"},
            {"speaker": "Stewie", "text": "Yes. If you cannot prove the control runs, the auditor treats it like theater."},
            {"speaker": "Peter", "text": "So every rule needs an owner?"},
            {"speaker": "Stewie", "text": "Owner, implementation, test method, evidence source, and remediation plan. That is the grown-up version."},
            {"speaker": "Peter", "text": "Where do tools fit in?"},
            {"speaker": "Stewie", "text": "Purview maps data and policies. Azure Policy enforces resource rules. Defender for Cloud validates posture."},
            {"speaker": "Peter", "text": "So compliance is design work, not paperwork?"},
            {"speaker": "Stewie", "text": "Exactly. Paperwork documents the design. It does not replace the design."},
        ],
        "learning_objectives": [
            "Map regulatory requirements to technical and operational controls",
            "Define owners, evidence, validation methods, and remediation paths",
            "Use Purview, Azure Policy, and Defender for Cloud as compliance design inputs",
        ],
    },
    {
        "concept_slug": "identity-access",
        "title": "Conditional Access for AI Agents",
        "slug": "sc100-ai-agent-conditional-access",
        "category": "identity",
        "difficulty": 5,
        "hook": "AI agents are not interns. Do not give them permanent keys to production.",
        "description": "Designing identity controls for agentic workloads using least privilege, signals, and scoped access.",
        "dialogue": [
            {"speaker": "Peter", "text": "Wait, AI agents need Conditional Access too? They are not people."},
            {"speaker": "Stewie", "text": "They are identities performing actions. That makes them very interesting to attackers."},
            {"speaker": "Peter", "text": "So what can we check if there is no human logging in?"},
            {"speaker": "Stewie", "text": "Workload identity, resource scope, risk signals, network location, device context, and requested action."},
            {"speaker": "Peter", "text": "Could an agent just get global admin?"},
            {"speaker": "Stewie", "text": "Only if someone enjoys starring in incident reports. Agents need narrow roles and time-bound access."},
            {"speaker": "Peter", "text": "What about plugins and connectors?"},
            {"speaker": "Stewie", "text": "Treat every connector as a data path. Approve it, log it, and restrict what it can reach."},
            {"speaker": "Peter", "text": "So Zero Trust applies to bots too?"},
            {"speaker": "Stewie", "text": "Especially bots. Verify explicitly, grant least privilege, and assume the prompt can be hostile."},
            {"speaker": "Peter", "text": "That last part feels ominous."},
            {"speaker": "Stewie", "text": "Good. Ominous is cheaper than breach recovery."},
        ],
        "learning_objectives": [
            "Apply Zero Trust principles to AI agent identities",
            "Scope agent permissions to specific resources and actions",
            "Design controls for connectors, plugins, and non-human access",
        ],
    },
    {
        "concept_slug": "privileged-access",
        "title": "Secure Tenant Administration",
        "slug": "sc100-secure-tenant-administration",
        "category": "privileged-access",
        "difficulty": 4,
        "hook": "Your tenant admin plane is the crown jewels wearing a tiny paper hat.",
        "description": "Hardening Microsoft cloud administration with break-glass accounts, role separation, and protected workflows.",
        "dialogue": [
            {"speaker": "Peter", "text": "Tenant admin sounds like the person who can fix everything."},
            {"speaker": "Stewie", "text": "And break everything. The admin plane controls identity, policy, data access, and recovery."},
            {"speaker": "Peter", "text": "So step one is MFA?"},
            {"speaker": "Stewie", "text": "MFA, phishing-resistant auth, Privileged Identity Management, and separate admin accounts."},
            {"speaker": "Peter", "text": "Separate from my normal email account?"},
            {"speaker": "Stewie", "text": "Yes. Daily browsing and global admin should never share the same identity."},
            {"speaker": "Peter", "text": "What if Conditional Access locks everyone out?"},
            {"speaker": "Stewie", "text": "You maintain break-glass accounts, monitor them heavily, and test them on a schedule."},
            {"speaker": "Peter", "text": "Do admins need special machines too?"},
            {"speaker": "Stewie", "text": "For high privilege, yes. Use hardened workstations and block unmanaged devices from admin portals."},
            {"speaker": "Peter", "text": "So admin access is a ceremony?"},
            {"speaker": "Stewie", "text": "A deliberate ceremony with logs, approvals, time limits, and no snacks in production."},
        ],
        "learning_objectives": [
            "Design separated admin identities and privileged workflows",
            "Plan break-glass access without creating hidden backdoors",
            "Use hardened workstations and Conditional Access for admin portals",
        ],
    },
    {
        "concept_slug": "privileged-access",
        "title": "Cloud Infrastructure Entitlement Management",
        "slug": "sc100-ciem-entitlement-management",
        "category": "privileged-access",
        "difficulty": 5,
        "hook": "Cloud permissions multiply like gremlins after midnight.",
        "description": "Using CIEM thinking to find excessive permissions across subscriptions, tenants, and clouds.",
        "dialogue": [
            {"speaker": "Peter", "text": "What is CIEM? Another security acronym escaped from a lab?"},
            {"speaker": "Stewie", "text": "Cloud Infrastructure Entitlement Management. It finds who can do what across your cloud estate."},
            {"speaker": "Peter", "text": "Isn't that just RBAC?"},
            {"speaker": "Stewie", "text": "RBAC is the raw permission model. CIEM analyzes effective permissions and risky combinations."},
            {"speaker": "Peter", "text": "Effective permissions?"},
            {"speaker": "Stewie", "text": "The real result after roles, groups, inherited scopes, service principals, and stale assignments collide."},
            {"speaker": "Peter", "text": "So it spots over-permissioned identities?"},
            {"speaker": "Stewie", "text": "Yes, especially identities with permissions they never use. Those are attack paths waiting politely."},
            {"speaker": "Peter", "text": "What should an architect recommend?"},
            {"speaker": "Stewie", "text": "Inventory permissions, remove unused rights, require just-in-time elevation, and monitor privilege drift."},
            {"speaker": "Peter", "text": "Privilege drift sounds sneaky."},
            {"speaker": "Stewie", "text": "It is. Nobody plans chaos. They approve it one exception at a time."},
        ],
        "learning_objectives": [
            "Explain effective permissions and privilege drift",
            "Identify over-permissioned users, groups, and workload identities",
            "Recommend least-privilege and just-in-time remediation patterns",
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Centralized Logging Architecture",
        "slug": "sc100-centralized-logging-architecture",
        "category": "security-operations",
        "difficulty": 4,
        "hook": "If logs live everywhere, investigations go nowhere.",
        "description": "Designing useful logging across identity, endpoints, cloud resources, SaaS, and network controls.",
        "dialogue": [
            {"speaker": "Peter", "text": "We already have logs. They are... somewhere."},
            {"speaker": "Stewie", "text": "A tragic phrase. Security logs need central collection, retention, normalization, and alerting."},
            {"speaker": "Peter", "text": "What should we collect first?"},
            {"speaker": "Stewie", "text": "Identity sign-ins, admin actions, endpoint alerts, cloud control-plane events, and data access."},
            {"speaker": "Peter", "text": "Can we just collect everything forever?"},
            {"speaker": "Stewie", "text": "If your budget enjoys combustion. Choose retention by investigation needs and regulatory requirements."},
            {"speaker": "Peter", "text": "Where does Sentinel fit?"},
            {"speaker": "Stewie", "text": "Sentinel correlates events, runs analytics, triggers automation, and supports hunting across sources."},
            {"speaker": "Peter", "text": "What makes a log useful?"},
            {"speaker": "Stewie", "text": "Timestamp, actor, action, target, result, source IP, and enough context to answer what happened."},
            {"speaker": "Peter", "text": "So logging is architecture?"},
            {"speaker": "Stewie", "text": "Precisely. Logs are the memory of your security program. Do not give it amnesia."},
        ],
        "learning_objectives": [
            "Select high-value security log sources",
            "Design retention and normalization around investigation needs",
            "Use SIEM and SOAR capabilities to correlate and respond",
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "MITRE ATT&CK Coverage Design",
        "slug": "sc100-mitre-attack-coverage-design",
        "category": "security-operations",
        "difficulty": 4,
        "hook": "A dashboard full of alerts is not the same thing as detection coverage.",
        "description": "Mapping detections to attacker tactics so SecOps can see gaps before attackers use them.",
        "dialogue": [
            {"speaker": "Peter", "text": "Our SOC has alerts. Does that mean we have coverage?"},
            {"speaker": "Stewie", "text": "Not necessarily. You may have twenty alerts for phishing and nothing for lateral movement."},
            {"speaker": "Peter", "text": "How does MITRE help?"},
            {"speaker": "Stewie", "text": "ATT&CK organizes attacker behavior into tactics and techniques, like persistence, discovery, and exfiltration."},
            {"speaker": "Peter", "text": "So we map detections to techniques?"},
            {"speaker": "Stewie", "text": "Exactly. Then you see which behaviors are detected, blocked, logged, or completely invisible."},
            {"speaker": "Peter", "text": "What if a technique has no detection?"},
            {"speaker": "Stewie", "text": "That becomes a design requirement: new telemetry, analytics, control changes, or accepted risk."},
            {"speaker": "Peter", "text": "Does this help with executives?"},
            {"speaker": "Stewie", "text": "Very much. It turns security monitoring from vibes into a coverage model."},
            {"speaker": "Peter", "text": "So fewer random alerts, more intentional detection?"},
            {"speaker": "Stewie", "text": "Yes. We are hunting attackers, not collecting beeps."},
        ],
        "learning_objectives": [
            "Map detection rules to MITRE ATT&CK tactics and techniques",
            "Identify telemetry and analytics gaps",
            "Turn coverage gaps into security architecture requirements",
        ],
    },
    {
        "concept_slug": "data-security",
        "title": "Secure Data for Copilot and AI Workloads",
        "slug": "sc100-copilot-ai-data-security",
        "category": "data-security",
        "difficulty": 5,
        "hook": "AI does not leak data by magic. It leaks what your permissions already exposed.",
        "description": "Designing data controls for AI by fixing classification, access, oversharing, and auditability.",
        "dialogue": [
            {"speaker": "Peter", "text": "People keep saying Copilot will leak secrets. Is the AI stealing things?"},
            {"speaker": "Stewie", "text": "Usually no. It surfaces data the user already has permission to read."},
            {"speaker": "Peter", "text": "So the real problem is oversharing?"},
            {"speaker": "Stewie", "text": "Exactly. AI makes messy permissions painfully visible."},
            {"speaker": "Peter", "text": "What should we fix first?"},
            {"speaker": "Stewie", "text": "Classify sensitive data, tighten access, remove stale sharing links, and enforce retention policies."},
            {"speaker": "Peter", "text": "Does Purview help here?"},
            {"speaker": "Stewie", "text": "Yes. Sensitivity labels, DLP, audit, eDiscovery, and data lifecycle controls are central."},
            {"speaker": "Peter", "text": "What about prompts with confidential info?"},
            {"speaker": "Stewie", "text": "Log usage, set policy boundaries, educate users, and monitor risky data movement."},
            {"speaker": "Peter", "text": "So AI readiness is data hygiene?"},
            {"speaker": "Stewie", "text": "Brutally so. Copilot is a mirror. Sometimes the mirror has incident response energy."},
        ],
        "learning_objectives": [
            "Explain how AI exposes existing data permission problems",
            "Use classification, DLP, audit, and lifecycle controls for AI data protection",
            "Prioritize oversharing remediation before broad AI rollout",
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Ransomware Recovery Architecture",
        "slug": "sc100-ransomware-recovery-architecture",
        "category": "resilience",
        "difficulty": 4,
        "hook": "A backup you cannot restore is just expensive nostalgia.",
        "description": "Designing ransomware resilience with immutable backups, recovery priorities, identity isolation, and tested runbooks.",
        "dialogue": [
            {"speaker": "Peter", "text": "If ransomware hits, we just restore from backup, right?"},
            {"speaker": "Stewie", "text": "Only if the backups survived, the credentials are clean, and the restore plan was tested."},
            {"speaker": "Peter", "text": "Attackers go after backups too?"},
            {"speaker": "Stewie", "text": "Of course. Deleting backups is how they increase pressure to pay."},
            {"speaker": "Peter", "text": "So what is the architecture answer?"},
            {"speaker": "Stewie", "text": "Immutable backups, isolated recovery credentials, separate admin paths, and prioritized restoration tiers."},
            {"speaker": "Peter", "text": "Prioritized tiers?"},
            {"speaker": "Stewie", "text": "Restore identity, networking, security monitoring, and critical business systems before nice-to-have services."},
            {"speaker": "Peter", "text": "Do we test this?"},
            {"speaker": "Stewie", "text": "Regularly. Tabletop exercises are good. Actual restore drills are better."},
            {"speaker": "Peter", "text": "What about patching?"},
            {"speaker": "Stewie", "text": "Patching reduces entry points. Recovery architecture limits blast radius when prevention fails."},
            {"speaker": "Peter", "text": "So resilience means assuming impact?"},
            {"speaker": "Stewie", "text": "Yes. Hope is not a recovery time objective."},
        ],
        "learning_objectives": [
            "Design backup protection against ransomware tampering",
            "Prioritize recovery dependencies and critical business services",
            "Use tested runbooks and isolated credentials for recovery",
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Patch Management Antipatterns",
        "slug": "sc100-patch-management-antipatterns",
        "category": "security-operations",
        "difficulty": 4,
        "hook": "Most patch failures start as process failures wearing technical costumes.",
        "description": "Specific patching mistakes from the SC-100 material and how architects design around them.",
        "dialogue": [
            {"speaker": "Peter", "text": "If a patch is not marked critical, can we wait?"},
            {"speaker": "Stewie", "text": "That is how noncritical becomes breach retrospective vocabulary."},
            {"speaker": "Peter", "text": "What other patching mistakes happen a lot?"},
            {"speaker": "Stewie", "text": "Waiting for perfect certainty, blaming security for outages, and customizing patch scope until nothing is standard anymore."},
            {"speaker": "Peter", "text": "Customizing sounds responsible though."},
            {"speaker": "Stewie", "text": "Only until you create a one-off build nobody tested, documented, or can recover quickly."},
            {"speaker": "Peter", "text": "Does patching mean just servers and laptops?"},
            {"speaker": "Stewie", "text": "No. Containers, apps, firmware, network gear, IoT, OT. Attackers love whatever you forgot to inventory."},
            {"speaker": "Peter", "text": "So what does the architect actually design?"},
            {"speaker": "Stewie", "text": "Ownership, cadence, exception handling, validation, rollback, and visibility across every asset class."},
        ],
        "learning_objectives": [
            "Identify patch management antipatterns from the SC-100 guidance",
            "Extend patching beyond operating systems to firmware, apps, containers, and devices",
            "Design ownership, exception, and rollback processes around patching",
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Verify Explicitly With Real Signals",
        "slug": "sc100-verify-explicitly-signals",
        "category": "zero-trust",
        "difficulty": 5,
        "hook": "Zero Trust is not one MFA prompt. It is many signals making one decision.",
        "description": "A more particular lesson on the first Zero Trust principle: verify explicitly using identity, device, workload, and anomaly signals.",
        "dialogue": [
            {"speaker": "Peter", "text": "Verify explicitly just means ask for MFA, right?"},
            {"speaker": "Stewie", "text": "That is one signal. Useful, but nowhere near whole story."},
            {"speaker": "Peter", "text": "What else should be checked?"},
            {"speaker": "Stewie", "text": "User identity, device health, location, workload identity, data sensitivity, network path, and unusual behavior."},
            {"speaker": "Peter", "text": "So access can change per request?"},
            {"speaker": "Stewie", "text": "Precisely. Same user, different device, different risk, different answer."},
            {"speaker": "Peter", "text": "What about service-to-service calls?"},
            {"speaker": "Stewie", "text": "Same rule. Verify workload identity and the exact action being requested."},
            {"speaker": "Peter", "text": "So static trust lists age badly?"},
            {"speaker": "Stewie", "text": "Like milk in summer. Explicit verification is contextual, continuous, and rude to assumptions."},
        ],
        "learning_objectives": [
            "Explain verify explicitly as a multi-signal decision model",
            "Use device, identity, workload, and anomaly signals in access design",
            "Apply contextual verification to both human and workload access",
        ],
    },
    {
        "concept_slug": "privileged-access",
        "title": "JIT and JEA for Least Privilege",
        "slug": "sc100-jit-jea-least-privilege",
        "category": "privileged-access",
        "difficulty": 5,
        "hook": "Permanent admin rights are convenience today, incident scope tomorrow.",
        "description": "A specific SC-100 lesson on just-in-time and just-enough-access as the practical form of least privilege.",
        "dialogue": [
            {"speaker": "Peter", "text": "Least privilege sounds nice, but admins still need to admin things."},
            {"speaker": "Stewie", "text": "Exactly. That is why JIT and JEA exist instead of fantasy."},
            {"speaker": "Peter", "text": "Difference?"},
            {"speaker": "Stewie", "text": "Just-in-time controls when privilege exists. Just-enough-access controls how much privilege appears."},
            {"speaker": "Peter", "text": "So no permanent global admin?"},
            {"speaker": "Stewie", "text": "Only if your threat model is written by the attacker."},
            {"speaker": "Peter", "text": "What supports this pattern?"},
            {"speaker": "Stewie", "text": "PIM approvals, time bounds, task-scoped roles, audited elevation, and frequent access reviews."},
            {"speaker": "Peter", "text": "Why does this matter so much?"},
            {"speaker": "Stewie", "text": "Because stolen standing privilege turns one phish into enterprise-wide consequences."},
        ],
        "learning_objectives": [
            "Differentiate just-in-time from just-enough-access",
            "Reduce standing privilege in administrative workflows",
            "Design approval, auditing, and review around privileged elevation",
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Assume Breach and Segment Blast Radius",
        "slug": "sc100-assume-breach-segmentation",
        "category": "zero-trust",
        "difficulty": 5,
        "hook": "Assume breach does not mean surrender. It means architecture with trust issues.",
        "description": "A focused lesson on microsegmentation, encryption, telemetry, and containment under the assume-breach principle.",
        "dialogue": [
            {"speaker": "Peter", "text": "Assume breach sounds depressing."},
            {"speaker": "Stewie", "text": "It is realistic, which is much cheaper than optimistic."},
            {"speaker": "Peter", "text": "What changes when we assume breach?"},
            {"speaker": "Stewie", "text": "You segment systems, encrypt paths end to end, log aggressively, and design so one compromise cannot become ten."},
            {"speaker": "Peter", "text": "Is this mainly network segmentation?"},
            {"speaker": "Stewie", "text": "Network, identity, applications, data paths, admin tiers. Blast radius reduction is a team sport."},
            {"speaker": "Peter", "text": "How do we know movement is happening?"},
            {"speaker": "Stewie", "text": "Telemetry and analytics. Without them you are not assuming breach, you are merely hosting it."},
            {"speaker": "Peter", "text": "So containment is first-class design?"},
            {"speaker": "Stewie", "text": "Exactly. Breach happens. Catastrophe should not."},
        ],
        "learning_objectives": [
            "Explain assume-breach as a containment design principle",
            "Use segmentation and encryption to reduce attacker movement",
            "Tie analytics and telemetry to breach detection and containment",
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "CAF, WAF, MCRA, and MCSB: Which One Answers What?",
        "slug": "sc100-framework-map-caf-waf-mcra-mcsb",
        "category": "cloud-frameworks",
        "difficulty": 5,
        "hook": "Four Microsoft frameworks. Same tenant. Very different jobs.",
        "description": "A specific framework-comparison lesson based on the SC-100 text so architects know which guidance to reach for in each scenario.",
        "dialogue": [
            {"speaker": "Peter", "text": "I keep mixing up CAF, WAF, MCRA, and MCSB."},
            {"speaker": "Stewie", "text": "Common condition. They are related, not interchangeable."},
            {"speaker": "Peter", "text": "Quick map?"},
            {"speaker": "Stewie", "text": "CAF guides cloud adoption journey. WAF evaluates workload quality. MCRA gives reference architectures. MCSB defines security control baseline."},
            {"speaker": "Peter", "text": "So if I am designing landing zones?"},
            {"speaker": "Stewie", "text": "Start with CAF. If you are reviewing workload tradeoffs, lean on WAF."},
            {"speaker": "Peter", "text": "And reference designs?"},
            {"speaker": "Stewie", "text": "MCRA. If you need security benchmark controls for Azure services, MCSB."},
            {"speaker": "Peter", "text": "So architects need all four, but for different questions."},
            {"speaker": "Stewie", "text": "Exactly. Confusing them is how guidance turns into decorative PDF furniture."},
        ],
        "learning_objectives": [
            "Differentiate CAF, WAF, MCRA, and MCSB by purpose",
            "Choose the right framework for adoption, architecture, benchmark, and workload review",
            "Explain how the frameworks complement each other in SC-100 design work",
        ],
    },
    {
        "concept_slug": "identity-access",
        "title": "Endpoint Compliance and BYOD Access Design",
        "slug": "sc100-endpoint-compliance-byod",
        "category": "identity",
        "difficulty": 5,
        "hook": "A valid password on an unhealthy device is still a bad idea.",
        "description": "A more particular SC-100 lesson on endpoints as a Zero Trust pillar, especially unmanaged and bring-your-own devices.",
        "dialogue": [
            {"speaker": "Peter", "text": "If the user passes MFA, why care about the device?"},
            {"speaker": "Stewie", "text": "Because compromised endpoints turn good identities into bad outcomes."},
            {"speaker": "Peter", "text": "What should be checked on devices?"},
            {"speaker": "Stewie", "text": "Compliance, encryption, patch level, EDR state, risk posture, and whether the device is managed at all."},
            {"speaker": "Peter", "text": "What about BYOD?"},
            {"speaker": "Stewie", "text": "Treat it carefully. Allow lower-risk actions, enforce app protection, and block sensitive admin access."},
            {"speaker": "Peter", "text": "So not every device gets equal trust."},
            {"speaker": "Stewie", "text": "Exactly. Trust is conditional, not democratic."},
            {"speaker": "Peter", "text": "Does this belong to endpoint team or identity team?"},
            {"speaker": "Stewie", "text": "Both. Zero Trust loves cross-team coordination almost as much as attackers love silos."},
        ],
        "learning_objectives": [
            "Use device compliance as an access signal in Zero Trust",
            "Differentiate managed, unmanaged, and BYOD access policies",
            "Restrict sensitive workflows based on endpoint risk and management state",
        ],
    },
    {
        "concept_slug": "data-security",
        "title": "Classify, Label, Encrypt, Restrict",
        "slug": "sc100-data-classify-label-encrypt",
        "category": "data-security",
        "difficulty": 5,
        "hook": "If data has no label, your policy is guessing in the dark.",
        "description": "A more specific SC-100 lesson on the data pillar: classification, labeling, encryption, and policy-driven access.",
        "dialogue": [
            {"speaker": "Peter", "text": "Why do architects obsess over labels so much?"},
            {"speaker": "Stewie", "text": "Because unlabeled data is hard to govern and impossible to protect consistently."},
            {"speaker": "Peter", "text": "So classification comes first?"},
            {"speaker": "Stewie", "text": "Classification, then labels, then encryption and access rules that actually use those labels."},
            {"speaker": "Peter", "text": "What does that enable?"},
            {"speaker": "Stewie", "text": "DLP, retention, conditional access, rights management, and audit that understands business value."},
            {"speaker": "Peter", "text": "What if data leaves the app?"},
            {"speaker": "Stewie", "text": "That is exactly why labels and encryption matter. Protection should travel with the data."},
            {"speaker": "Peter", "text": "So data itself becomes policy-aware?"},
            {"speaker": "Stewie", "text": "Now you are speaking architect."},
        ],
        "learning_objectives": [
            "Explain the sequence from classification to label-driven enforcement",
            "Apply encryption and DLP based on data sensitivity",
            "Design protection that persists when data moves across apps and devices",
        ],
    },
    {
        "concept_slug": "app-security-arch",
        "title": "Shadow IT Discovery and Session Controls",
        "slug": "sc100-shadow-it-session-controls",
        "category": "app-security-arch",
        "difficulty": 5,
        "hook": "Your approved apps are not whole environment. They are merely the polite part.",
        "description": "A more specific applications-pillar lesson covering discovery of unsanctioned apps and in-session controls for risky behavior.",
        "dialogue": [
            {"speaker": "Peter", "text": "We already approved the official apps. Problem solved?"},
            {"speaker": "Stewie", "text": "Only if users stopped discovering websites the internet keeps making."},
            {"speaker": "Peter", "text": "So shadow IT is just unauthorized SaaS?"},
            {"speaker": "Stewie", "text": "Unauthorized, unnoticed, and often full of company data."},
            {"speaker": "Peter", "text": "How do we control that without banning the internet?"},
            {"speaker": "Stewie", "text": "Discover usage, rate app risk, sanction what is acceptable, and apply session controls to the rest."},
            {"speaker": "Peter", "text": "Session controls like what?"},
            {"speaker": "Stewie", "text": "Block downloads, prevent copy-paste, require watermarking, or force read-only access in risky contexts."},
            {"speaker": "Peter", "text": "So app governance is live behavior control, not just allow lists."},
            {"speaker": "Stewie", "text": "Exactly. Apps are doors. Session controls decide what happens after entry."},
        ],
        "learning_objectives": [
            "Discover and assess shadow IT usage",
            "Differentiate sanctioned apps from risky unmanaged SaaS",
            "Use in-session controls to reduce data exfiltration and unsafe behavior",
        ],
    },
]
LESSONS = rewrite_lessons_dialogues(LESSONS)
