"""Cybersecurity architecture lessons — grounded in the awesome-list repo
github.com/paulveillard/cybersecurity-architecture.

Covers the repo's core themes mapped to existing CyberMentorTok concepts:
  Security by Design, Cloud Architecture, Serverless, Microservices, IoT,
  Containers/Kubernetes, Databases & Storage, Big Data, Stability, Availability,
  Rate Limiting, Security at Scale, AWS Security.

Same schema as the other sc100_*_lessons files.
"""

from dialogue_rewriter import rewrite_lessons_dialogues


LESSONS = [
    {
        "concept_slug": "app-security-arch",
        "title": "Security by Design: Build It Secure",
        "slug": "gh-security-by-design",
        "description": "Designing security into software from the first line instead of bolting it on after a breach.",
        "hook": "Patching after a breach is archaeology. Security by design is architecture — built in from day one.",
        "problem": "Teams build features first and add security later, so flaws live in the foundation and every patch is a retrofit.",
        "explanation": "Security by design means thinking about cybersecurity at the beginning of a project, so engineers design software to be secure from the outset. The key shift is from reactive security (repairing after a breach) to preventive security (reducing the likelihood of flaws that compromise information security). It covers the whole software architecture: the organization or structure of a system, how it behaves, and how it transforms requirements into implementation through requirements specification, high-level design, and detailed design. Core practices: threat modeling in the design phase, least privilege in every component, secure defaults, defense in depth, and secure coding patterns. Combined with the OWASP security by design principles, it makes security an architectural property rather than an add-on.",
        "real_world_example": "A payments team builds threat modeling into its design review. They find an authorization gap before any code ships, so the fix costs hours instead of an incident and a breach notification.",
        "summary": "Security by design moves protection to the start of the lifecycle: threat model early, use secure defaults, apply least privilege everywhere, and treat security as an architectural property.",
        "curiosity_hook": "The same codebase can be secure by design or riddled with flaws — the difference is decided in the architecture phase, not the audit phase.",
        "dialogue": [
            {"speaker": "Peter", "text": "We can just add security after we build it, right?"},
            {"speaker": "Stewie", "text": "That's archaeology, not architecture. Fixing flaws after a breach is the expensive way."},
            {"speaker": "Peter", "text": "What does security by design actually mean?"},
            {"speaker": "Stewie", "text": "Thinking about security at the beginning, so the software is secure from the outset."},
            {"speaker": "Peter", "text": "So it's about the design phase?"},
            {"speaker": "Stewie", "text": "Yes. Threat modeling, secure defaults, least privilege — all decided before code."},
            {"speaker": "Peter", "text": "Why does the architecture matter?"},
            {"speaker": "Stewie", "text": "Because the structure decides how the system behaves. Flaws in the foundation are everywhere."},
            {"speaker": "Peter", "text": "What's the difference from secure coding?"},
            {"speaker": "Stewie", "text": "Secure coding is how you write. Security by design is how you architect before writing."},
            {"speaker": "Peter", "text": "Where do OWASP principles fit?"},
            {"speaker": "Stewie", "text": "They give the design rules: least privilege, fail secure, defense in depth."},
            {"speaker": "Peter", "text": "So security becomes a property of the design?"},
            {"speaker": "Stewie", "text": "Exactly. Not an add-on. An architectural property."},
            {"speaker": "Peter", "text": "Cheaper in the long run?"},
            {"speaker": "Stewie", "text": "Dramatically. A design fix costs hours. A breach costs everything."},
        ],
        "learning_objectives": [
            "Explain security by design and how it differs from reactive security",
            "Apply threat modeling, secure defaults, and least privilege in design",
            "Treat security as an architectural property, not an add-on",
        ],
        "quiz_questions": [
            {
                "question": "What is the core idea of security by design?",
                "answers": [
                    {"id": "a", "text": "Designing software to be secure from the outset", "correct": True},
                    {"id": "b", "text": "Patching after a breach", "correct": False},
                    {"id": "c", "text": "Adding firewalls later", "correct": False},
                    {"id": "d", "text": "Security testing only", "correct": False},
                ],
            },
            {
                "question": "Which phase does security by design emphasize?",
                "answers": [
                    {"id": "a", "text": "The design and architecture phase", "correct": True},
                    {"id": "b", "text": "The post-mortem phase", "correct": False},
                    {"id": "c", "text": "The decommission phase", "correct": False},
                    {"id": "d", "text": "The marketing phase", "correct": False},
                ],
            },
            {
                "question": "Which is a security by design principle?",
                "answers": [
                    {"id": "a", "text": "Least privilege and fail secure", "correct": True},
                    {"id": "b", "text": "Maximize privileges", "correct": False},
                    {"id": "c", "text": "Open by default", "correct": False},
                    {"id": "d", "text": "Obscurity as the only control", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "Cloud Architecture & Multi-Tenant Isolation",
        "slug": "gh-cloud-architecture-patterns",
        "description": "Cloud design patterns and how multi-tenant SaaS isolates tenants at every layer.",
        "hook": "One customer's data leaking into another's is the cloud's worst nightmare. Tenant isolation is how you prevent it.",
        "problem": "SaaS runs many customers on shared infrastructure, and without deliberate isolation a tenant can reach another tenant's data.",
        "explanation": "Cloud architecture uses proven design patterns for reliability, scalability, and security: retry, circuit breaker, queue-based load leveling, cache-aside, and sidecar. For multi-tenant SaaS, tenant isolation is the critical security concern — the boundaries that keep each customer's data and operations separate. Isolation strategies vary by model: isolated per-tenant infrastructure (strongest, most expensive), pool-per-tier, and shared services with row-level and application-level isolation. Tenant isolation applies at compute (separate clusters or pods), network (VPCs, subnets, network policies), storage (per-tenant buckets or encrypted keys), and data (per-tenant databases or schemas with row-level security). The isolation strategy must be deliberate and tested — shared infrastructure with weak isolation is a compliance and security failure waiting to happen.",
        "real_world_example": "A SaaS HR platform uses a pool-per-tier model: separate database pools per tenant tier with per-tenant encryption keys. A pentest proves one tenant cannot query another's rows, passing the isolation audit.",
        "summary": "Choose tenant isolation deliberately across compute, network, storage, and data. Test it like a boundary, because that's exactly what it is.",
        "curiosity_hook": "Multi-tenancy is why cloud is cheap — but shared infrastructure is also why isolation testing is non-negotiable.",
        "dialogue": [
            {"speaker": "Peter", "text": "Cloud architecture patterns. Is that a real thing?"},
            {"speaker": "Stewie", "text": "Very real. Retry, circuit breaker, cache-aside, queue-based load leveling. Proven building blocks."},
            {"speaker": "Peter", "text": "What's the big security concern for SaaS?"},
            {"speaker": "Stewie", "text": "Tenant isolation. One customer reaching another's data is the nightmare scenario."},
            {"speaker": "Peter", "text": "How do you isolate tenants?"},
            {"speaker": "Stewie", "text": "Per-tenant infrastructure, pool-per-tier, or shared services with row-level security."},
            {"speaker": "Peter", "text": "Where does isolation apply?"},
            {"speaker": "Stewie", "text": "Compute, network, storage, and data. Each layer needs its own boundary."},
            {"speaker": "Peter", "text": "Storage isolation?"},
            {"speaker": "Stewie", "text": "Per-tenant buckets or per-tenant encryption keys. Shared storage needs strict access controls."},
            {"speaker": "Peter", "text": "Data layer?"},
            {"speaker": "Stewie", "text": "Per-tenant databases or schemas, plus row-level security as defense in depth."},
            {"speaker": "Peter", "text": "How do I know isolation actually holds?"},
            {"speaker": "Stewie", "text": "Test it. Pentest cross-tenant access like you'd test any security boundary."},
            {"speaker": "Peter", "text": "So cheap shared infrastructure needs expensive testing?"},
            {"speaker": "Stewie", "text": "The testing is what makes sharing safe. Skip it and sharing becomes a breach."},
        ],
        "learning_objectives": [
            "Identify common cloud architecture patterns and their security role",
            "Design tenant isolation across compute, network, storage, and data",
            "Test multi-tenant boundaries for cross-tenant access",
        ],
        "quiz_questions": [
            {
                "question": "What is the critical security concern for multi-tenant SaaS?",
                "answers": [
                    {"id": "a", "text": "Tenant isolation", "correct": True},
                    {"id": "b", "text": "Color scheme", "correct": False},
                    {"id": "c", "text": "Logo placement", "correct": False},
                    {"id": "d", "text": "Marketing copy", "correct": False},
                ],
            },
            {
                "question": "Which is a tenant isolation model?",
                "answers": [
                    {"id": "a", "text": "Pool-per-tier", "correct": True},
                    {"id": "b", "text": "Single shared admin", "correct": False},
                    {"id": "c", "text": "No isolation", "correct": False},
                    {"id": "d", "text": "Public buckets", "correct": False},
                ],
            },
            {
                "question": "How do you verify tenant isolation holds?",
                "answers": [
                    {"id": "a", "text": "Test cross-tenant access like any security boundary", "correct": True},
                    {"id": "b", "text": "Trust the cloud provider blindly", "correct": False},
                    {"id": "c", "text": "Skip testing to save cost", "correct": False},
                    {"id": "d", "text": "Assume it works", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "Serverless Architecture & Security",
        "slug": "gh-serverless-security",
        "description": "Event-driven serverless patterns and the security model that comes with no servers to patch.",
        "hook": "No servers to patch, but plenty of functions to abuse. Serverless moves the attack surface, not the risk.",
        "problem": "Teams adopt serverless for scale but keep thinking in server terms, missing function-level permissions, event injection, and dependency risks.",
        "explanation": "Serverless architecture runs code on demand with no server management — functions execute in response to events. Common patterns include function as a service, event-driven workflows, and serverless microservices. The security model differs: you no longer manage OS patches, but you own function code, dependencies, permissions, and event inputs. Key risks: over-permissioned functions (a function that can touch everything), event injection (untrusted payloads from queues, storage, or HTTP), vulnerable dependencies in the function bundle, and lack of observability. Best practices: least-privilege execution roles per function, validate and sanitize every event input, scan dependencies, keep functions small and single-purpose, enable logging and tracing, and protect secrets with a managed secret store instead of environment literals.",
        "real_world_example": "A serverless image-resize function had an execution role that could delete any bucket. An attacker triggered it with a crafted event, and the over-broad role turned a toy function into a data-loss tool. Scoped to one bucket, the blast radius vanished.",
        "summary": "Serverless removes server patching but adds function-level duties: least-privilege roles, event validation, dependency scanning, and observability.",
        "curiosity_hook": "A serverless function's IAM role is its identity — over-scope it and every invocation is a potential privilege escalation.",
        "dialogue": [
            {"speaker": "Peter", "text": "Serverless means no servers to secure, right?"},
            {"speaker": "Stewie", "text": "No servers to patch. But functions, events, and roles to secure. The risk moves, not disappears."},
            {"speaker": "Peter", "text": "What's the big risk?"},
            {"speaker": "Stewie", "text": "Over-permissioned functions. A resize function that can delete any bucket."},
            {"speaker": "Peter", "text": "Event inputs?"},
            {"speaker": "Stewie", "text": "Functions eat events from queues and storage. Treat every event as hostile and validate it."},
            {"speaker": "Peter", "text": "Dependencies?"},
            {"speaker": "Stewie", "text": "They're bundled into every function. Scan them or ship known vulnerabilities."},
            {"speaker": "Peter", "text": "Execution roles?"},
            {"speaker": "Stewie", "text": "Least privilege per function. A function only touches what it needs, nothing else."},
            {"speaker": "Peter", "text": "Secrets in serverless?"},
            {"speaker": "Stewie", "text": "Never in environment literals. Use a managed secret store."},
            {"speaker": "Peter", "text": "Observability?"},
            {"speaker": "Stewie", "text": "Enable logging and tracing on every function. Invisible functions can't be investigated."},
            {"speaker": "Peter", "text": "Keep functions small?"},
            {"speaker": "Stewie", "text": "Single-purpose functions with narrow scope. That's the whole security model."},
        ],
        "learning_objectives": [
            "Explain serverless patterns and their shifted security model",
            "Scope execution roles with least privilege per function",
            "Validate events, scan dependencies, and enable observability",
        ],
        "quiz_questions": [
            {
                "question": "What replaces server patching as the security duty in serverless?",
                "answers": [
                    {"id": "a", "text": "Function roles, event validation, and dependencies", "correct": True},
                    {"id": "b", "text": "OS kernel updates", "correct": False},
                    {"id": "c", "text": "Physical access control", "correct": False},
                    {"id": "d", "text": "CPU microcode patches", "correct": False},
                ],
            },
            {
                "question": "How should a serverless function's execution role be scoped?",
                "answers": [
                    {"id": "a", "text": "Least privilege, only what the function needs", "correct": True},
                    {"id": "b", "text": "Administrator on everything", "correct": False},
                    {"id": "c", "text": "Full access to all buckets", "correct": False},
                    {"id": "d", "text": "No permissions at all", "correct": False},
                ],
            },
            {
                "question": "How should event inputs be handled in serverless?",
                "answers": [
                    {"id": "a", "text": "Treat them as hostile and validate", "correct": True},
                    {"id": "b", "text": "Trust them implicitly", "correct": False},
                    {"id": "c", "text": "Execute them directly", "correct": False},
                    {"id": "d", "text": "Store them raw", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "app-security-arch",
        "title": "Microservices & Distributed Systems Security",
        "slug": "gh-microservices-security",
        "description": "Securing many small services: service identity, API gateways, and the distributed security model.",
        "hook": "A monolith hides your attack surface. Microservices expose it — on purpose. Now you must secure every seam.",
        "problem": "Breaking an app into microservices multiplies the entry points, and teams often secure the services but forget the network, identity, and data seams between them.",
        "explanation": "Microservices decompose an application into small, independently deployable services communicating over a network. Security shifts from a single perimeter to many boundaries. Core controls: service identity and mutual TLS (mTLS) so services authenticate each other; an API gateway as the single entry point enforcing auth, rate limiting, and input validation; service meshes for policy enforcement, traffic encryption, and observability between services; decentralized authorization so every service enforces its own access rules instead of trusting the gateway; and circuit breakers to stop a failing dependency from cascading. Distributed tracing correlates requests across services for investigation. Secure the seams: encrypt inter-service traffic, validate payloads at each boundary, and avoid trusting internal networks just because they are internal — an attacker who compromises one service will try to move to the next.",
        "real_world_example": "A retailer splits checkout into services. A service mesh enforces mTLS between all of them, the API gateway rate-limits and validates input, and when a discount service is compromised, its least-privilege identity cannot reach the payment service — blast radius contained.",
        "summary": "Secure microservices at the seams: mTLS service identity, an API gateway, decentralized authorization, service mesh policy, and circuit breakers to contain failure.",
        "curiosity_hook": "In a microservice world, every inter-service call is a trust decision — that's why mTLS and decentralized auth matter more than one big firewall.",
        "dialogue": [
            {"speaker": "Peter", "text": "Microservices sound like a mess of moving parts."},
            {"speaker": "Stewie", "text": "They are. And each moving part is a security seam you must secure."},
            {"speaker": "Peter", "text": "How do services trust each other?"},
            {"speaker": "Stewie", "text": "Service identity with mutual TLS. Every service proves who it is to every other."},
            {"speaker": "Peter", "text": "What guards the front door?"},
            {"speaker": "Stewie", "text": "An API gateway. Auth, rate limiting, input validation, all in one place."},
            {"speaker": "Peter", "text": "Do services trust the gateway?"},
            {"speaker": "Stewie", "text": "No. Decentralized authorization — every service enforces its own access rules."},
            {"speaker": "Peter", "text": "What's a service mesh?"},
            {"speaker": "Stewie", "text": "A layer that enforces policy and encrypts traffic between services automatically."},
            {"speaker": "Peter", "text": "How do I stop a failure from spreading?"},
            {"speaker": "Stewie", "text": "Circuit breakers. A failing dependency stops being called before it takes everything down."},
            {"speaker": "Peter", "text": "Investigations across services?"},
            {"speaker": "Stewie", "text": "Distributed tracing correlates one request across every service it touches."},
            {"speaker": "Peter", "text": "Should I trust the internal network?"},
            {"speaker": "Stewie", "text": "Never. One compromised service will try to hop to the next. Secure every seam."},
        ],
        "learning_objectives": [
            "Design service identity with mTLS between microservices",
            "Use API gateways and decentralized authorization correctly",
            "Apply service mesh policy and circuit breakers for containment",
        ],
        "quiz_questions": [
            {
                "question": "How do microservices authenticate each other?",
                "answers": [
                    {"id": "a", "text": "Mutual TLS with service identity", "correct": True},
                    {"id": "b", "text": "Shared plaintext passwords", "correct": False},
                    {"id": "c", "text": "Trusting the internal network", "correct": False},
                    {"id": "d", "text": "No authentication", "correct": False},
                ],
            },
            {
                "question": "Why is decentralized authorization needed in microservices?",
                "answers": [
                    {"id": "a", "text": "Each service must enforce its own access rules", "correct": True},
                    {"id": "b", "text": "To centralize all checks in the gateway", "correct": False},
                    {"id": "c", "text": "To remove all authorization", "correct": False},
                    {"id": "d", "text": "To trust clients", "correct": False},
                ],
            },
            {
                "question": "What stops a failing dependency from taking down a whole system?",
                "answers": [
                    {"id": "a", "text": "Circuit breakers", "correct": True},
                    {"id": "b", "text": "More services", "correct": False},
                    {"id": "c", "text": "Longer timeouts", "correct": False},
                    {"id": "d", "text": "Fewer logs", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "app-security-arch",
        "title": "IoT Architecture & Security Patterns",
        "slug": "gh-iot-security",
        "description": "Securing billions of constrained devices: identity, communication patterns, and the gateway model.",
        "hook": "Your toaster now has an IP address and a password of '1234'. IoT is a security problem at planet scale.",
        "problem": "IoT devices are constrained, numerous, and often unpatched — and each one is a potential entry point into the network and the physical world.",
        "explanation": "IoT architectures connect constrained devices through gateways and cloud platforms. Security patterns include device identity at manufacture (unique certificates or keys), secure boot and signed firmware to prevent tampering, encrypted communication (TLS or DTLS over MQTT or CoAP), and gateway-mediated access so devices never expose services directly. Communication patterns vary: device-to-device, device-to-gateway, and device-to-cloud, each with different trust boundaries. Key risks: default credentials, unpatched firmware, insecure protocols, and device-to-device trust that lets a compromised node attack peers. Mitigations: enforce credential change on first boot, sign and verify firmware updates, segment IoT networks from corporate IT, use per-device keys so one compromise cannot clone the fleet, and monitor device telemetry for anomalies.",
        "real_world_example": "A building's HVAC controllers use default passwords. An attacker scans the internet, logs in, and pivots into the corporate network through an unsegmented IoT subnet. Segmentation and credential enforcement would have stopped both steps.",
        "summary": "Secure IoT with device identity, secure boot and signed updates, encrypted protocols, gateway mediation, network segmentation, and per-device keys.",
        "curiosity_hook": "Per-device keys mean a hacked sensor can't be cloned — the whole fleet stays safe even when one node falls.",
        "dialogue": [
            {"speaker": "Peter", "text": "IoT devices are everywhere now. What's the risk?"},
            {"speaker": "Stewie", "text": "Billions of constrained, unpatched devices with default credentials. Each one a door."},
            {"speaker": "Peter", "text": "How do we give devices an identity?"},
            {"speaker": "Stewie", "text": "Unique certificates or keys at manufacture. Per-device keys, not one shared secret."},
            {"speaker": "Peter", "text": "Firmware tampering?"},
            {"speaker": "Stewie", "text": "Secure boot and signed firmware. Only verified code runs and updates."},
            {"speaker": "Peter", "text": "Device communication?"},
            {"speaker": "Stewie", "text": "Encrypt it. TLS or DTLS over MQTT or CoAP. Never plaintext."},
            {"speaker": "Peter", "text": "Should devices be directly exposed?"},
            {"speaker": "Stewie", "text": "No. Route through gateways so devices never publish services to the internet."},
            {"speaker": "Peter", "text": "Default passwords?"},
            {"speaker": "Stewie", "text": "Force a change on first boot. Default credentials are how most IoT gets owned."},
            {"speaker": "Peter", "text": "What about the network?"},
            {"speaker": "Stewie", "text": "Segment IoT from corporate IT. A hacked sensor should not reach the file server."},
            {"speaker": "Peter", "text": "Monitoring?"},
            {"speaker": "Stewie", "text": "Watch device telemetry for anomalies. Odd traffic from a sensor is a red flag."},
        ],
        "learning_objectives": [
            "Design device identity and secure boot for IoT fleets",
            "Apply gateway mediation and encrypted IoT communication patterns",
            "Segment IoT networks and enforce per-device keys",
        ],
        "quiz_questions": [
            {
                "question": "How should IoT devices be given identity?",
                "answers": [
                    {"id": "a", "text": "Unique certificates or keys per device", "correct": True},
                    {"id": "b", "text": "One shared fleet password", "correct": False},
                    {"id": "c", "text": "Default credentials", "correct": False},
                    {"id": "d", "text": "No identity", "correct": False},
                ],
            },
            {
                "question": "Why route IoT devices through gateways?",
                "answers": [
                    {"id": "a", "text": "So devices never expose services directly", "correct": True},
                    {"id": "b", "text": "To increase latency", "correct": False},
                    {"id": "c", "text": "To remove encryption", "correct": False},
                    {"id": "d", "text": "To share one password", "correct": False},
                ],
            },
            {
                "question": "What is a key defense against compromised IoT nodes?",
                "answers": [
                    {"id": "a", "text": "Network segmentation from corporate IT", "correct": True},
                    {"id": "b", "text": "Connecting everything to one flat network", "correct": False},
                    {"id": "c", "text": "Ignoring device telemetry", "correct": False},
                    {"id": "d", "text": "Disabling firmware updates", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "container-security",
        "title": "Kubernetes & Container Security Patterns",
        "slug": "gh-container-kubernetes-security",
        "description": "Securing container images, Kubernetes clusters, and the software supply chain they run on.",
        "hook": "Containers share the kernel with their neighbors. One bad image and a whole cluster is a soft target.",
        "problem": "Teams deploy containers without hardening images, scanning for vulnerabilities, or isolating workloads, turning shared clusters into a wide blast radius.",
        "explanation": "Containers are not virtual machines — they share the host kernel, so isolation and image hygiene matter more. Secure the supply chain: scan images for vulnerabilities before deployment, sign and verify images, and use minimal base images. Harden the runtime: run containers as non-root, drop unnecessary capabilities, use read-only root filesystems, and enforce resource limits. Secure the cluster: role-based access control with least privilege, network policies to segment pods, secrets stored in a managed secret store rather than environment literals, and pod security standards to enforce safe defaults. Use Kubernetes native patterns: sidecars for logging and security agents, service mesh for encrypted traffic, and network policies as microsegmentation between workloads.",
        "real_world_example": "A pipeline pulls a base image with a known critical vulnerability. Image scanning in CI rejects it before deployment, and cluster network policies keep a compromised pod from reaching the database — the supply chain and blast radius are both controlled.",
        "summary": "Harden containers from image to runtime: scan and sign images, run non-root with minimal capabilities, enforce RBAC and network policies, and use managed secrets.",
        "curiosity_hook": "A container that runs as root with all capabilities is basically a VM with a paper-thin wall — isolation comes from how you configure it, not from the word 'container'.",
        "dialogue": [
            {"speaker": "Peter", "text": "Containers are isolated, so they're safe, right?"},
            {"speaker": "Stewie", "text": "They share the host kernel. Isolation is earned through configuration, not magic."},
            {"speaker": "Peter", "text": "Start with images?"},
            {"speaker": "Stewie", "text": "Scan them for vulnerabilities, sign and verify them, use minimal base images."},
            {"speaker": "Peter", "text": "Runtime hardening?"},
            {"speaker": "Stewie", "text": "Run non-root, drop unnecessary capabilities, read-only filesystems, resource limits."},
            {"speaker": "Peter", "text": "Cluster access?"},
            {"speaker": "Stewie", "text": "RBAC with least privilege. Nobody is cluster-admin by default."},
            {"speaker": "Peter", "text": "Secrets?"},
            {"speaker": "Stewie", "text": "Managed secret store. Never environment literals in the manifest."},
            {"speaker": "Peter", "text": "Network between pods?"},
            {"speaker": "Stewie", "text": "Network policies. Microsegment workloads so one pod can't roam the cluster."},
            {"speaker": "Peter", "text": "Pod security?"},
            {"speaker": "Stewie", "text": "Pod security standards enforce safe defaults cluster-wide."},
            {"speaker": "Peter", "text": "Service mesh?"},
            {"speaker": "Stewie", "text": "Encrypted traffic and policy between services. Defense in depth at the seam."},
        ],
        "learning_objectives": [
            "Secure the container image supply chain with scanning and signing",
            "Harden container runtime with non-root and minimal capabilities",
            "Enforce cluster RBAC, network policies, and managed secrets",
        ],
        "quiz_questions": [
            {
                "question": "Why do containers need deliberate isolation?",
                "answers": [
                    {"id": "a", "text": "They share the host kernel", "correct": True},
                    {"id": "b", "text": "They are virtual machines", "correct": False},
                    {"id": "c", "text": "They have no attack surface", "correct": False},
                    {"id": "d", "text": "They cannot be attacked", "correct": False},
                ],
            },
            {
                "question": "How should containers run to reduce privilege risk?",
                "answers": [
                    {"id": "a", "text": "Non-root with dropped capabilities", "correct": True},
                    {"id": "b", "text": "As root with all capabilities", "correct": False},
                    {"id": "c", "text": "With privileged mode", "correct": False},
                    {"id": "d", "text": "With host PID access", "correct": False},
                ],
            },
            {
                "question": "What segments pod-to-pod traffic in a cluster?",
                "answers": [
                    {"id": "a", "text": "Network policies", "correct": True},
                    {"id": "b", "text": "No controls", "correct": False},
                    {"id": "c", "text": "A single flat subnet", "correct": False},
                    {"id": "d", "text": "Public exposure", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "data-security",
        "title": "Database & Storage Security Patterns",
        "slug": "gh-database-storage-security",
        "description": "Securing SQL, NoSQL, and object storage with tenancy patterns, encryption, and access boundaries.",
        "hook": "Every database type has a different attack surface. SQL, NoSQL, object storage — each needs its own pattern.",
        "problem": "Teams apply one security model to every datastore, missing the specific risks of SQL injection, NoSQL injection, and misconfigured object storage.",
        "explanation": "Datastore security patterns vary by type. SQL: parameterized queries against injection, least-privilege database accounts, column-level and row-level security, transparent data encryption, and multi-tenant database tenancy patterns (database-per-tenant, schema-per-tenant, or shared table with row-level security). NoSQL: validate query operators (NoSQL injection), use per-application credentials, encrypt fields, and follow resilience patterns for availability. Object storage: the classic leak vector — disable public access by default, use bucket policies with least privilege, enable server-side encryption, versioning for recovery, and access logging to see who reads what. Across all: encryption at rest and in transit, separation of environments, backups with immutable retention, and least-privilege access to the storage management plane.",
        "real_world_example": "An analytics team leaves an object storage bucket public for easy sharing. A scanner finds it and dumps customer records. Bucket policies, encryption, and access logs would have made the same share safe and auditable.",
        "summary": "Match the pattern to the datastore: parameterize SQL, validate NoSQL operators, lock down object storage, and layer encryption, least privilege, and immutable backups everywhere.",
        "curiosity_hook": "Object storage is the single most common source of cloud data leaks — because public-by-default is one toggle away from a breach.",
        "dialogue": [
            {"speaker": "Peter", "text": "One security plan for all databases?"},
            {"speaker": "Stewie", "text": "No. SQL, NoSQL, and object storage each have their own attack surface."},
            {"speaker": "Peter", "text": "SQL first."},
            {"speaker": "Stewie", "text": "Parameterized queries, least-privilege accounts, column and row-level security, encryption."},
            {"speaker": "Peter", "text": "Multi-tenant databases?"},
            {"speaker": "Stewie", "text": "Database-per-tenant, schema-per-tenant, or shared table with row-level security."},
            {"speaker": "Peter", "text": "NoSQL?"},
            {"speaker": "Stewie", "text": "Validate query operators — NoSQL injection is real. Per-application credentials, field encryption."},
            {"speaker": "Peter", "text": "Object storage?"},
            {"speaker": "Stewie", "text": "The classic leak. Public access off by default, least-privilege bucket policies, encryption, logging."},
            {"speaker": "Peter", "text": "What about backups?"},
            {"speaker": "Stewie", "text": "Immutable retention. A backup you can't delete survives ransomware and mistakes."},
            {"speaker": "Peter", "text": "Encryption everywhere?"},
            {"speaker": "Stewie", "text": "At rest and in transit, on every datastore, without exception."},
            {"speaker": "Peter", "text": "So the storage plane is a crown jewel?"},
            {"speaker": "Stewie", "text": "Treat the management plane like one. Least privilege there protects all the data below."},
        ],
        "learning_objectives": [
            "Apply SQL, NoSQL, and object storage security patterns",
            "Design multi-tenant database isolation strategies",
            "Layer encryption, least privilege, logging, and immutable backups",
        ],
        "quiz_questions": [
            {
                "question": "What is the most common source of cloud data leaks?",
                "answers": [
                    {"id": "a", "text": "Misconfigured object storage", "correct": True},
                    {"id": "b", "text": "Parameterized queries", "correct": False},
                    {"id": "c", "text": "Row-level security", "correct": False},
                    {"id": "d", "text": "Immutable backups", "correct": False},
                ],
            },
            {
                "question": "How do you defend against NoSQL injection?",
                "answers": [
                    {"id": "a", "text": "Validate query operators", "correct": True},
                    {"id": "b", "text": "Ignore user input", "correct": False},
                    {"id": "c", "text": "Use public buckets", "correct": False},
                    {"id": "d", "text": "Disable encryption", "correct": False},
                ],
            },
            {
                "question": "Which multi-tenant database model uses shared tables?",
                "answers": [
                    {"id": "a", "text": "Shared table with row-level security", "correct": True},
                    {"id": "b", "text": "Database-per-tenant", "correct": False},
                    {"id": "c", "text": "No isolation", "correct": False},
                    {"id": "d", "text": "Public schema", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "data-security",
        "title": "Big Data & Analytics Platform Security",
        "slug": "gh-bigdata-analytics-security",
        "description": "Securing data pipelines, warehouses, and ML platforms — from ingestion to insight.",
        "hook": "Your data platform holds more than your databases. Pipelines, warehouses, and ML models are all targets.",
        "problem": "Big data platforms grow organically with weak access control, and sensitive data flows through pipelines no one monitors.",
        "explanation": "Big data architectures collect, store, and analyze massive datasets through pipelines, warehouses, and machine learning platforms. Security must cover the whole path. Ingestion: validate and encrypt data in transit, authenticate producers, and scan for sensitive data entering the pipeline. Storage: encrypt data lakes and warehouses at rest, apply fine-grained access control and column-level masking, and classify data as it lands. Processing: isolate compute from data, run jobs with least privilege, and audit who runs what. ML platforms: protect training data, control model access, and monitor for data exfiltration through inference. Governance: data lineage to know where data came from, metadata catalogs for discovery with access control, and privacy-preserving techniques so analytics don't leak personal data. The platform is a crown-jewel target — its analytics users often have broad read access that spans the entire organization.",
        "real_world_example": "An analyst queries a warehouse with broad access and exports a full customer table. Column-level masking on sensitive fields and per-role row limits turn the same query into a safe, auditable result.",
        "summary": "Secure the whole analytics path: encrypt and validate ingestion, protect warehouses with fine-grained access and masking, least-privilege compute, and govern with lineage and metadata catalogs.",
        "curiosity_hook": "Data lineage is the paper trail of your platform — it answers where a number came from and who touched it, which is exactly what audits demand.",
        "dialogue": [
            {"speaker": "Peter", "text": "Big data platform. Just a bigger database, right?"},
            {"speaker": "Stewie", "text": "A bigger attack surface. Pipelines, warehouses, and ML models are all targets."},
            {"speaker": "Peter", "text": "Where does it start?"},
            {"speaker": "Stewie", "text": "Ingestion. Validate and encrypt data in transit, authenticate producers, scan for sensitive data."},
            {"speaker": "Peter", "text": "Data at rest?"},
            {"speaker": "Stewie", "text": "Encrypt lakes and warehouses. Fine-grained access and column-level masking."},
            {"speaker": "Peter", "text": "Analytics users?"},
            {"speaker": "Stewie", "text": "Their broad read access is the real risk. Mask columns and limit rows per role."},
            {"speaker": "Peter", "text": "Processing jobs?"},
            {"speaker": "Stewie", "text": "Run with least privilege and audit who runs what. Isolate compute from data."},
            {"speaker": "Peter", "text": "ML platforms?"},
            {"speaker": "Stewie", "text": "Protect training data, control model access, watch for exfiltration through inference."},
            {"speaker": "Peter", "text": "How do I track data?"},
            {"speaker": "Stewie", "text": "Lineage and metadata catalogs. Know where data came from and who touched it."},
            {"speaker": "Peter", "text": "Privacy?"},
            {"speaker": "Stewie", "text": "Privacy-preserving analytics so insights don't leak personal data."},
        ],
        "learning_objectives": [
            "Secure the data pipeline from ingestion to analytics",
            "Apply fine-grained access, masking, and least-privilege compute",
            "Govern data with lineage, catalogs, and privacy-preserving techniques",
        ],
        "quiz_questions": [
            {
                "question": "What is the real risk from analytics users?",
                "answers": [
                    {"id": "a", "text": "Broad read access across the whole organization", "correct": True},
                    {"id": "b", "text": "Too little access", "correct": False},
                    {"id": "c", "text": "No compute resources", "correct": False},
                    {"id": "d", "text": "Slow queries", "correct": False},
                ],
            },
            {
                "question": "What protects sensitive columns from over-broad analytics?",
                "answers": [
                    {"id": "a", "text": "Column-level masking and per-role limits", "correct": True},
                    {"id": "b", "text": "Public buckets", "correct": False},
                    {"id": "c", "text": "No access control", "correct": False},
                    {"id": "d", "text": "Disabling encryption", "correct": False},
                ],
            },
            {
                "question": "What provides the paper trail of a data platform?",
                "answers": [
                    {"id": "a", "text": "Data lineage and metadata catalogs", "correct": True},
                    {"id": "b", "text": "More storage", "correct": False},
                    {"id": "c", "text": "Faster CPUs", "correct": False},
                    {"id": "d", "text": "Bigger screens", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Resilience Patterns: Circuit Breakers & Bulkheads",
        "slug": "gh-resilience-patterns",
        "description": "Stability patterns that keep a single failure from becoming a full outage.",
        "hook": "One slow service can stall everything — unless you build bulkheads and circuit breakers to contain the damage.",
        "problem": "In distributed systems a single failing or slow dependency can cascade into a full outage, and retries make it worse.",
        "explanation": "Stability patterns protect systems from cascading failure. The circuit breaker wraps a dependency: when failures exceed a threshold, it trips open and calls fail fast instead of hanging, then half-opens to test recovery. Timeouts bound how long a call may take so a slow dependency cannot consume resources indefinitely. Retries with backoff handle transient failures but must be capped so they don't amplify load during an outage. Bulkheads partition resources so one failing component cannot exhaust the pool — separate thread pools or connection pools per dependency. Throttling and rate limiting shed excess load and maintain a steady pace. Together these patterns contain a failure to its origin, preserve availability for the rest of the system, and let the platform recover gracefully instead of falling over.",
        "real_world_example": "A recommendation service calls a third-party API that starts timing out. The circuit breaker trips, calls fail fast, bulkheads keep other services on their own pools, and the app keeps working — degraded, but alive — until the API recovers.",
        "summary": "Use circuit breakers, timeouts, capped retries, and bulkheads to contain failure. Stability patterns turn a potential outage into a contained, recoverable incident.",
        "curiosity_hook": "Bulkheads are named after ship compartments — when one floods, the rest keep sailing. Distributed systems borrowed the idea wholesale.",
        "dialogue": [
            {"speaker": "Peter", "text": "One slow service is annoying, not fatal, right?"},
            {"speaker": "Stewie", "text": "It is fatal if it cascades. Stability patterns stop the spread."},
            {"speaker": "Peter", "text": "What's a circuit breaker?"},
            {"speaker": "Stewie", "text": "When a dependency fails enough, it trips open and calls fail fast instead of hanging."},
            {"speaker": "Peter", "text": "Then what?"},
            {"speaker": "Stewie", "text": "It half-opens to test recovery. Succeed and it closes again."},
            {"speaker": "Peter", "text": "Timeouts?"},
            {"speaker": "Stewie", "text": "Bound how long a call waits. No infinite hangs."},
            {"speaker": "Peter", "text": "Retries?"},
            {"speaker": "Stewie", "text": "Fine with backoff, but cap them. Retry storms make outages worse."},
            {"speaker": "Peter", "text": "Bulkheads?"},
            {"speaker": "Stewie", "text": "Separate resource pools per dependency. One exhausted pool can't starve the rest."},
            {"speaker": "Peter", "text": "What about load?"},
            {"speaker": "Stewie", "text": "Throttling and rate limiting shed excess and keep a steady pace."},
            {"speaker": "Peter", "text": "So failures stay contained?"},
            {"speaker": "Stewie", "text": "Exactly. Degraded but alive beats fully down."},
        ],
        "learning_objectives": [
            "Explain circuit breaker, timeout, and retry semantics",
            "Use bulkheads to isolate resource pools per dependency",
            "Apply throttling to shed load and preserve availability",
        ],
        "quiz_questions": [
            {
                "question": "When does a circuit breaker trip open?",
                "answers": [
                    {"id": "a", "text": "When dependency failures exceed a threshold", "correct": True},
                    {"id": "b", "text": "When the system is idle", "correct": False},
                    {"id": "c", "text": "On every successful call", "correct": False},
                    {"id": "d", "text": "Never", "correct": False},
                ],
            },
            {
                "question": "What do bulkheads isolate?",
                "answers": [
                    {"id": "a", "text": "Resource pools per dependency", "correct": True},
                    {"id": "b", "text": "All resources shared", "correct": False},
                    {"id": "c", "text": "Nothing", "correct": False},
                    {"id": "d", "text": "The public API", "correct": False},
                ],
            },
            {
                "question": "Why cap retries?",
                "answers": [
                    {"id": "a", "text": "Retry storms amplify load during outages", "correct": True},
                    {"id": "b", "text": "To save code lines", "correct": False},
                    {"id": "c", "text": "Retries are always harmful", "correct": False},
                    {"id": "d", "text": "To reduce logging", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Availability: Load Balancing & Autoscaling",
        "slug": "gh-availability-load-balancing",
        "description": "Load balancing, failover, and autoscaling patterns that keep services up under traffic and failure.",
        "hook": "Load balancers are the traffic cops of availability — and autoscaling is the only way to survive a surge without paying for idle servers.",
        "problem": "Services either run on too few servers (die under load) or too many (waste money), and a single point of failure takes the app down.",
        "explanation": "Availability patterns keep services reachable under load and failure. Load balancing distributes traffic across healthy instances at L4 or L7, health-checking backends and routing around failures. Failover ensures redundancy: when one node, zone, or region fails, traffic shifts to a standby without downtime. Autoscaling adds or removes capacity based on demand — reactive (CPU, queue depth) or predictive (forecast) — so the system matches load. Availability zones and regions provide failure isolation; multi-region deployments give disaster recovery. Design for failure: accept partial failures, minimize service loss, and degrade gracefully. Monitoring and alerting on service-level objectives keep availability measurable. Together these patterns turn a single instance into a resilient, elastic service.",
        "real_world_example": "A flash sale drives traffic to 50x normal. Predictive autoscaling spins up instances before the surge, the load balancer spreads traffic across them, and when a zone fails mid-sale, failover shifts traffic to the healthy zone — no outage, no overspend.",
        "summary": "Combine load balancing, health checks, failover, and autoscaling to match capacity to demand and survive failure — design for partial failure and measure with SLOs.",
        "curiosity_hook": "A load balancer with a health check is doing security work too — it routes around dead and failing instances automatically.",
        "dialogue": [
            {"speaker": "Peter", "text": "How do big services stay up under a million users?"},
            {"speaker": "Stewie", "text": "Load balancing, failover, and autoscaling. The holy trinity of availability."},
            {"speaker": "Peter", "text": "Load balancer?"},
            {"speaker": "Stewie", "text": "Spreads traffic across healthy instances and routes around failures."},
            {"speaker": "Peter", "text": "Failover?"},
            {"speaker": "Stewie", "text": "Redundancy. When a node, zone, or region fails, traffic shifts to a standby."},
            {"speaker": "Peter", "text": "Autoscaling?"},
            {"speaker": "Stewie", "text": "Add or remove capacity with demand. Reactive or predictive. Match load exactly."},
            {"speaker": "Peter", "text": "Why zones and regions?"},
            {"speaker": "Stewie", "text": "Failure isolation. One zone dying shouldn't kill the app. Regions give disaster recovery."},
            {"speaker": "Peter", "text": "Design philosophy?"},
            {"speaker": "Stewie", "text": "Accept partial failures. Minimize service loss. Degrade gracefully."},
            {"speaker": "Peter", "text": "How do I measure it?"},
            {"speaker": "Stewie", "text": "Service-level objectives. Availability is only real if you measure it."},
            {"speaker": "Peter", "text": "So one instance is never the answer?"},
            {"speaker": "Stewie", "text": "One instance is a single point of failure. Availability is a design, not a setting."},
        ],
        "learning_objectives": [
            "Design load balancing and health checks across instances",
            "Apply failover and multi-zone or multi-region redundancy",
            "Match capacity to demand with reactive and predictive autoscaling",
        ],
        "quiz_questions": [
            {
                "question": "What does a load balancer do on a failing backend?",
                "answers": [
                    {"id": "a", "text": "Routes traffic around it via health checks", "correct": True},
                    {"id": "b", "text": "Sends all traffic to it", "correct": False},
                    {"id": "c", "text": "Deletes it", "correct": False},
                    {"id": "d", "text": "Ignores it", "correct": False},
                ],
            },
            {
                "question": "What provides failure isolation in the cloud?",
                "answers": [
                    {"id": "a", "text": "Availability zones and regions", "correct": True},
                    {"id": "b", "text": "One large server", "correct": False},
                    {"id": "c", "text": "A single datacenter", "correct": False},
                    {"id": "d", "text": "No redundancy", "correct": False},
                ],
            },
            {
                "question": "What does predictive autoscaling use?",
                "answers": [
                    {"id": "a", "text": "Forecasts of demand", "correct": True},
                    {"id": "b", "text": "Random decisions", "correct": False},
                    {"id": "c", "text": "Manual restarts", "correct": False},
                    {"id": "d", "text": "Coin flips", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Rate Limiting & Throttling at Scale",
        "slug": "gh-rate-limiting",
        "description": "Why rate limiting is both a defense and an availability pattern, and how to design it in distributed systems.",
        "hook": "Rate limiting is the bouncer at the club — it keeps one rowdy guest from ruining the night for everyone.",
        "problem": "Without rate limits, a single abusive client, a bug, or an attacker can exhaust capacity and take the service down for everyone.",
        "explanation": "Rate limiting controls how many requests a client can make in a window, protecting capacity and enforcing fairness. It serves three roles: defense (blocking credential stuffing, scraping, DDoS), availability (preventing a burst from overloading the system), and cost control (stopping runaway consumption). Common algorithms: token bucket, fixed window, sliding window, and leaky bucket, each trading simplicity against burst accuracy. In distributed systems, rate limits need shared state — a centralized store like Redis — so limits hold across many instances. Return proper responses like 429 Too Many Requests with Retry-After so well-behaved clients back off. Throttling is the sibling pattern: it sheds load by delaying or dropping excess work to maintain a steady pace. Design limits by identity, IP, or key, and tune them so legitimate spikes are not blocked.",
        "real_world_example": "A login endpoint has no rate limit. An attacker runs credential stuffing at scale until it takes the auth service down. A token bucket per account with 429 responses stops the attack and keeps legitimate users logging in.",
        "summary": "Rate limit by identity with shared state across instances, use window algorithms deliberately, return 429 with Retry-After, and throttle to shed load and keep a steady pace.",
        "curiosity_hook": "HTTP status 429 exists purely so services can say 'slow down' politely — and well-behaved clients actually listen.",
        "dialogue": [
            {"speaker": "Peter", "text": "Rate limiting. Sounds like a speed bump."},
            {"speaker": "Stewie", "text": "It's a bouncer, a firebreak, and a cost control all in one."},
            {"speaker": "Peter", "text": "What does it stop?"},
            {"speaker": "Stewie", "text": "Credential stuffing, scraping, DDoS — and one buggy client eating all capacity."},
            {"speaker": "Peter", "text": "Algorithms?"},
            {"speaker": "Stewie", "text": "Token bucket, fixed window, sliding window, leaky bucket. Each trades simplicity for accuracy."},
            {"speaker": "Peter", "text": "Distributed systems?"},
            {"speaker": "Stewie", "text": "Limits need shared state, like Redis. One instance alone can't enforce a global limit."},
            {"speaker": "Peter", "text": "What should the client see?"},
            {"speaker": "Stewie", "text": "429 Too Many Requests with Retry-After. Well-behaved clients back off politely."},
            {"speaker": "Peter", "text": "Throttling vs rate limiting?"},
            {"speaker": "Stewie", "text": "Throttling sheds load by delaying or dropping work to keep a steady pace."},
            {"speaker": "Peter", "text": "Who do you limit?"},
            {"speaker": "Stewie", "text": "By identity, IP, or key. And tune it so legitimate spikes aren't blocked."},
            {"speaker": "Peter", "text": "So it's both defense and availability?"},
            {"speaker": "Stewie", "text": "Exactly. One pattern, two jobs."},
        ],
        "learning_objectives": [
            "Explain rate limiting algorithms and their tradeoffs",
            "Design distributed rate limits with shared state",
            "Use 429 responses and throttling to shed load",
        ],
        "quiz_questions": [
            {
                "question": "What status code signals a client to slow down?",
                "answers": [
                    {"id": "a", "text": "429 Too Many Requests", "correct": True},
                    {"id": "b", "text": "200 OK", "correct": False},
                    {"id": "c", "text": "500 Internal Error", "correct": False},
                    {"id": "d", "text": "301 Redirect", "correct": False},
                ],
            },
            {
                "question": "Why do distributed systems need shared state for rate limits?",
                "answers": [
                    {"id": "a", "text": "One instance cannot enforce a global limit", "correct": True},
                    {"id": "b", "text": "To save memory", "correct": False},
                    {"id": "c", "text": "To avoid logging", "correct": False},
                    {"id": "d", "text": "Shared state is never needed", "correct": False},
                ],
            },
            {
                "question": "Which is a rate limiting algorithm?",
                "answers": [
                    {"id": "a", "text": "Token bucket", "correct": True},
                    {"id": "b", "text": "Binary search", "correct": False},
                    {"id": "c", "text": "Quick sort", "correct": False},
                    {"id": "d", "text": "Hash join", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Security at Scale: Least Privilege Automation",
        "slug": "gh-security-at-scale",
        "description": "How big tech automates least privilege, credential detection, and response across thousands of systems.",
        "hook": "Humans can't review a million permissions. Automation is the only way security survives at scale.",
        "problem": "At scale, manual permission review and response are impossible, so privileges accumulate and credentials leak undetected.",
        "explanation": "Large engineering organizations automate security because scale defeats manual review. The principles, drawn from patterns like Netflix's Aardvark and Repokid: continuously inventory every identity's effective permissions; compute and revoke unused permissions automatically — Repokid analyzes a role's actual usage and removes privileges that were never used; enforce least privilege as a service rather than a policy. TTL-based access revokes stale privileges automatically after a time-to-live. Distributed firewalls and network policies segment at scale. Secret detection scans repositories to keep credentials out of code. Syscall auditing and endpoint monitoring catch abuse across fleets. Security development lifecycles are embedded in the platform. The lesson for any architect: bake least privilege and detection into the platform, automate the boring work, and measure so security stays correct as the estate grows.",
        "real_world_example": "Netflix runs Repokid, which scans every AWS role's last-used permissions and removes anything unused — a continuous, automated least-privilege sweep that no human team could do manually across thousands of roles.",
        "summary": "Automate least privilege with usage-based permission revocation, TTL access, secret scanning, and distributed enforcement — security that relies on manual review does not scale.",
        "curiosity_hook": "Netflix's Repokid literally 'kills' unused permissions on a schedule — least privilege enforced by software, not by review meetings.",
        "dialogue": [
            {"speaker": "Peter", "text": "How do huge companies keep permissions under control?"},
            {"speaker": "Stewie", "text": "They automate it. Manual review doesn't survive scale."},
            {"speaker": "Peter", "text": "Automate least privilege?"},
            {"speaker": "Stewie", "text": "Yes. Analyze what each identity actually uses and revoke the rest."},
            {"speaker": "Peter", "text": "Isn't that what Repokid does?"},
            {"speaker": "Stewie", "text": "Exactly. Netflix's tool removes permissions nobody used. Least privilege as a service."},
            {"speaker": "Peter", "text": "Stale privileges?"},
            {"speaker": "Stewie", "text": "TTL-based access. Privileges expire automatically after a time-to-live."},
            {"speaker": "Peter", "text": "Credentials in code?"},
            {"speaker": "Stewie", "text": "Secret detection scans repositories. Keep credentials out of source."},
            {"speaker": "Peter", "text": "Network at scale?"},
            {"speaker": "Stewie", "text": "Distributed firewalls and network policies. Segmentation that scales with the fleet."},
            {"speaker": "Peter", "text": "Detection?"},
            {"speaker": "Stewie", "text": "Syscall auditing and endpoint monitoring across every host."},
            {"speaker": "Peter", "text": "So the platform does the security work?"},
            {"speaker": "Stewie", "text": "Yes. Bake it in, automate the boring parts, and measure so it stays correct."},
        ],
        "learning_objectives": [
            "Automate least privilege with usage-based permission revocation",
            "Apply TTL access and secret detection at scale",
            "Embed security into the platform instead of manual review",
        ],
        "quiz_questions": [
            {
                "question": "Why must least privilege be automated at scale?",
                "answers": [
                    {"id": "a", "text": "Manual review cannot handle millions of permissions", "correct": True},
                    {"id": "b", "text": "Automation is always slower", "correct": False},
                    {"id": "c", "text": "Manual review is more accurate", "correct": False},
                    {"id": "d", "text": "Permissions never accumulate", "correct": False},
                ],
            },
            {
                "question": "What does Repokid do?",
                "answers": [
                    {"id": "a", "text": "Revokes unused permissions automatically", "correct": True},
                    {"id": "b", "text": "Creates new permissions", "correct": False},
                    {"id": "c", "text": "Deletes accounts", "correct": False},
                    {"id": "d", "text": "Monitors CPU", "correct": False},
                ],
            },
            {
                "question": "What is TTL-based access?",
                "answers": [
                    {"id": "a", "text": "Privileges expire automatically after a time-to-live", "correct": True},
                    {"id": "b", "text": "Permanent access", "correct": False},
                    {"id": "c", "text": "Access without limits", "correct": False},
                    {"id": "d", "text": "Manual revocation", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "aws-security",
        "title": "AWS Security Architecture & Shared Responsibility",
        "slug": "gh-aws-security-architecture",
        "description": "The AWS shared responsibility model and core patterns: IAM, VPC segmentation, and encryption.",
        "hook": "AWS is secure — the question is whether your configuration is. The shared responsibility model draws that line.",
        "problem": "Teams assume the cloud provider secures everything, then leave buckets public, roles over-broad, and networks flat.",
        "explanation": "The AWS shared responsibility model splits duties: AWS secures the cloud (physical data centers, hardware, hypervisor, managed services), and the customer secures what's in the cloud (data, identity, access, and configuration). Core patterns: IAM with least privilege — users, groups, roles, and policies, with roles for workloads instead of long-lived keys; VPC segmentation with subnets, security groups as instance-level firewalls, and network ACLs as subnet-level filters; encryption at rest with KMS and in transit with TLS; S3 locked down with block public access, bucket policies, and versioning; CloudTrail for API auditing and CloudWatch for monitoring; and multi-account strategy with organizational units and service control policies so security baselines inherit everywhere. The line of responsibility is the architect's starting point: know exactly what AWS does and what you must configure.",
        "real_world_example": "A startup deploys with one shared AWS account, a broad admin role, and a public S3 bucket. After a scan exposes the bucket, it moves to multi-account with SCPs, least-privilege roles, and block public access — inherited security instead of hope.",
        "summary": "Know the shared responsibility line, then apply the core patterns: least-privilege IAM, VPC segmentation, KMS encryption, locked-down S3, CloudTrail auditing, and multi-account guardrails.",
        "curiosity_hook": "The most dangerous phrase in AWS is 'it's secure by default' — most leaks come from customer-side configuration, not from AWS itself.",
        "dialogue": [
            {"speaker": "Peter", "text": "AWS handles security, so we're safe, right?"},
            {"speaker": "Stewie", "text": "That's the shared responsibility trap. AWS secures the cloud, you secure what's in it."},
            {"speaker": "Peter", "text": "What exactly do I own?"},
            {"speaker": "Stewie", "text": "Data, identity, access, and configuration. The part most breaches come from."},
            {"speaker": "Peter", "text": "IAM?"},
            {"speaker": "Stewie", "text": "Least privilege. Roles for workloads, not long-lived keys lying around."},
            {"speaker": "Peter", "text": "Networking?"},
            {"speaker": "Stewie", "text": "VPCs with subnets, security groups as firewalls, network ACLs as filters. Segment everything."},
            {"speaker": "Peter", "text": "Encryption?"},
            {"speaker": "Stewie", "text": "KMS for at rest, TLS for in transit. No exceptions."},
            {"speaker": "Peter", "text": "S3?"},
            {"speaker": "Stewie", "text": "Block public access, bucket policies, versioning. The classic leak vector."},
            {"speaker": "Peter", "text": "Auditing?"},
            {"speaker": "Stewie", "text": "CloudTrail for API calls, CloudWatch for monitoring. Can't investigate what you don't log."},
            {"speaker": "Peter", "text": "Many accounts?"},
            {"speaker": "Stewie", "text": "Multi-account with service control policies. Security baselines inherit everywhere."},
            {"speaker": "Peter", "text": "So know the line?"},
            {"speaker": "Stewie", "text": "Exactly. Know what AWS does and what you must configure. That line is the whole game."},
        ],
        "learning_objectives": [
            "Explain the AWS shared responsibility model",
            "Apply least-privilege IAM, VPC segmentation, and KMS encryption",
            "Use CloudTrail, locked-down S3, and multi-account guardrails",
        ],
        "quiz_questions": [
            {
                "question": "Under the shared responsibility model, what does the customer secure?",
                "answers": [
                    {"id": "a", "text": "Data, identity, access, and configuration", "correct": True},
                    {"id": "b", "text": "Physical data centers", "correct": False},
                    {"id": "c", "text": "The hypervisor", "correct": False},
                    {"id": "d", "text": "Server hardware", "correct": False},
                ],
            },
            {
                "question": "What is the classic AWS data leak vector?",
                "answers": [
                    {"id": "a", "text": "Public S3 buckets", "correct": True},
                    {"id": "b", "text": "Encrypted EBS volumes", "correct": False},
                    {"id": "c", "text": "CloudTrail logs", "correct": False},
                    {"id": "d", "text": "Private subnets", "correct": False},
                ],
            },
            {
                "question": "What enforces inherited security baselines across many accounts?",
                "answers": [
                    {"id": "a", "text": "Service control policies and organizational units", "correct": True},
                    {"id": "b", "text": "One shared admin account", "correct": False},
                    {"id": "c", "text": "No policies", "correct": False},
                    {"id": "d", "text": "A public bucket", "correct": False},
                ],
            },
        ],
    },
]
LESSONS = rewrite_lessons_dialogues(LESSONS)
