from dialogue_rewriter import rewrite_lessons_dialogues


LESSONS = [
    {
        "concept_slug": "zero-trust",
        "title": "Zero Trust: Never Trust, Always Verify",
        "slug": "sc100-zero-trust-foundations",
        "description": "Zero Trust is a security model built on three core principles: verify explicitly, use least privilege access, and assume breach. It replaces the outdated perimeter-based 'castle-and-moat' approach with continuous verification across six pillars: identity, devices, networks, applications, infrastructure, and data.",
        "hook": "The castle-and-moat approach to security is officially dead. If your firewall goes down, should the whole network fall? Zero Trust says: verify everything, everywhere, all the time.",
        "problem": "Traditional perimeter security assumes everything inside the network is safe. Attackers who breach the perimeter move laterally with ease, as seen in breaches like SolarWinds and Colonial Pipeline.",
        "explanation": "Zero Trust flips the model. Instead of trusting anyone inside the network, every access request is verified regardless of location. The three pillars are: verify explicitly (authenticate and authorize every request), least privilege access (minimum permissions needed), and assume breach (design as if attackers are already inside). These apply across identity, devices, networks, applications, infrastructure, and data.",
        "real_world_example": "After the SolarWinds attack, Microsoft implemented Zero Trust across their own environment. When attackers compromised a single account, least-privilege policies and microsegmentation prevented lateral movement to critical systems, limiting the blast radius significantly.",
        "summary": "Zero Trust is not a product you buy but a strategy you adopt. By verifying explicitly, enforcing least privilege, and assuming breach, organizations dramatically reduce the attack surface across all six security pillars.",
        "curiosity_hook": "Here's the kicker: the term 'Zero Trust' was coined in 2010, but most organizations still haven't fully implemented it. What's the biggest barrier?",
        "dialogue": [
            {"speaker": "Peter", "text": "So Stewie, what exactly is Zero Trust? Sounds paranoid."},
            {"speaker": "Stewie", "text": "It's not paranoia, Peter. It's verifying every single request, no matter where it comes from."},
            {"speaker": "Peter", "text": "But what about the firewall? That's supposed to keep bad guys out, right?"},
            {"speaker": "Stewie", "text": "That's castle-and-moat thinking. Once someone's past the wall, they roam free. Think SolarWinds."},
            {"speaker": "Peter", "text": "So we just... trust nobody? That sounds exhausting."},
            {"speaker": "Stewie", "text": "Three principles: verify explicitly, least privilege, and assume breach. That's it."},
            {"speaker": "Peter", "text": "Assume breach? So we just expect to get hacked?"},
            {"speaker": "Stewie", "text": "You design your defenses so that even if an attacker gets in, they can't move laterally."},
            {"speaker": "Peter", "text": "What are the six pillars you mentioned earlier?"},
            {"speaker": "Stewie", "text": "Identity, devices, networks, apps, infrastructure, and data. All six need Zero Trust."},
            {"speaker": "Peter", "text": "So it's basically securing everything twice over?"},
            {"speaker": "Stewie", "text": "Exactly. Every door gets a lock, not just the front gate."},
        ],
        "learning_objectives": [
            "Explain the three core principles of Zero Trust: verify explicitly, least privilege access, and assume breach",
            "Identify the six pillars of Zero Trust and why each requires protection",
            "Compare perimeter-based security with Zero Trust and explain why the castle-and-moat model fails",
        ],
        "quiz_questions": [
            {
                "question": "What are the three core principles of Zero Trust?",
                "answers": [
                    {"id": "a", "text": "Verify explicitly, least privilege access, assume breach", "correct": True},
                    {"id": "b", "text": "Firewall, antivirus, encryption", "correct": False},
                    {"id": "c", "text": "VPN, MFA, DLP", "correct": False},
                    {"id": "d", "text": "Encrypt, monitor, patch", "correct": False},
                ],
            },
            {
                "question": "Which of the following is NOT one of the six Zero Trust pillars?",
                "answers": [
                    {"id": "a", "text": "Identity", "correct": False},
                    {"id": "b", "text": "Compliance", "correct": True},
                    {"id": "c", "text": "Data", "correct": False},
                    {"id": "d", "text": "Infrastructure", "correct": False},
                ],
            },
            {
                "question": "Why is the castle-and-moat security model considered outdated?",
                "answers": [
                    {"id": "a", "text": "It relies too heavily on encryption", "correct": False},
                    {"id": "b", "text": "It assumes everything inside the perimeter is safe", "correct": True},
                    {"id": "c", "text": "It uses too many firewalls", "correct": False},
                    {"id": "d", "text": "It requires too much user authentication", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Zero Trust Adoption: From Strategy to Deployment",
        "slug": "sc100-zero-trust-adoption",
        "description": "Microsoft's Zero Trust adoption framework follows five phases: identify, plan, deploy, operate, and evolve. A successful rollout requires C-suite buy-in, pilot groups, and measurable success through Microsoft Secure Score.",
        "hook": "Knowing Zero Trust is great. Actually deploying it across an enterprise with legacy systems, politics, and budget constraints? That's the real challenge.",
        "problem": "Organizations often buy Zero Trust tools without a strategy. They deploy point solutions in isolation, creating gaps and silos instead of a cohesive security posture.",
        "explanation": "Microsoft's adoption framework provides five phases: identify your current posture and business scenarios, plan with stakeholder buy-in, deploy incrementally through pilot groups, operate with monitoring and incident response, and evolve by continuously improving. C-suite sponsorship and measuring success with Secure Score keep the program on track.",
        "real_world_example": "A large financial services firm used Microsoft's framework to deploy Zero Trust in phases. They started with identity (enforcing MFA), then devices (compliance policies in Intune), then network segmentation. After 18 months, their Secure Score jumped from 42% to 78%, and lateral-movement incidents dropped by 65%.",
        "summary": "Zero Trust adoption is a journey, not a one-time project. Following a structured framework with executive support, phased deployment, and measurable outcomes ensures long-term success.",
        "curiosity_hook": "Did you know that organizations with executive sponsorship are 3x more likely to complete their Zero Trust journey? Let's talk about why the C-suite matters.",
        "dialogue": [
            {"speaker": "Peter", "text": "Okay, I get Zero Trust conceptually. But how do you actually deploy it?"},
            {"speaker": "Stewie", "text": "Microsoft has a five-phase framework: identify, plan, deploy, operate, evolve."},
            {"speaker": "Peter", "text": "Five phases? That sounds like corporate jargon to me."},
            {"speaker": "Stewie", "text": "Phase one is identifying your current security gaps and business scenarios."},
            {"speaker": "Peter", "text": "So you need to know what's broken before you fix it? Revolutionary."},
            {"speaker": "Stewie", "text": "You'd be surprised how many skip that step. They just start buying tools."},
            {"speaker": "Peter", "text": "What about getting the bosses to sign off on all this?"},
            {"speaker": "Stewie", "text": "C-suite buy-in is critical. No budget, no Zero Trust. It's that simple."},
            {"speaker": "Peter", "text": "And how do you prove it's actually working?"},
            {"speaker": "Stewie", "text": "Microsoft Secure Score gives you a measurable baseline. Track it monthly."},
            {"speaker": "Peter", "text": "So you deploy it in phases instead of all at once?"},
            {"speaker": "Stewie", "text": "Exactly. Start with a pilot group, validate, then expand across the org."},
        ],
        "learning_objectives": [
            "Describe the five phases of Microsoft's Zero Trust adoption framework",
            "Explain why executive sponsorship is critical for Zero Trust deployment",
            "Identify Microsoft Secure Score as a tool for measuring Zero Trust progress",
        ],
        "quiz_questions": [
            {
                "question": "What is the correct order of Microsoft's five Zero Trust adoption phases?",
                "answers": [
                    {"id": "a", "text": "Identify, Plan, Deploy, Operate, Evolve", "correct": True},
                    {"id": "b", "text": "Plan, Identify, Deploy, Evolve, Operate", "correct": False},
                    {"id": "c", "text": "Deploy, Plan, Identify, Operate, Evolve", "correct": False},
                    {"id": "d", "text": "Identify, Deploy, Plan, Operate, Evolve", "correct": False},
                ],
            },
            {
                "question": "Why is C-suite sponsorship important for Zero Trust adoption?",
                "answers": [
                    {"id": "a", "text": "They configure the security tools", "correct": False},
                    {"id": "b", "text": "They provide budget and organizational authority", "correct": True},
                    {"id": "c", "text": "They handle incident response", "correct": False},
                    {"id": "d", "text": "They run the pilot programs", "correct": False},
                ],
            },
            {
                "question": "What tool does Microsoft provide to measure your security posture over time?",
                "answers": [
                    {"id": "a", "text": "Azure Monitor", "correct": False},
                    {"id": "b", "text": "Microsoft Sentinel", "correct": False},
                    {"id": "c", "text": "Microsoft Secure Score", "correct": True},
                    {"id": "d", "text": "Entra ID Protection", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Identity as the New Security Perimeter",
        "slug": "sc100-identity-perimeter",
        "description": "In Zero Trust, identity is the control plane. It replaces the network perimeter with a fabric of SSO, MFA, passwordless authentication, FIDO2, Windows Hello, device trust, and hybrid identity via Entra Connect.",
        "hook": "Forget firewalls. In a world where your workforce works from coffee shops, airports, and couches, identity IS your perimeter.",
        "problem": "With remote work, cloud apps, and BYOD, the traditional network boundary no longer exists. Attackers target credentials because they're the easiest path into any environment.",
        "explanation": "Identity fabric design weaves together single sign-on, multi-factor authentication, passwordless options like FIDO2 and Windows Hello, and device trust. Hybrid environments use Entra Connect to sync on-premises AD with Entra ID. Identity becomes the control plane that enforces Zero Trust policies across every access request.",
        "real_world_example": "Google implemented BeyondCorp, an identity-centric Zero Trust model, after the Operation Aurora attacks. Every employee accesses internal apps based on identity and device state, not network location. They saw a 50% reduction in phishing-related incidents after enforcing FIDO2 keys for all staff.",
        "summary": "Identity is no longer just a login system. It's the security perimeter itself. Organizations that invest in strong identity controls with MFA, passwordless auth, and device trust build the foundation for Zero Trust.",
        "curiosity_hook": "Here's a thought: if identity is the perimeter, then your password is the front door. And most people leave that front door wide open.",
        "dialogue": [
            {"speaker": "Peter", "text": "Wait, identity is the perimeter now? What happened to firewalls?"},
            {"speaker": "Stewie", "text": "Firewalls protect a network boundary. There is no boundary anymore, Peter."},
            {"speaker": "Peter", "text": "Because everyone works from home or a Starbucks somewhere?"},
            {"speaker": "Stewie", "text": "Exactly. So we verify WHO you are, not WHERE you are."},
            {"speaker": "Peter", "text": "How do you do that? Just a better password?"},
            {"speaker": "Stewie", "text": "No. Passwordless auth, FIDO2 keys, Windows Hello, MFA. The works."},
            {"speaker": "Peter", "text": "What's FIDO2? Sounds like a Star Wars droid."},
            {"speaker": "Stewie", "text": "It's a hardware security key. Phish-proof. Even if you click a fake login, the key won't work on it."},
            {"speaker": "Peter", "text": "And SSO? I see that acronym everywhere."},
            {"speaker": "Stewie", "text": "Single Sign-On. One login gives you access to all your apps securely, no password fatigue."},
            {"speaker": "Peter", "text": "What about companies still running on-prem Active Directory?"},
            {"speaker": "Stewie", "text": "Entra Connect syncs your on-prem AD to the cloud. Hybrid identity, best of both worlds."},
        ],
        "learning_objectives": [
            "Explain why identity replaces the network perimeter in a Zero Trust architecture",
            "Identify modern authentication methods including MFA, FIDO2, Windows Hello, and passwordless",
            "Describe how hybrid identity works with Entra Connect for organizations with on-premises Active Directory",
        ],
        "quiz_questions": [
            {
                "question": "Why is identity considered the new security perimeter?",
                "answers": [
                    {"id": "a", "text": "Because users are no longer confined to a physical network location", "correct": True},
                    {"id": "b", "text": "Because firewalls are no longer needed", "correct": False},
                    {"id": "c", "text": "Because identity systems are unhackable", "correct": False},
                    {"id": "d", "text": "Because passwords are the strongest form of security", "correct": False},
                ],
            },
            {
                "question": "Which authentication method is considered phish-proof?",
                "answers": [
                    {"id": "a", "text": "SMS-based MFA", "correct": False},
                    {"id": "b", "text": "Email OTP", "correct": False},
                    {"id": "c", "text": "FIDO2 hardware security key", "correct": True},
                    {"id": "d", "text": "Security questions", "correct": False},
                ],
            },
            {
                "question": "What does Entra Connect do in a hybrid environment?",
                "answers": [
                    {"id": "a", "text": "Replaces on-premises Active Directory", "correct": False},
                    {"id": "b", "text": "Syncs on-premises AD with Entra ID in the cloud", "correct": True},
                    {"id": "c", "text": "Provides single sign-on only", "correct": False},
                    {"id": "d", "text": "Manages device compliance policies", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Device Security & Compliance",
        "slug": "sc100-device-compliance",
        "description": "Device compliance in Zero Trust means every device must prove its health before accessing resources. Intune enforces compliance policies, Defender for Endpoint provides EDR, and Conditional Access blocks unhealthy devices.",
        "hook": "Your laptop is the gateway to your company's data. If it's compromised, everything behind it is too. Device compliance policies ensure only healthy devices get access.",
        "problem": "With BYOD and remote work, organizations have thousands of unmanaged devices accessing corporate resources. A single compromised device can become an attacker's foothold into the entire network.",
        "explanation": "Microsoft Intune manages device compliance through policies that check encryption, OS version, jailbreak status, and more. Conditional Access uses device health as a gate: compliant devices get access, non-compliant ones get blocked. Defender for Endpoint provides EDR capabilities, while application protection policies secure data on unmanaged BYOD devices without full device management.",
        "real_world_example": "A hospital chain used Intune compliance policies to ensure all devices accessing patient records ran the latest OS version and had disk encryption enabled. When a ransomware attack hit their network, unpatched BYOD tablets were automatically blocked by Conditional Access, preventing the malware from reaching their Electronic Health Records system.",
        "summary": "Device compliance is a Zero Trust gatekeeper. Intune policies, Conditional Access, and Defender for Endpoint work together to ensure only healthy, verified devices can access corporate resources.",
        "curiosity_hook": "What if I told you that a single non-compliant device on your network could be the entry point for a multi-million dollar breach?",
        "dialogue": [
            {"speaker": "Peter", "text": "So we verified the user's identity. But what about their device?"},
            {"speaker": "Stewie", "text": "Great question. Identity is half the equation. The device has to be healthy too."},
            {"speaker": "Peter", "text": "How do you check if a device is healthy? Run some antivirus on it?"},
            {"speaker": "Stewie", "text": "Microsoft Intune checks compliance: encryption, OS version, jailbreak status, firewall."},
            {"speaker": "Peter", "text": "And if the device fails the check?"},
            {"speaker": "Stewie", "text": "Conditional Access blocks it. No compliant device, no access. Simple."},
            {"speaker": "Peter", "text": "What about people using their personal phones for work email?"},
            {"speaker": "Stewie", "text": "App protection policies secure the corporate data without managing the whole device."},
            {"speaker": "Peter", "text": "That sounds like BYOD without the headaches."},
            {"speaker": "Stewie", "text": "Exactly. Company data stays encrypted and controlled, personal stuff stays private."},
            {"speaker": "Peter", "text": "What about detecting threats on the device itself?"},
            {"speaker": "Stewie", "text": "Defender for Endpoint handles EDR. It detects, investigates, and responds to threats."},
        ],
        "learning_objectives": [
            "Explain how Intune device compliance policies enforce device health requirements",
            "Describe how Conditional Access uses device compliance as an access gate",
            "Differentiate between device management (Intune) and application protection policies for BYOD",
        ],
        "quiz_questions": [
            {
                "question": "What does Intune check in a device compliance policy?",
                "answers": [
                    {"id": "a", "text": "Only the device's serial number", "correct": False},
                    {"id": "b", "text": "Encryption status, OS version, jailbreak status, and firewall", "correct": True},
                    {"id": "c", "text": "Only whether the user is in the correct group", "correct": False},
                    {"id": "d", "text": "Network bandwidth and storage capacity", "correct": False},
                ],
            },
            {
                "question": "What happens when a device fails a compliance check with Conditional Access?",
                "answers": [
                    {"id": "a", "text": "The device is automatically wiped", "correct": False},
                    {"id": "b", "text": "The user receives a warning but still gets access", "correct": False},
                    {"id": "c", "text": "Access to corporate resources is blocked", "correct": True},
                    {"id": "d", "text": "The device is quarantined on a separate VLAN", "correct": False},
                ],
            },
            {
                "question": "What is the purpose of application protection policies?",
                "answers": [
                    {"id": "a", "text": "They manage the entire device through Intune", "correct": False},
                    {"id": "b", "text": "They protect corporate data on unmanaged BYOD devices", "correct": True},
                    {"id": "c", "text": "They install antivirus software on personal devices", "correct": False},
                    {"id": "d", "text": "They replace the need for device compliance", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Network Security in a Zero Trust World",
        "slug": "sc100-network-zero-trust",
        "description": "Zero Trust eliminates the traditional DMZ. Microsegmentation, Azure Firewall, WAF, private endpoints, and Azure Bastion replace flat networks with granular, identity-aware controls.",
        "hook": "In a Zero Trust world, there's no trusted internal network. Every segment is a potential attack vector, and every connection must be verified.",
        "problem": "Traditional flat networks let attackers move laterally once they breach the perimeter. DMZs create false confidence, and VPNs grant broad network access instead of specific resource access.",
        "explanation": "Zero Trust network architecture uses microsegmentation to isolate workloads, Azure Firewall for traffic inspection, WAF for web application protection, private endpoints to keep traffic off the public internet, and Azure Bastion for secure remote access. The DMZ concept is eliminated because no zone is inherently trusted.",
        "real_world_example": "A retail company migrated to Azure and replaced their flat on-prem network with microsegmented VNETs. Each application tier lived in its own segment with NSGs restricting traffic. When attackers compromised a public-facing web app, they couldn't pivot to the database tier because the microsegmentation rules blocked lateral movement entirely.",
        "summary": "Zero Trust networking means no implicit trust for any network segment. Microsegmentation, firewalls, WAF, and private endpoints work together to contain threats and eliminate the flat network problem.",
        "curiosity_hook": "Did you know that the average cost of a lateral movement breach is $4.45 million? Microsegmentation could prevent every dollar of that.",
        "dialogue": [
            {"speaker": "Peter", "text": "So how does networking work in Zero Trust? No more firewalls?"},
            {"speaker": "Stewie", "text": "Firewalls still exist. But the idea of a trusted internal network is gone."},
            {"speaker": "Peter", "text": "What does that mean exactly? I'm inside the building, I should be trusted!"},
            {"speaker": "Stewie", "text": "Microsegmentation splits your network into tiny isolated zones."},
            {"speaker": "Peter", "text": "So if an attacker gets in one zone, they can't reach the others?"},
            {"speaker": "Stewie", "text": "Exactly. Each zone has its own rules. No free lateral movement."},
            {"speaker": "Peter", "text": "What about web apps? Those seem like easy targets."},
            {"speaker": "Stewie", "text": "Azure Web Application Firewall inspects and blocks malicious web traffic."},
            {"speaker": "Peter", "text": "And how do admins securely access servers for maintenance?"},
            {"speaker": "Stewie", "text": "Azure Bastion. It's a hardened jump box. No public RDP or SSH needed."},
            {"speaker": "Peter", "text": "So the old DMZ concept is just... dead?"},
            {"speaker": "Stewie", "text": "Dead and buried. In Zero Trust, every network segment is treated as hostile."},
        ],
        "learning_objectives": [
            "Explain how microsegmentation prevents lateral movement in a Zero Trust network",
            "Identify Azure networking security services: Firewall, WAF, private endpoints, and Bastion",
            "Describe why the traditional DMZ model is replaced in Zero Trust architectures",
        ],
        "quiz_questions": [
            {
                "question": "What does microsegmentation do in a Zero Trust network?",
                "answers": [
                    {"id": "a", "text": "Creates a single large network segment for all workloads", "correct": False},
                    {"id": "b", "text": "Isolates workloads into small segments with individual access controls", "correct": True},
                    {"id": "c", "text": "Replaces all firewalls with software-defined networking", "correct": False},
                    {"id": "d", "text": "Provides VPN access for remote users", "correct": False},
                ],
            },
            {
                "question": "What is the purpose of Azure Bastion?",
                "answers": [
                    {"id": "a", "text": "It acts as a public DNS server", "correct": False},
                    {"id": "b", "text": "It provides secure RDP/SSH access without exposing public IPs", "correct": True},
                    {"id": "c", "text": "It segments the network into zones", "correct": False},
                    {"id": "d", "text": "It inspects web application traffic", "correct": False},
                ],
            },
            {
                "question": "Why is the traditional DMZ model considered obsolete in Zero Trust?",
                "answers": [
                    {"id": "a", "text": "DMZs are too expensive to maintain", "correct": False},
                    {"id": "b", "text": "Because Zero Trust treats every network segment as potentially hostile", "correct": True},
                    {"id": "c", "text": "DMZs only work with on-premises infrastructure", "correct": False},
                    {"id": "d", "text": "Because cloud providers don't support DMZs", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "zero-trust",
        "title": "Data Security & Protection",
        "slug": "sc100-data-protection",
        "description": "Data is what attackers ultimately want. Zero Trust data protection uses sensitivity labels, encryption at rest and in transit, DLP policies, Microsoft Purview, Key Vault, and retention policies to safeguard your most valuable asset.",
        "hook": "Hackers don't break in to steal your servers. They break in to steal your data. If you don't know where your sensitive data lives, neither do you.",
        "problem": "Organizations generate massive amounts of data but often lack visibility into what's sensitive, where it resides, and who has access to it. Without classification and protection, data leaks become inevitable.",
        "explanation": "Microsoft Purview Information Protection provides data classification through sensitivity labels that encrypt and restrict access. DLP policies prevent sensitive data from leaving the organization. Encryption at rest and in transit protects data in storage and movement. Azure Key Vault manages secrets and keys. Retention policies ensure data governance and sovereignty compliance.",
        "real_world_example": "A healthcare provider used Microsoft Purview to classify 2.3 million documents containing patient data. Sensitivity labels automatically encrypted files marked as 'Confidential.' DLP policies blocked attempts to email patient records to personal accounts, preventing HIPAA violations that could have cost $50 million in fines.",
        "summary": "Data-centric security is the heart of Zero Trust. Classify your data, encrypt it everywhere, prevent leakage with DLP, and manage secrets properly. If you protect the data, you protect the business.",
        "curiosity_hook": "Studies show that 68% of breached organizations didn't even know they had sensitive data in the affected system. Classification changes everything.",
        "dialogue": [
            {"speaker": "Peter", "text": "Okay, so we've secured identity, devices, networks. What about the actual data?"},
            {"speaker": "Stewie", "text": "That's the crown jewel, Peter. Attackers want your data, not your firewall configs."},
            {"speaker": "Peter", "text": "So how do you protect data specifically? Just encrypt everything?"},
            {"speaker": "Stewie", "text": "Step one: classify it. You can't protect what you don't know exists."},
            {"speaker": "Peter", "text": "Microsoft Purview does that? How does it know what's sensitive?"},
            {"speaker": "Stewie", "text": "Sensitivity labels. You define what's public, internal, confidential, top secret."},
            {"speaker": "Peter", "text": "And once it's labeled, what happens?"},
            {"speaker": "Stewie", "text": "Encryption kicks in. Access is restricted. DLP policies prevent leakage."},
            {"speaker": "Peter", "text": "DLP? Data Loss Prevention? Sounds like corporate buzzword soup."},
            {"speaker": "Stewie", "text": "It literally blocks emails with credit card numbers or patient records from leaving."},
            {"speaker": "Peter", "text": "What about encryption keys and secrets? Where do those live?"},
            {"speaker": "Stewie", "text": "Azure Key Vault. Hardware-protected, audited, and fully managed."},
        ],
        "learning_objectives": [
            "Explain how Microsoft Purview sensitivity labels classify and protect data",
            "Describe the role of DLP policies in preventing data leakage",
            "Identify the purpose of Azure Key Vault for secrets and key management",
        ],
        "quiz_questions": [
            {
                "question": "What is the first step in a data security strategy?",
                "answers": [
                    {"id": "a", "text": "Encrypt all data immediately", "correct": False},
                    {"id": "b", "text": "Classify and discover sensitive data", "correct": True},
                    {"id": "c", "text": "Implement DLP policies", "correct": False},
                    {"id": "d", "text": "Move all data to Azure Key Vault", "correct": False},
                ],
            },
            {
                "question": "What do sensitivity labels in Microsoft Purview do?",
                "answers": [
                    {"id": "a", "text": "They only tag documents with visual markers", "correct": False},
                    {"id": "b", "text": "They encrypt and restrict access to classified data", "correct": True},
                    {"id": "c", "text": "They delete sensitive data automatically", "correct": False},
                    {"id": "d", "text": "They replace the need for DLP policies", "correct": False},
                ],
            },
            {
                "question": "What does Azure Key Vault manage?",
                "answers": [
                    {"id": "a", "text": "User passwords and login sessions", "correct": False},
                    {"id": "b", "text": "Encryption keys, secrets, and certificates", "correct": True},
                    {"id": "c", "text": "Network firewall rules", "correct": False},
                    {"id": "d", "text": "Device compliance policies", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "The Cloud Adoption Framework",
        "slug": "sc100-cloud-adoption-framework",
        "description": "Microsoft's Cloud Adoption Framework (CAF) guides organizations through seven methodologies: Strategy, Plan, Ready, Adopt, Govern, Manage, and Organize. It covers migration, innovation, landing zones, and building a cloud center of excellence.",
        "hook": "Moving to the cloud without a framework is like building a house without a blueprint. You'll end up with something, but you probably won't want to live in it.",
        "problem": "Organizations rush to cloud adoption without proper planning. They end up with ungoverned subscriptions, spiraling costs, security gaps, and no clear strategy for what to migrate versus what to modernize.",
        "explanation": "The Cloud Adoption Framework provides seven methodologies. Strategy defines why you're going to cloud. Plan details what to migrate. Ready prepares landing zones. Adopt executes migrations and innovations. Govern establishes guardrails. Manage handles operations. Organize defines team structures. Together, they provide a structured journey from on-premises to cloud.",
        "real_world_example": "A manufacturing company used CAF to migrate 400 servers to Azure. They started with Strategy (reducing datacenter costs), built landing zones in Ready, migrated workloads in Adopt, and established governance policies. They saved $2.1M annually in datacenter costs and reduced deployment time from weeks to hours.",
        "summary": "The Cloud Adoption Framework is a comprehensive guide that takes organizations from cloud strategy to operational management. Following all seven methodologies ensures a structured, successful cloud transformation.",
        "curiosity_hook": "Microsoft reports that organizations using CAF are 50% more likely to meet their cloud migration timelines. The framework exists because the hard lessons have already been learned.",
        "dialogue": [
            {"speaker": "Peter", "text": "So our company wants to move to the cloud. Where do we even start?"},
            {"speaker": "Stewie", "text": "Microsoft has the Cloud Adoption Framework. Seven steps from strategy to operations."},
            {"speaker": "Peter", "text": "Seven steps? Can't we just lift and shift everything?"},
            {"speaker": "Stewie", "text": "That's what companies that end up with a $200K monthly bill thought too."},
            {"speaker": "Peter", "text": "Fair point. What's the first step?"},
            {"speaker": "Stewie", "text": "Strategy. Define WHY you're going to cloud. Cost? Agility? Scalability?"},
            {"speaker": "Peter", "text": "Then what?"},
            {"speaker": "Stewie", "text": "Plan what to migrate, Ready your landing zones, then Adopt by migrating workloads."},
            {"speaker": "Peter", "text": "What are landing zones? Some kind of cloud infrastructure?"},
            {"speaker": "Stewie", "text": "They're pre-configured environments with governance and security built in."},
            {"speaker": "Peter", "text": "And the last steps?"},
            {"speaker": "Stewie", "text": "Govern to set guardrails, Manage for operations, and Organize your teams."},
        ],
        "learning_objectives": [
            "List the seven methodologies of the Microsoft Cloud Adoption Framework",
            "Explain the difference between migration and innovation strategies in CAF",
            "Describe the purpose of a cloud center of excellence for sustained cloud adoption",
        ],
        "quiz_questions": [
            {
                "question": "Which of the following is NOT one of the seven CAF methodologies?",
                "answers": [
                    {"id": "a", "text": "Strategy", "correct": False},
                    {"id": "b", "text": "Innovate", "correct": True},
                    {"id": "c", "text": "Govern", "correct": False},
                    {"id": "d", "text": "Manage", "correct": False},
                ],
            },
            {
                "question": "What is the purpose of the 'Ready' phase in the Cloud Adoption Framework?",
                "answers": [
                    {"id": "a", "text": "To define the business case for cloud migration", "correct": False},
                    {"id": "b", "text": "To prepare landing zones and cloud infrastructure", "correct": True},
                    {"id": "c", "text": "To execute the actual workload migration", "correct": False},
                    {"id": "d", "text": "To manage cloud operations post-migration", "correct": False},
                ],
            },
            {
                "question": "What does the 'Govern' methodology provide?",
                "answers": [
                    {"id": "a", "text": "Technical support for migrated workloads", "correct": False},
                    {"id": "b", "text": "Team structure and organizational roles", "correct": False},
                    {"id": "c", "text": "Guardrails and policies to manage cloud resources", "correct": True},
                    {"id": "d", "text": "Cost optimization recommendations", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "Azure Landing Zones Explained",
        "slug": "sc100-azure-landing-zones",
        "description": "Azure landing zones are pre-configured environments that provide scale, governance, and security from day one. They include management group hierarchies, subscription designs, and connectivity and identity subscriptions across six design areas.",
        "hook": "Think of a landing zone as a pre-built foundation for your cloud house. Skip it, and you're building on sand.",
        "problem": "Organizations create Azure subscriptions ad hoc, resulting in inconsistent naming, missing policies, security gaps, and no coherent governance structure. This creates technical debt from day one.",
        "explanation": "Landing zones come in two flavors: platform (managing core infrastructure like connectivity, identity, and management) and application (hosting workloads). Enterprise-scale landing zones use management group hierarchies to enforce policies, dedicated subscriptions for connectivity and identity, and six design areas: identity, topology, management, security, governance, and deployment automation.",
        "real_world_example": "A global bank deployed enterprise-scale landing zones with a connectivity subscription for Azure Firewall and VPN Gateway, an identity subscription for Entra Connect, and separate application subscriptions per business unit. Policy-as-code enforced encryption standards across all subscriptions, reducing compliance audit preparation from 3 months to 2 weeks.",
        "summary": "Landing zones are the foundation of a well-governed Azure environment. Platform and application landing zones, combined with proper subscription design and six key design areas, ensure your cloud grows sustainably.",
        "curiosity_hook": "Microsoft estimates that 70% of Azure environments have governance issues that landing zones would have prevented. The foundation matters more than you think.",
        "dialogue": [
            {"speaker": "Peter", "text": "So what exactly is an Azure landing zone? Is it like a VM?"},
            {"speaker": "Stewie", "text": "No. It's a pre-configured environment with governance baked in from the start."},
            {"speaker": "Peter", "text": "How is that different from just creating a subscription?"},
            {"speaker": "Stewie", "text": "A subscription is just a billing boundary. A landing zone has policies, networking, and security."},
            {"speaker": "Peter", "text": "You mentioned two types. Platform and application?"},
            {"speaker": "Stewie", "text": "Platform handles core infrastructure. Connectivity, identity, management. Application hosts your workloads."},
            {"speaker": "Peter", "text": "And enterprise-scale? Is that the big-company version?"},
            {"speaker": "Stewie", "text": "It uses management group hierarchies and dedicated subscriptions for scale."},
            {"speaker": "Peter", "text": "What are the six design areas you mentioned?"},
            {"speaker": "Stewie", "text": "Identity, topology, management, security, governance, and deployment automation."},
            {"speaker": "Peter", "text": "So everything is planned out before you even deploy a workload?"},
            {"speaker": "Stewie", "text": "Exactly. Build the foundation right, and everything on top is solid."},
        ],
        "learning_objectives": [
            "Differentiate between platform and application landing zones",
            "Describe the enterprise-scale landing zone architecture with management group hierarchies",
            "Identify the six design areas of Azure landing zones",
        ],
        "quiz_questions": [
            {
                "question": "What is the difference between platform and application landing zones?",
                "answers": [
                    {"id": "a", "text": "Platform manages core infrastructure; application hosts workloads", "correct": True},
                    {"id": "b", "text": "Platform is for small companies; application is for enterprise", "correct": False},
                    {"id": "c", "text": "They are the same thing with different names", "correct": False},
                    {"id": "d", "text": "Platform is for production; application is for development", "correct": False},
                ],
            },
            {
                "question": "Which of the following is one of the six landing zone design areas?",
                "answers": [
                    {"id": "a", "text": "Budget optimization", "correct": False},
                    {"id": "b", "text": "Deployment automation", "correct": True},
                    {"id": "c", "text": "User experience", "correct": False},
                    {"id": "d", "text": "Marketing compliance", "correct": False},
                ],
            },
            {
                "question": "What does enterprise-scale landing zones use to enforce policies at scale?",
                "answers": [
                    {"id": "a", "text": "Manual configuration on each subscription", "correct": False},
                    {"id": "b", "text": "Management group hierarchies and policy assignments", "correct": True},
                    {"id": "c", "text": "A single ARM template for all resources", "correct": False},
                    {"id": "d", "text": "Third-party governance tools only", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "Azure Well-Architected Framework",
        "slug": "sc100-well-architected-framework",
        "description": "The Azure Well-Architected Framework evaluates workloads across five pillars: Reliability, Security, Cost Optimization, Operational Excellence, and Performance Efficiency. The security pillar is a deep dive within Zero Trust principles.",
        "hook": "Building in the cloud is easy. Building WELL in the cloud? That takes a framework and trade-off awareness.",
        "problem": "Teams deploy cloud workloads focusing only on functionality. They ignore reliability, cost, and operational excellence until something breaks or the bill arrives.",
        "explanation": "The Well-Architected Framework provides five pillars. Reliability ensures uptime and disaster recovery. Security covers defense-in-depth and Zero Trust. Cost Optimization manages spending without sacrificing quality. Operational Excellence automates and monitors. Performance Efficiency scales appropriately. The key insight is that these pillars involve trade-offs: maximum reliability costs more, and cutting costs can impact performance.",
        "real_world_example": "A SaaS company used the WAF assessment tool and discovered their architecture scored 35% on Cost Optimization because they over-provisioned for peak load. By implementing auto-scaling and reserved instances, they cut costs by 40% while maintaining 99.95% reliability. The assessment tool helped them identify the exact trade-off sweet spot.",
        "summary": "The Well-Architected Framework ensures cloud workloads balance reliability, security, cost, operations, and performance. Regular assessments and understanding trade-offs between pillars lead to optimized architectures.",
        "curiosity_hook": "Most organizations focus on security and performance but ignore operational excellence. Microsoft found that teams with high operational excellence scores resolve incidents 60% faster.",
        "dialogue": [
            {"speaker": "Peter", "text": "So the Well-Architected Framework. What is that, some kind of cloud blueprint?"},
            {"speaker": "Stewie", "text": "It's five pillars: reliability, security, cost optimization, operations, performance."},
            {"speaker": "Peter", "text": "Five pillars? That's a lot of pillars. Do they all matter equally?"},
            {"speaker": "Stewie", "text": "They all matter, but there are trade-offs. Maximum reliability costs more."},
            {"speaker": "Peter", "text": "So you can't have everything? There's no free lunch in the cloud?"},
            {"speaker": "Stewie", "text": "Welcome to architecture 101. You balance trade-offs based on business needs."},
            {"speaker": "Peter", "text": "How do you know if your architecture is any good?"},
            {"speaker": "Stewie", "text": "Microsoft has a free assessment tool. It scores your workload on all five pillars."},
            {"speaker": "Peter", "text": "And the security pillar? What does that cover?"},
            {"speaker": "Stewie", "text": "Defense-in-depth, Zero Trust principles, encryption, identity, and network security."},
            {"speaker": "Peter", "text": "So it's basically the whole SC-100 exam in one pillar?"},
            {"speaker": "Stewie", "text": "Pretty much. The security pillar is the deepest of the five."},
        ],
        "learning_objectives": [
            "List and describe the five pillars of the Azure Well-Architected Framework",
            "Explain the trade-offs between cost optimization and reliability in cloud architecture",
            "Describe how the WAF assessment tool helps evaluate workload architecture",
        ],
        "quiz_questions": [
            {
                "question": "Which are the five pillars of the Azure Well-Architected Framework?",
                "answers": [
                    {"id": "a", "text": "Reliability, Security, Cost Optimization, Operational Excellence, Performance Efficiency", "correct": True},
                    {"id": "b", "text": "Identity, Devices, Networks, Data, Applications", "correct": False},
                    {"id": "c", "text": "Strategy, Plan, Ready, Adopt, Govern", "correct": False},
                    {"id": "d", "text": "Availability, Scalability, Durability, Redundancy, Recovery", "correct": False},
                ],
            },
            {
                "question": "What is a key insight of the Well-Architected Framework?",
                "answers": [
                    {"id": "a", "text": "All five pillars can be maximized simultaneously without trade-offs", "correct": False},
                    {"id": "b", "text": "Security should always take priority over cost", "correct": False},
                    {"id": "c", "text": "Pillars involve trade-offs that must be balanced based on business needs", "correct": True},
                    {"id": "d", "text": "Only the security and reliability pillars matter in practice", "correct": False},
                ],
            },
            {
                "question": "How does Microsoft help organizations evaluate their cloud architecture?",
                "answers": [
                    {"id": "a", "text": "Through mandatory annual audits", "correct": False},
                    {"id": "b", "text": "Through a free Well-Architected assessment tool", "correct": True},
                    {"id": "c", "text": "Through paid consulting engagements only", "correct": False},
                    {"id": "d", "text": "Through Azure Support tickets", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "MCRA & MCSB: Microsoft Security Blueprints",
        "slug": "sc100-mcra-mcsb-blueprints",
        "description": "The Microsoft Cloud Reference Architecture (MCRA) provides a security architecture blueprint, while the Microsoft Cloud Security Benchmark (MCSB) offers 12 control domains. Together, they map security services to real-world implementation.",
        "hook": "Need a security architecture but don't know where to start? Microsoft built two blueprints specifically for this. One shows the architecture, the other the controls.",
        "problem": "Organizations struggle to map security best practices to actual Azure services. They know WHAT to do but not HOW to implement it with Microsoft's tooling.",
        "explanation": "MCRA provides a reference architecture showing how Microsoft security services connect and interact. It maps the attack chain to specific services and their configurations. MCSB defines 12 security domains including identity management, network security, data protection, and incident response. Each domain maps to Azure services and configurations. Together, they provide both the architectural vision and the specific controls needed.",
        "real_world_example": "A government agency used MCRA to design their security architecture, mapping each control to Azure services. They implemented the 12 MCSB domains systematically: starting with identity (Entra ID), then network security (NSGs, Firewall), then data protection (Purview). Their security posture improved from reactive to proactive within one fiscal year.",
        "summary": "MCRA and MCSB are complementary blueprints. MCRA shows the security architecture; MCSB provides the control domains. Together, they give organizations a clear roadmap from architecture to implementation.",
        "curiosity_hook": "The MCSB maps directly to compliance standards like CIS, ISO 27001, and NIST. One framework, multiple compliance mappings.",
        "dialogue": [
            {"speaker": "Peter", "text": "I keep hearing about MCRA and MCSB. What's the difference?"},
            {"speaker": "Stewie", "text": "MCRA is the architecture blueprint. Shows how security services connect."},
            {"speaker": "Peter", "text": "And MCSB?"},
            {"speaker": "Stewie", "text": "Cloud Security Benchmark. Twelve domains of security controls you must implement."},
            {"speaker": "Peter", "text": "Twelve? That sounds like a lot of homework."},
            {"speaker": "Stewie", "text": "Identity management, network security, data protection, incident response, and more."},
            {"speaker": "Peter", "text": "So MCRA shows the big picture and MCSB gives you the checklist?"},
            {"speaker": "Stewie", "text": "Exactly. Architecture plus controls equals a complete security posture."},
            {"speaker": "Peter", "text": "Do they map to compliance standards?"},
            {"speaker": "Stewie", "text": "Yes. CIS, ISO 27001, NIST. MCSB covers multiple frameworks at once."},
            {"speaker": "Peter", "text": "So one benchmark to rule them all?"},
            {"speaker": "Stewie", "text": "In the Microsoft cloud world, yes. MCSB is that comprehensive."},
        ],
        "learning_objectives": [
            "Explain the purpose and scope of the Microsoft Cloud Reference Architecture (MCRA)",
            "Describe the 12 domains of the Microsoft Cloud Security Benchmark (MCSB)",
            "Explain how MCRA and MCSB complement each other for security implementation",
        ],
        "quiz_questions": [
            {
                "question": "What does the Microsoft Cloud Reference Architecture (MCRA) provide?",
                "answers": [
                    {"id": "a", "text": "A list of compliance standards for Azure", "correct": False},
                    {"id": "b", "text": "A security architecture blueprint showing how Microsoft security services connect", "correct": True},
                    {"id": "c", "text": "A cost optimization framework for cloud workloads", "correct": False},
                    {"id": "d", "text": "A migration planning tool for on-premises workloads", "correct": False},
                ],
            },
            {
                "question": "How many domains does the Microsoft Cloud Security Benchmark cover?",
                "answers": [
                    {"id": "a", "text": "5", "correct": False},
                    {"id": "b", "text": "7", "correct": False},
                    {"id": "c", "text": "12", "correct": True},
                    {"id": "d", "text": "20", "correct": False},
                ],
            },
            {
                "question": "Which compliance standards does MCSB map to?",
                "answers": [
                    {"id": "a", "text": "Only GDPR", "correct": False},
                    {"id": "b", "text": "CIS, ISO 27001, and NIST", "correct": True},
                    {"id": "c", "text": "Only PCI DSS", "correct": False},
                    {"id": "d", "text": "No external standards, it's Microsoft-only", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "cloud-frameworks",
        "title": "Microsoft Defender for Cloud",
        "slug": "sc100-defender-for-cloud",
        "description": "Microsoft Defender for Cloud combines Cloud Security Posture Management (CSPM) and Cloud Workload Protection Platform (CWPP) to secure your entire environment with secure score, attack path analysis, and multicloud support.",
        "hook": "You can't protect what you can't see. Defender for Cloud gives you a single pane of glass across your entire security posture, on Azure and beyond.",
        "problem": "Organizations use multiple security tools for different workloads. They lack a unified view of their security posture, leaving gaps between tools and blind spots across multicloud environments.",
        "explanation": "Defender for Cloud provides two core capabilities: CSPM for continuous posture assessment and CWPP for workload protection. Secure Score quantifies your security posture with actionable recommendations. Attack path analysis visualizes how attackers could reach critical assets. Defender plans cover servers, storage, databases, containers, and Key Vault. Multicloud support extends protection to AWS and GCP.",
        "real_world_example": "A media company running workloads across Azure and AWS used Defender for Cloud's multicloud support to unify their security dashboard. Secure Score revealed critical gaps in their storage configuration. Attack path analysis showed an attacker could reach their content database through a misconfigured storage account. They fixed the path in 48 hours, closing a gap that existed for 14 months undetected.",
        "summary": "Defender for Cloud is your unified security command center. CSPM, CWPP, secure score, and attack path analysis work across multicloud environments to provide comprehensive visibility and protection.",
        "curiosity_hook": "Defender for Cloud's attack path analysis uses graph-based modeling to simulate attack chains before they happen. It's like having a red team running 24/7.",
        "dialogue": [
            {"speaker": "Peter", "text": "What is Defender for Cloud? Is it just another antivirus?"},
            {"speaker": "Stewie", "text": "Way more than that. It's two things: posture management and workload protection."},
            {"speaker": "Peter", "text": "Posture management? Is my server supposed to do yoga?"},
            {"speaker": "Stewie", "text": "CSPM checks your cloud configuration continuously. Misconfigurations become visible."},
            {"speaker": "Peter", "text": "And workload protection?"},
            {"speaker": "Stewie", "text": "CWPP protects your actual workloads: servers, databases, containers, storage."},
            {"speaker": "Peter", "text": "What's the secure score I keep hearing about?"},
            {"speaker": "Stewie", "text": "It's a number from 0 to 100. Higher means better posture. It tracks your progress."},
            {"speaker": "Peter", "text": "Does it work with AWS and GCP too?"},
            {"speaker": "Stewie", "text": "Yes. Multicloud support means one dashboard for all your cloud environments."},
            {"speaker": "Peter", "text": "What about attack path analysis? That sounds intense."},
            {"speaker": "Stewie", "text": "It maps how an attacker could reach your critical assets. Visual, actionable, powerful."},
        ],
        "learning_objectives": [
            "Differentiate between CSPM and CWPP capabilities in Defender for Cloud",
            "Explain how secure score quantifies and tracks security posture",
            "Describe the multicloud support capabilities and Defender plans for different workload types",
        ],
        "quiz_questions": [
            {
                "question": "What are the two core capabilities of Microsoft Defender for Cloud?",
                "answers": [
                    {"id": "a", "text": "CSPM and CWPP", "correct": True},
                    {"id": "b", "text": "SIEM and SOAR", "correct": False},
                    {"id": "c", "text": "DLP and IRM", "correct": False},
                    {"id": "d", "text": "SSO and MFA", "correct": False},
                ],
            },
            {
                "question": "What does attack path analysis in Defender for Cloud do?",
                "answers": [
                    {"id": "a", "text": "It blocks all incoming network traffic automatically", "correct": False},
                    {"id": "b", "text": "It visualizes how an attacker could reach critical assets through misconfigurations", "correct": True},
                    {"id": "c", "text": "It encrypts all data at rest and in transit", "correct": False},
                    {"id": "d", "text": "It generates compliance reports for auditors", "correct": False},
                ],
            },
            {
                "question": "Which clouds does Defender for Cloud support beyond Azure?",
                "answers": [
                    {"id": "a", "text": "Only Azure, no other clouds", "correct": False},
                    {"id": "b", "text": "AWS and GCP", "correct": True},
                    {"id": "c", "text": "Only AWS", "correct": False},
                    {"id": "d", "text": "Oracle Cloud and IBM Cloud", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Business Continuity & Disaster Recovery",
        "slug": "sc100-bcdr-resilience",
        "description": "Business continuity and disaster recovery follows a three-phase approach: Protect, Detect, and Recover. Azure Site Recovery, Azure Backup, RPO/RTO targets, and availability zones ensure your organization survives any disaster, including ransomware.",
        "hook": "Your backups are only as good as your last test. When ransomware hits at 3 AM, you don't want to discover your recovery plan was theoretical.",
        "problem": "Organizations assume they're protected because they have 'backups' without testing recovery. They don't define RPO/RTO targets, don't test failover procedures, and discover gaps during actual disasters.",
        "explanation": "BCDR follows three phases: Protect (availability zones, redundancy), Detect (monitoring, alerts), and Recover (Azure Site Recovery for VMs, Azure Backup for data). RPO defines maximum data loss tolerance, RTO defines maximum downtime tolerance. Recovery Services Vault centralizes backup and recovery. Testing is critical: a plan untested is a plan that fails.",
        "real_world_example": "A European bank tested their BCDR plan quarterly. When a regional outage hit their primary datacenter, Azure Site Recovery failed over their critical systems in 12 minutes. Their RTO was 30 minutes. Because they had availability zones configured, zero data was lost. They were back fully operational before most customers even noticed.",
        "summary": "BCDR is not a one-time setup but a continuous cycle of protecting, detecting, and recovering. Regular testing, clear RPO/RTO targets, and Azure's native recovery tools ensure organizational resilience.",
        "curiosity_hook": "The average ransomware downtime is 24 days. Companies with tested BCDR plans recover in hours. The difference is preparation.",
        "dialogue": [
            {"speaker": "Peter", "text": "So BCDR. We just need backups, right? Problem solved?"},
            {"speaker": "Stewie", "text": "Backups are one piece. BCDR is three phases: protect, detect, recover."},
            {"speaker": "Peter", "text": "What do you mean by protect?"},
            {"speaker": "Stewie", "text": "Availability zones, redundancy, making sure your infrastructure survives a failure."},
            {"speaker": "Peter", "text": "And detect?"},
            {"speaker": "Stewie", "text": "Monitoring and alerts. You need to know something went wrong immediately."},
            {"speaker": "Peter", "text": "What about recover? That's the backup part?"},
            {"speaker": "Stewie", "text": "Azure Site Recovery for VMs, Azure Backup for data. Recovery Services Vault ties it together."},
            {"speaker": "Peter", "text": "What are RPO and RTO? More acronyms?"},
            {"speaker": "Stewie", "text": "RPO is max data you can lose. RTO is max time you can be down. Define them upfront."},
            {"speaker": "Peter", "text": "And testing? We tested once, years ago."},
            {"speaker": "Stewie", "text": "An untested plan is a wish. Test quarterly, or plan to fail when it matters most."},
        ],
        "learning_objectives": [
            "Describe the three phases of the BCDR approach: Protect, Detect, and Recover",
            "Explain RPO and RTO targets and why they must be defined before a disaster",
            "Identify Azure BCDR services: Site Recovery, Backup, and Recovery Services Vault",
        ],
        "quiz_questions": [
            {
                "question": "What are the three phases of the BCDR approach?",
                "answers": [
                    {"id": "a", "text": "Backup, Copy, Restore", "correct": False},
                    {"id": "b", "text": "Protect, Detect, Recover", "correct": True},
                    {"id": "c", "text": "Plan, Execute, Review", "correct": False},
                    {"id": "d", "text": "Monitor, Alert, Respond", "correct": False},
                ],
            },
            {
                "question": "What does RTO represent in disaster recovery?",
                "answers": [
                    {"id": "a", "text": "The maximum amount of data that can be lost", "correct": False},
                    {"id": "b", "text": "The maximum tolerable downtime before recovery", "correct": True},
                    {"id": "c", "text": "The total cost of a recovery operation", "correct": False},
                    {"id": "d", "text": "The number of recovery attempts allowed", "correct": False},
                ],
            },
            {
                "question": "What Azure service is used to protect virtual machines during a regional disaster?",
                "answers": [
                    {"id": "a", "text": "Azure Backup only", "correct": False},
                    {"id": "b", "text": "Azure Monitor", "correct": False},
                    {"id": "c", "text": "Azure Site Recovery", "correct": True},
                    {"id": "d", "text": "Azure Traffic Manager", "correct": False},
                ],
            },
        ],
    },
]
LESSONS = rewrite_lessons_dialogues(LESSONS)
