"""SC-100 Learning Path 4 lessons — grounded in the SC-100 training doc.

Covers gaps in existing SC-100 coverage:
  - LP2 Module 2.2 (identity): hybrid sync, multicloud federation, access control planes
  - LP2 Module 2.1 (compliance): AI compliance regulations
  - LP1 Module 4 (resilience): attack chain modeling, business resiliency, patch strategy
  - LP1 Module 3 (MCRA/MCSB): insider / external / supply chain defense

Each lesson uses the same schema as sc100_lp1/2/3_lessons.py so it seeds via
seed_lessons and renders via the video pipeline.
"""

from dialogue_rewriter import rewrite_lessons_dialogues


LESSONS = [
    {
        "concept_slug": "identity-access",
        "title": "Hybrid Identity: Cloud Sync vs Connect Sync",
        "slug": "sc100-hybrid-identity-sync",
        "description": "Choosing between Microsoft Entra Cloud Sync and Connect Sync, plus password hash sync, pass-through auth, and federation.",
        "hook": "Two sync tools, one directory, and a hard deadline. Pick wrong and your identities stop syncing on September 30, 2026.",
        "problem": "Organizations with on-premises Active Directory must sync identities to Microsoft Entra ID, but the wrong sync tool breaks password flows, device join, and resiliency.",
        "explanation": "Cloud Sync is the strategic direction: a lightweight, cloud-managed provisioning agent that handles multi-forest and disconnected forests, runs multiple active agents for high availability, supports on-demand provisioning, and syncs up to 150,000 objects per domain. Connect Sync is the on-premises application for pass-through auth, device sync for hybrid join, Microsoft Entra Domain Services integration, and over 150,000 objects. Authentication options are password hash sync (recommended, enables leaked credential detection and cloud resiliency), pass-through auth (passwords never leave on-premises, needs agents), and federation (smart cards, on-premises policy, most complexity). Seamless SSO uses Kerberos tickets for silent sign-in. Connect Sync must run version 2.5.79.0 or higher; all sync stops September 30, 2026 below that.",
        "real_world_example": "A company with two disconnected AD forests from an acquisition uses Cloud Sync with multiple agents to unify both into one Entra tenant without staging servers. A bank needing on-premises password validation uses Connect Sync with pass-through auth.",
        "summary": "Cloud Sync is the future for most hybrid identity; Connect Sync remains for pass-through auth, device sync, and large-scale needs. Pick authentication by resiliency and security requirements, not habit.",
        "curiosity_hook": "Password hash sync sounds like handing over your password database — but it only stores a one-way hash, and it's what lets Entra detect leaked credentials.",
        "dialogue": [
            {"speaker": "Peter", "text": "We have on-prem Active Directory. Can't we just... keep it?"},
            {"speaker": "Stewie", "text": "You keep it, Peter. But you sync it to Entra ID so cloud apps have one identity."},
            {"speaker": "Peter", "text": "And there are two sync tools? That seems excessive."},
            {"speaker": "Stewie", "text": "Cloud Sync is the modern one: lightweight agent, multi-forest support, easy high availability."},
            {"speaker": "Peter", "text": "So when do I ever need Connect Sync?"},
            {"speaker": "Stewie", "text": "Pass-through auth, device sync for hybrid join, Domain Services, or over 150,000 objects."},
            {"speaker": "Peter", "text": "Pass-through auth sounds safer. Passwords stay on-premises, right?"},
            {"speaker": "Stewie", "text": "True, but it needs agents online. Password hash sync gives you leaked-credential detection and cloud resiliency."},
            {"speaker": "Peter", "text": "And federation?"},
            {"speaker": "Stewie", "text": "Smart cards, on-premises policy. Also a whole extra server farm to keep alive."},
            {"speaker": "Peter", "text": "So what do most orgs pick?"},
            {"speaker": "Stewie", "text": "Password hash sync. Strongest cloud features, best resiliency. And check your Connect Sync version — old builds stop September 30, 2026."},
            {"speaker": "Peter", "text": "Any trick to make logins painless?"},
            {"speaker": "Stewie", "text": "Seamless SSO. Kerberos tickets sign users in silently on the corporate network."},
        ],
        "learning_objectives": [
            "Choose between Entra Cloud Sync and Connect Sync for a given scenario",
            "Compare password hash sync, pass-through auth, and federation tradeoffs",
            "Explain seamless SSO and the Connect Sync version deadline",
        ],
        "quiz_questions": [
            {
                "question": "Which capability requires Microsoft Entra Connect Sync rather than Cloud Sync?",
                "answers": [
                    {"id": "a", "text": "Multi-forest support", "correct": False},
                    {"id": "b", "text": "Pass-through authentication", "correct": True},
                    {"id": "c", "text": "On-demand provisioning", "correct": False},
                    {"id": "d", "text": "Multiple active agents", "correct": False},
                ],
            },
            {
                "question": "What happens to Connect Sync below version 2.5.79.0 after September 30, 2026?",
                "answers": [
                    {"id": "a", "text": "Nothing changes", "correct": False},
                    {"id": "b", "text": "Sync services stop working", "correct": True},
                    {"id": "c", "text": "It auto-upgrades", "correct": False},
                    {"id": "d", "text": "It requires federation", "correct": False},
                ],
            },
            {
                "question": "Why is password hash synchronization recommended for most organizations?",
                "answers": [
                    {"id": "a", "text": "It stores plaintext passwords in the cloud", "correct": False},
                    {"id": "b", "text": "It enables leaked-credential detection and cloud resiliency", "correct": True},
                    {"id": "c", "text": "It removes the need for any on-premises directory", "correct": False},
                    {"id": "d", "text": "It only works with federation servers", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "identity-access",
        "title": "Federating Identity Across Multicloud",
        "slug": "sc100-multicloud-federation",
        "description": "Making Microsoft Entra ID the identity provider for AWS and GCP with federation, SCIM provisioning, and workload identity federation.",
        "hook": "Your developers hold credentials for three clouds and none of them talk to each other. That's how cloud sprawl becomes a security hole.",
        "problem": "Organizations using Azure, AWS, and GCP end up with separate identities per cloud, duplicate accounts, and no consistent authentication policy or lifecycle management.",
        "explanation": "The solution is to make Microsoft Entra ID the central identity provider. For AWS, federate through AWS IAM Identity Center: users sign in with Entra, groups provision automatically via SCIM, Conditional Access evaluates every AWS sign-in, and Entra group memberships map to AWS IAM roles. For GCP, use workforce identity federation so Google trusts Entra as an external identity provider and users access GCP with existing credentials and no separate Google accounts. For workloads running outside Azure, workload identity federation lets a workload exchange its native cloud token for a Microsoft Entra access token without storing secrets. Conditional Access then applies consistent policies — MFA, device compliance, user risk — regardless of which cloud hosts the resource. Monitor cross-cloud permissions with Defender for Cloud to find overprovisioned identities.",
        "real_world_example": "A startup uses AWS for data pipelines and Azure for core services. With IAM Identity Center federated to Entra, a user who leaves the company loses AWS access the moment their Entra account is disabled — no orphaned AWS users.",
        "summary": "Centralize identity in Entra, federate AWS and GCP as service providers, use workload identity federation for non-Azure workloads, and let Conditional Access govern every sign-in across clouds.",
        "curiosity_hook": "Workload identity federation means a GitHub Action or a Kubernetes pod on AWS can get an Azure token without storing a single secret.",
        "dialogue": [
            {"speaker": "Peter", "text": "We run Azure, AWS, and GCP. That's three logins per person?"},
            {"speaker": "Stewie", "text": "Only if you're doing identity wrong. One identity provider should rule them all."},
            {"speaker": "Peter", "text": "And that provider is...?"},
            {"speaker": "Stewie", "text": "Microsoft Entra ID. AWS and GCP become service providers that trust it."},
            {"speaker": "Peter", "text": "How does AWS work?"},
            {"speaker": "Stewie", "text": "AWS IAM Identity Center. Entra signs users in, SCIM provisions groups, and group membership maps to IAM roles."},
            {"speaker": "Peter", "text": "Conditional Access still applies on AWS?"},
            {"speaker": "Stewie", "text": "Yes. Every AWS sign-in gets MFA, device checks, and risk evaluation from Entra."},
            {"speaker": "Peter", "text": "What about GCP?"},
            {"speaker": "Stewie", "text": "Workforce identity federation. Google trusts Entra, so users bring their existing credentials. No duplicate accounts."},
            {"speaker": "Peter", "text": "And machines running on AWS that need Azure resources?"},
            {"speaker": "Stewie", "text": "Workload identity federation. They swap their native token for an Azure token. No stored secrets to leak."},
            {"speaker": "Peter", "text": "So nobody gets orphaned cloud accounts?"},
            {"speaker": "Stewie", "text": "Exactly. Fire the user in Entra and every cloud loses access instantly."},
            {"speaker": "Peter", "text": "How do we spot over-permissioned cloud roles?"},
            {"speaker": "Stewie", "text": "Defender for Cloud. It monitors cross-cloud permissions and flags identities that can do too much."},
        ],
        "learning_objectives": [
            "Design Microsoft Entra ID as the central identity provider across AWS and GCP",
            "Explain IAM Identity Center, SCIM provisioning, and group-to-role mapping",
            "Use workload identity federation to avoid stored secrets for non-Azure workloads",
        ],
        "quiz_questions": [
            {
                "question": "How does AWS get user identities from Microsoft Entra ID automatically?",
                "answers": [
                    {"id": "a", "text": "Manual CSV uploads", "correct": False},
                    {"id": "b", "text": "SCIM-based lifecycle management through IAM Identity Center", "correct": True},
                    {"id": "c", "text": "Direct database replication", "correct": False},
                    {"id": "d", "text": "Shared password vaults", "correct": False},
                ],
            },
            {
                "question": "What does workload identity federation enable for a workload on AWS needing Azure resources?",
                "answers": [
                    {"id": "a", "text": "Storing Azure keys in the codebase", "correct": False},
                    {"id": "b", "text": "Exchanging its native token for an Entra access token without stored secrets", "correct": True},
                    {"id": "c", "text": "Bypassing authentication entirely", "correct": False},
                    {"id": "d", "text": "Creating duplicate Google accounts", "correct": False},
                ],
            },
            {
                "question": "Which GCP capability lets Entra users access GCP with existing credentials?",
                "answers": [
                    {"id": "a", "text": "GCP VPN gateway", "correct": False},
                    {"id": "b", "text": "Workforce identity federation", "correct": True},
                    {"id": "c", "text": "Cloud NAT", "correct": False},
                    {"id": "d", "text": "GCP IAP alone", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "identity-access",
        "title": "Securing Access Across SaaS, PaaS, IaaS",
        "slug": "sc100-access-control-planes",
        "description": "Coordinating identity, network, and application controls to secure access to SaaS, PaaS, IaaS, hybrid, and multicloud resources.",
        "hook": "Every deployment model needs its own mix of controls. Treat them all the same and you'll leave a door open somewhere.",
        "problem": "Access strategies differ by deployment model, and teams often secure identity without the matching network and application controls — or vice versa.",
        "explanation": "Access security spans three control planes. Identity controls: SSO with SAML and OIDC, RBAC at the narrowest scope, Privileged Identity Management for just-in-time admin, and Conditional Access evaluating user risk, device compliance, and location. Workload identity uses managed identities and workload identity federation to avoid stored secrets. Networking controls: Microsoft Entra Internet Access acts as a Secure Web Gateway with content filtering and tenant restrictions; Microsoft Entra Private Access delivers Zero Trust Network Access per-app instead of a broad VPN; Azure Private Link and private endpoints keep PaaS traffic on the Microsoft backbone; NSGs and Azure Firewall control IaaS traffic. Application controls: Microsoft Defender for Cloud Apps provides CASB discovery and session controls that restrict downloads and copy/paste; Application Proxy secures legacy on-prem web apps with MFA; app consent policies block users from granting high-privilege permissions. Multicloud means Entra stays the central IdP with Conditional Access enforcing MFA and risk checks on every sign-in.",
        "real_world_example": "An accounting firm replaces its full-tunnel VPN with Entra Private Access: users reach only the finance app they need, Conditional Access demands device compliance, and Defender for Cloud Apps blocks file uploads to unsanctioned SaaS apps.",
        "summary": "Design access per deployment model using three planes together: identity (SSO, RBAC, PIM, Conditional Access), network (SWG, ZTNA, Private Link, NSG), and application (CASB, Application Proxy, consent policies).",
        "curiosity_hook": "A CASB can let a user open a cloud app but block every download — session-level control without changing the app at all.",
        "dialogue": [
            {"speaker": "Peter", "text": "We've got SaaS apps, Azure services, and old on-prem apps. One security plan for all?"},
            {"speaker": "Stewie", "text": "One strategy, three control planes: identity, network, and application."},
            {"speaker": "Peter", "text": "Start with identity."},
            {"speaker": "Stewie", "text": "SSO for SaaS, RBAC for Azure at the narrowest scope, PIM for admin, Conditional Access for risky sign-ins."},
            {"speaker": "Peter", "text": "And machines calling machines?"},
            {"speaker": "Stewie", "text": "Managed identities and workload identity federation. No passwords lying around."},
            {"speaker": "Peter", "text": "Now the network plane."},
            {"speaker": "Stewie", "text": "Internet Access is a secure web gateway. Private Access is Zero Trust per-app access instead of a fat VPN."},
            {"speaker": "Peter", "text": "So users don't get the whole network?"},
            {"speaker": "Stewie", "text": "Correct. Just the apps they need. Private Link keeps PaaS traffic off the public internet too."},
            {"speaker": "Peter", "text": "What about application-level control?"},
            {"speaker": "Stewie", "text": "Defender for Cloud Apps. Shadow IT discovery, session controls, block risky uploads."},
            {"speaker": "Peter", "text": "Legacy on-prem web apps?"},
            {"speaker": "Stewie", "text": "Application Proxy. MFA and device checks without rewriting the app."},
            {"speaker": "Peter", "text": "And app permissions?"},
            {"speaker": "Stewie", "text": "Consent policies. High-privilege permissions require admin approval, not a user checkbox."},
        ],
        "learning_objectives": [
            "Map identity, network, and application controls to SaaS, PaaS, IaaS, and hybrid models",
            "Use Entra Internet Access and Private Access for SWG and ZTNA",
            "Apply Defender for Cloud Apps and Application Proxy as application-layer controls",
        ],
        "quiz_questions": [
            {
                "question": "Which service replaces a traditional VPN with per-application Zero Trust access?",
                "answers": [
                    {"id": "a", "text": "Microsoft Entra Private Access", "correct": True},
                    {"id": "b", "text": "Azure ExpressRoute", "correct": False},
                    {"id": "c", "text": "Microsoft Entra Internet Access", "correct": False},
                    {"id": "d", "text": "Azure Load Balancer", "correct": False},
                ],
            },
            {
                "question": "What does a CASB like Microsoft Defender for Cloud Apps provide for SaaS?",
                "answers": [
                    {"id": "a", "text": "Physical access controls", "correct": False},
                    {"id": "b", "text": "Shadow IT discovery and session controls", "correct": True},
                    {"id": "c", "text": "DNS server management", "correct": False},
                    {"id": "d", "text": "Database encryption", "correct": False},
                ],
            },
            {
                "question": "How should app consent be governed in Microsoft Entra ID?",
                "answers": [
                    {"id": "a", "text": "Let users consent to everything", "correct": False},
                    {"id": "b", "text": "Require admin consent for high-privilege permissions", "correct": True},
                    {"id": "c", "text": "Disable all apps", "correct": False},
                    {"id": "d", "text": "Ignore consent entirely", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "compliance",
        "title": "AI Compliance: EU AI Act & ISO 42001",
        "slug": "sc100-ai-compliance-regulations",
        "description": "How AI changes compliance — EU AI Act, ISO/IEC 42001, NIST AI RMF — and the controls architects must design.",
        "hook": "Your AI can answer customers, but can it prove it followed the law? Regulators are starting to ask.",
        "problem": "AI systems produce probabilistic, opaque outputs and depend on training data, so traditional compliance frameworks don't fully cover them, and AI-specific regulations are emerging globally.",
        "explanation": "AI breaks the usual compliance assumptions in four ways: probabilistic outputs vary for similar inputs, training data carries biases and privacy risk, opaque models are hard to explain, and systems evolve over time. Key frameworks: the EU AI Act (risk-based classification, transparency obligations, conformity assessments for high-risk AI), ISO/IEC 42001:2023 (AI management system covering governance, risk, and improvement), NIST AI RMF 1.0, and ISO/IEC 23894 (AI risk management guidance). Design considerations: protect training data and respect data subject rights, document model purpose and limitations, keep audit trails of inputs and outputs, require human oversight for high-risk decisions, and add content-safety guardrails. Microsoft tools: Purview Compliance Manager has templates for EU AI Act, ISO 42001, and NIST AI RMF; Defender for Cloud Apps assesses AI apps by risk; Azure AI Content Safety filters harmful content. Microsoft 365 Copilot holds ISO/IEC 42001 certification, and Transparency Notes document AI capabilities and limits.",
        "real_world_example": "A healthcare insurer deploying AI must show conformity for high-risk use. It runs Purview Compliance Manager against the EU AI Act, documents training data lineage, keeps an audit trail of every inference, and routes high-risk decisions to human review.",
        "summary": "AI compliance means documenting model purpose and data, explaining decisions, keeping human oversight, adding content guardrails, and mapping controls to EU AI Act, ISO 42001, and NIST AI RMF.",
        "curiosity_hook": "ISO/IEC 42001 is a management-system standard — the same family as ISO 27001, but for AI. Microsoft 365 Copilot is already certified against it.",
        "dialogue": [
            {"speaker": "Peter", "text": "We're rolling out AI features. Compliance still applies to AI?"},
            {"speaker": "Stewie", "text": "More than ever. And AI breaks the usual compliance assumptions."},
            {"speaker": "Peter", "text": "How?"},
            {"speaker": "Stewie", "text": "Outputs are probabilistic, training data carries bias, models are opaque, and they keep evolving."},
            {"speaker": "Peter", "text": "So which regulations actually exist?"},
            {"speaker": "Stewie", "text": "EU AI Act, ISO 42001 for AI management systems, NIST AI RMF, ISO 23894."},
            {"speaker": "Peter", "text": "What does the EU AI Act demand?"},
            {"speaker": "Stewie", "text": "Risk-based classification, transparency obligations, and conformity assessments for high-risk AI."},
            {"speaker": "Peter", "text": "What do I need to document?"},
            {"speaker": "Stewie", "text": "Model purpose, capabilities, limitations, training data, and decisions that affect people."},
            {"speaker": "Peter", "text": "Human oversight required?"},
            {"speaker": "Stewie", "text": "For high-risk decisions, yes. And audit trails of inputs and outputs."},
            {"speaker": "Peter", "text": "How do we keep AI from going rogue?"},
            {"speaker": "Stewie", "text": "Content-safety guardrails and controls against misleading or harmful output."},
            {"speaker": "Peter", "text": "What tools help prove compliance?"},
            {"speaker": "Stewie", "text": "Purview Compliance Manager has AI templates. Defender for Cloud Apps assesses AI app risk."},
            {"speaker": "Peter", "text": "Does Microsoft walk the talk?"},
            {"speaker": "Stewie", "text": "M365 Copilot is ISO 42001 certified, and they publish Transparency Notes for every AI service."},
        ],
        "learning_objectives": [
            "Explain why AI creates unique compliance challenges",
            "Compare EU AI Act, ISO/IEC 42001, and NIST AI RMF requirements",
            "Design documentation, human oversight, and content-safety controls for AI",
        ],
        "quiz_questions": [
            {
                "question": "Which characteristic of AI creates unique compliance challenges?",
                "answers": [
                    {"id": "a", "text": "Deterministic identical outputs", "correct": False},
                    {"id": "b", "text": "Probabilistic outputs that vary for similar inputs", "correct": True},
                    {"id": "c", "text": "No data dependencies", "correct": False},
                    {"id": "d", "text": "Fully transparent decision logic", "correct": False},
                ],
            },
            {
                "question": "Which standard is an AI management system standard in the ISO 27001 family?",
                "answers": [
                    {"id": "a", "text": "ISO/IEC 42001:2023", "correct": True},
                    {"id": "b", "text": "PCI-DSS v4", "correct": False},
                    {"id": "c", "text": "SOC 2 Type II", "correct": False},
                    {"id": "d", "text": "CIS Controls v8.1", "correct": False},
                ],
            },
            {
                "question": "What Microsoft tool provides compliance templates for the EU AI Act and ISO 42001?",
                "answers": [
                    {"id": "a", "text": "Microsoft Purview Compliance Manager", "correct": True},
                    {"id": "b", "text": "Azure Load Balancer", "correct": False},
                    {"id": "c", "text": "Microsoft Entra Private Access", "correct": False},
                    {"id": "d", "text": "Azure Key Vault", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Attack Chains: Kill Chain & PETE",
        "slug": "sc100-attack-chain-modeling",
        "description": "Modeling attacks with MITRE ATT&CK, the Lockheed Martin Cyber Kill Chain, and Microsoft's PETE model — plus AI-specific threats.",
        "hook": "Most attacks follow the same script. Learn the script and you can interrupt it before the finale.",
        "problem": "Security teams chase individual alerts without understanding the sequence of an attack, missing the chance to break the chain at its earliest stage.",
        "explanation": "Attack chain frameworks model the sequence of an attack so defenders can interrupt it. MITRE ATT&CK is the most widely adopted framework for detailed control planning, cataloging tactics and techniques (TTPs). The Lockheed Martin Cyber Kill Chain defines sequential phases: reconnaissance, weaponization, delivery, exploitation, installation, command and control, and actions on objectives. Microsoft's PETE model simplifies this to Prepare, Enter, Traverse, and Execute. For AI systems, MITRE ATLAS provides adversarial tactics and techniques, including prompt injection (direct and indirect), model and data poisoning, jailbreaking, adversarial perturbation, model theft and inversion, and training data exfiltration. Common attack vectors include email, removable media, browser exploits, cloud services, insiders, and AI systems themselves. Recognizing these patterns lets architects design controls that stop attacks at each phase and detect adversaries who get past prevention.",
        "real_world_example": "A SOC maps a phishing campaign to the Kill Chain: it blocks the delivery stage with email filtering, detects the installation stage with EDR, and stops command-and-control with network egress controls — interrupting the attack at three different phases.",
        "summary": "Model attacks as chains — MITRE ATT&CK for detail, Cyber Kill Chain or PETE for the sequence — and design controls to interrupt every phase, including AI-specific threats from MITRE ATLAS.",
        "curiosity_hook": "The Cyber Kill Chain was born from military fighter-pilot doctrine — kill the enemy before the weapons reach you.",
        "dialogue": [
            {"speaker": "Peter", "text": "Why do we need yet another framework to understand attacks?"},
            {"speaker": "Stewie", "text": "Because attacks follow a sequence. Disrupt the sequence early and the attack dies."},
            {"speaker": "Peter", "text": "What are the options?"},
            {"speaker": "Stewie", "text": "MITRE ATT&CK for detail, the Cyber Kill Chain for the classic sequence, PETE as the simplified version."},
            {"speaker": "Peter", "text": "Give me the Kill Chain phases."},
            {"speaker": "Stewie", "text": "Recon, weaponization, delivery, exploitation, installation, command and control, actions on objectives."},
            {"speaker": "Peter", "text": "And PETE?"},
            {"speaker": "Stewie", "text": "Prepare, Enter, Traverse, Execute. Microsoft's stripped-down take."},
            {"speaker": "Peter", "text": "Where does AI fit in?"},
            {"speaker": "Stewie", "text": "MITRE ATLAS. Prompt injection, model poisoning, jailbreaking, data exfiltration."},
            {"speaker": "Peter", "text": "So attackers follow a script?"},
            {"speaker": "Stewie", "text": "Mostly. Variation comes from entry points and goals. The patterns repeat."},
            {"speaker": "Peter", "text": "How do I use this as an architect?"},
            {"speaker": "Stewie", "text": "Design a control for every phase. Kill the chain at delivery, at installation, and at command and control."},
            {"speaker": "Peter", "text": "So one big firewall is not enough?"},
            {"speaker": "Stewie", "text": "Never was. You need layered stops along the whole path."},
        ],
        "learning_objectives": [
            "Compare MITRE ATT&CK, the Cyber Kill Chain, and the PETE model",
            "Map defense controls to attack chain phases",
            "Identify AI-specific threats from MITRE ATLAS",
        ],
        "quiz_questions": [
            {
                "question": "Which framework defines phases like reconnaissance, weaponization, and delivery?",
                "answers": [
                    {"id": "a", "text": "Lockheed Martin Cyber Kill Chain", "correct": True},
                    {"id": "b", "text": "FAIR model", "correct": False},
                    {"id": "c", "text": "CIS Controls", "correct": False},
                    {"id": "d", "text": "STRIDE", "correct": False},
                ],
            },
            {
                "question": "What do the letters in Microsoft's PETE model stand for?",
                "answers": [
                    {"id": "a", "text": "Plan, Execute, Test, End", "correct": False},
                    {"id": "b", "text": "Prepare, Enter, Traverse, Execute", "correct": True},
                    {"id": "c", "text": "Patch, Encrypt, Test, Exit", "correct": False},
                    {"id": "d", "text": "Probe, Exploit, Take, Exfiltrate", "correct": False},
                ],
            },
            {
                "question": "Which framework catalogs adversarial techniques specific to AI systems?",
                "answers": [
                    {"id": "a", "text": "MITRE ATLAS", "correct": True},
                    {"id": "b", "text": "MITRE ATT&CK for ICS", "correct": False},
                    {"id": "c", "text": "OWASP API Top 10", "correct": False},
                    {"id": "d", "text": "NIST SP 800-53", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Business Resiliency & Critical Assets",
        "slug": "sc100-business-resiliency-planning",
        "description": "Planning resilience around business-critical assets, RTO and RPO, and the before-during-after incident cycle.",
        "hook": "You can't be perfect on security. You can be resilient — and resilience starts with knowing which systems would end the business if lost.",
        "problem": "Organizations treat all systems equally in disaster planning, so when an incident hits, the truly critical systems lack the fastest recovery paths.",
        "explanation": "Resilience is the ability to keep business operations going before, during, and after security incidents. The cycle: continuously improve posture and response before an incident; during an incident protect people and stop damage while keeping critical functions working; after an incident restore full operations immediately, even if it means restoring without lost data; then feed lessons back to block, detect, and recover better. Identify business-critical assets in five priority categories: identity systems (Active Directory, Entra Connect, domain controllers), human life systems (medical and safety systems), financial systems (payments, reporting databases), product or service enablement (factory and delivery systems), and security systems (minimum monitoring to prevent reattack). Classify each asset by criticality — Very High, High, Medium, Low — and define RTO (Recovery Time Objective) and RPO (Recovery Point Objective) for each. Assume breach to drive preparation: education, exercises, and incident drills. For AI, map dependencies between AI systems and business processes and validate model integrity after restoration.",
        "real_world_example": "A manufacturer ranks its factory control systems as Very High with a two-hour RTO. When ransomware hits, recovery drills mean operators restore those systems first from immutable backups while lower-priority systems wait.",
        "summary": "Prioritize the five critical asset categories, set RTO and RPO per asset, run the before-during-after resilience cycle, and validate AI dependencies as part of recovery.",
        "curiosity_hook": "Identity systems top the priority list for a reason — if Active Directory is down, no one can get into any other system to fix anything.",
        "dialogue": [
            {"speaker": "Peter", "text": "Perfect security is impossible, right?"},
            {"speaker": "Stewie", "text": "Correct. So we design for resilience instead — keep the business running through an attack."},
            {"speaker": "Peter", "text": "Where do I start?"},
            {"speaker": "Stewie", "text": "Identify business-critical assets. Not all systems are created equal."},
            {"speaker": "Peter", "text": "What tops the list?"},
            {"speaker": "Stewie", "text": "Identity systems first. Then human life systems, financial systems, product enablement, and security monitoring."},
            {"speaker": "Peter", "text": "Why identity first?"},
            {"speaker": "Stewie", "text": "Domain controllers and Entra Connect gate access to everything else. Lose them and nobody can log in to fix anything."},
            {"speaker": "Peter", "text": "Then what?"},
            {"speaker": "Stewie", "text": "Set RTO and RPO for each critical asset. How fast to recover, and how much data you can lose."},
            {"speaker": "Peter", "text": "Before, during, and after an incident?"},
            {"speaker": "Stewie", "text": "Prepare before, protect people and stop damage during, restore operations after — even if data is lost."},
            {"speaker": "Peter", "text": "And when it's over?"},
            {"speaker": "Stewie", "text": "Feed lessons back. Block better, detect better, recover better. That's the loop."},
            {"speaker": "Peter", "text": "Does AI change the plan?"},
            {"speaker": "Stewie", "text": "Yes. Map AI dependencies on business processes and validate model integrity after any restore."},
        ],
        "learning_objectives": [
            "Identify business-critical assets across five priority categories",
            "Define RTO and RPO for critical assets",
            "Apply the before-during-after resilience cycle and assume-breach preparation",
        ],
        "quiz_questions": [
            {
                "question": "Which asset category should be prioritized first in BCDR planning?",
                "answers": [
                    {"id": "a", "text": "Identity systems", "correct": True},
                    {"id": "b", "text": "Marketing websites", "correct": False},
                    {"id": "c", "text": "Dev test environments", "correct": False},
                    {"id": "d", "text": "Printers", "correct": False},
                ],
            },
            {
                "question": "What does RPO measure?",
                "answers": [
                    {"id": "a", "text": "How fast recovery must happen", "correct": False},
                    {"id": "b", "text": "How much data loss is acceptable", "correct": True},
                    {"id": "c", "text": "How many users are affected", "correct": False},
                    {"id": "d", "text": "How long backups are kept", "correct": False},
                ],
            },
            {
                "question": "What is the correct priority order for critical asset categories?",
                "answers": [
                    {"id": "a", "text": "Financial, identity, human life, security", "correct": False},
                    {"id": "b", "text": "Identity, human life, financial, product enablement, security", "correct": True},
                    {"id": "c", "text": "Security, financial, identity, human life", "correct": False},
                    {"id": "d", "text": "Product enablement, security, identity, financial", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "security-operations",
        "title": "Insider, External & Supply Chain Defense",
        "slug": "sc100-insider-supply-chain-defense",
        "description": "Designing layered defenses for the three attack origins: insiders, external actors, and compromised supply chains.",
        "hook": "Three different attackers, three different playbooks. Blur them together and one of them will slip through.",
        "problem": "Organizations often build one generic defense, but insider threats, external attacks, and supply chain compromises exploit different weaknesses and need different controls.",
        "explanation": "Insider threats come from people with legitimate access who cause harm intentionally or accidentally. Controls include least privilege (MCSB PA-1, PA-7, IM-2), user behavior analytics with UEBA (LT-1, LT-2), data classification, DLP, and encryption (DP-1, DP-2, DP-3), and separation of duties (PA-1, PA-4). External attacks come from outside actors. Controls include layered preventive and detective defenses (NS-1, ES-1, LT-1), integrating XDR with SIEM (LT-1, LT-5, IR-3), automated response with SOAR (IR-6, IR-4), and documented, tested incident response (IR-1, IR-2, IR-7). Supply chain attacks compromise trusted vendors, software, or services. Controls include verifying software integrity with code signing and SBOMs (DS-2, DS-6), assessing third-party risk before onboarding (AM-2, PA-3), granting third parties least privilege (PA-6, PA-8, IM-7), and isolating integrations with network segmentation (NS-1, NS-2). Common threads: assume breach, monitor continuously across identity, network, endpoint, and data, and automate containment with tested response.",
        "real_world_example": "A vendor's software update is signed but an attacker swaps the package downstream. SBOM review and code-signature verification catch the tampered build before it reaches production, and segmentation keeps the vendor's integration from reaching core systems.",
        "summary": "Use least privilege, UEBA, DLP, and separation of duties for insiders; layered defenses, XDR plus SIEM, and SOAR for external attacks; code signing, SBOMs, third-party risk review, and segmentation for supply chains.",
        "curiosity_hook": "An SBOM is a software bill of materials — the ingredient list for your software. Attackers don't like it when you check ingredients.",
        "dialogue": [
            {"speaker": "Peter", "text": "Three kinds of attackers? Isn't a hacker a hacker?"},
            {"speaker": "Stewie", "text": "Insiders, external actors, and supply chains. Different origins, different controls."},
            {"speaker": "Peter", "text": "Insiders first. They already have access, right?"},
            {"speaker": "Stewie", "text": "Yes. Least privilege, UEBA to spot odd behavior, DLP on sensitive data, separation of duties."},
            {"speaker": "Peter", "text": "External attackers?"},
            {"speaker": "Stewie", "text": "Layered defenses, XDR feeding a SIEM, SOAR to automate response, and tested incident plans."},
            {"speaker": "Peter", "text": "What makes supply chain attacks different?"},
            {"speaker": "Stewie", "text": "You're trusting someone else's code. Verify with code signing and SBOMs, assess vendors before onboarding."},
            {"speaker": "Peter", "text": "Do third parties get full access?"},
            {"speaker": "Stewie", "text": "Least privilege only, and isolate their integrations with segmentation."},
            {"speaker": "Peter", "text": "What's the common thread across all three?"},
            {"speaker": "Stewie", "text": "Assume breach, monitor continuously, and automate containment with tested response."},
            {"speaker": "Peter", "text": "Assume breach again. It keeps coming up."},
            {"speaker": "Stewie", "text": "Because prevention eventually fails. Design so the damage stays small when it does."},
            {"speaker": "Peter", "text": "So I need all three playbooks written down?"},
            {"speaker": "Stewie", "text": "Documented and drilled. A plan nobody tested is just a document."},
        ],
        "learning_objectives": [
            "Design least privilege, UEBA, DLP, and separation of duties for insider threats",
            "Apply layered defense, XDR, SIEM, and SOAR for external attacks",
            "Use code signing, SBOMs, third-party risk review, and segmentation for supply chains",
        ],
        "quiz_questions": [
            {
                "question": "Which control is most directly aimed at insider threats?",
                "answers": [
                    {"id": "a", "text": "User behavior analytics (UEBA)", "correct": True},
                    {"id": "b", "text": "DDoS protection", "correct": False},
                    {"id": "c", "text": "WAF rules", "correct": False},
                    {"id": "d", "text": "BGP filtering", "correct": False},
                ],
            },
            {
                "question": "What two techniques verify software integrity against supply chain tampering?",
                "answers": [
                    {"id": "a", "text": "Code signing and SBOMs", "correct": True},
                    {"id": "b", "text": "Port scanning and ping sweeps", "correct": False},
                    {"id": "c", "text": "Password spraying and brute force", "correct": False},
                    {"id": "d", "text": "DNS rebinding and cache poisoning", "correct": False},
                ],
            },
            {
                "question": "What is the recommended access level for third-party vendors?",
                "answers": [
                    {"id": "a", "text": "Full administrative access", "correct": False},
                    {"id": "b", "text": "Least privilege with isolated integrations", "correct": True},
                    {"id": "c", "text": "No access controls", "correct": False},
                    {"id": "d", "text": "Shared global admin", "correct": False},
                ],
            },
        ],
    },
    {
        "concept_slug": "resilience",
        "title": "Security Update & Patch Management Strategy",
        "slug": "sc100-patch-management-strategy",
        "description": "A patch management strategy across VMs, on-premises servers, and multicloud — discovery, prioritization, deployment, and verification.",
        "hook": "Unpatched is not a vulnerability — it's a schedule. Attackers read the same CVE list you do.",
        "problem": "Organizations patch inconsistently, prioritize by noise instead of risk, and have no unified view across Azure, on-premises, and other clouds.",
        "explanation": "A comprehensive update strategy has four key areas. Discovery and assessment: continuously inventory every machine and assess update status. Prioritization: rank by severity, exploitability, and asset criticality, aligned with CVSS. Deployment: a controlled process with maintenance windows, staged rollouts, and rollback plans. Verification and reporting: confirm success, validate functionality, and report. Key capabilities to evaluate include flexible patching options (on-demand and scheduled with custom maintenance windows), unified update assessment across all machines, and governance with policy integration, built-in reporting, and query-based dashboards. Approaches: Azure Update Manager for cloud VMs; Azure Update Manager plus Azure Arc for hybrid and multicloud; WSUS and Configuration Manager for legacy Windows; or third-party tools for existing investments. Integration with CSPM: Defender for Cloud periodically checks for missing updates and surfaces critical and security patches as security recommendations. For AI, patch ML frameworks and model-serving runtimes, update base images, and prioritize updates that affect inference performance.",
        "real_world_example": "A hybrid shop uses Azure Update Manager with Arc to see all servers in one dashboard. Critical internet-facing servers patch in a midnight window with staged rollout; when a patch breaks an app, the rollback plan restores service in minutes.",
        "summary": "Build patching on four pillars — discovery, prioritization by CVSS and asset criticality, staged deployment with rollback, and verification — with a unified tool across hybrid and multicloud.",
        "curiosity_hook": "The easiest way to exploit a system is still a known, patchable CVE. Basic patch hygiene stops the majority of attacks.",
        "dialogue": [
            {"speaker": "Peter", "text": "Patching. The most boring security topic, right?"},
            {"speaker": "Stewie", "text": "And the most exploited. Known CVEs are the attacker's favorite front door."},
            {"speaker": "Peter", "text": "So what's the strategy?"},
            {"speaker": "Stewie", "text": "Four parts: discovery, prioritization, deployment, verification."},
            {"speaker": "Peter", "text": "Discovery first?"},
            {"speaker": "Stewie", "text": "You can't patch what you haven't inventoried. Continuously assess every machine's update status."},
            {"speaker": "Peter", "text": "How do I prioritize?"},
            {"speaker": "Stewie", "text": "Severity, exploitability, and asset criticality. CVSS helps, but context matters more."},
            {"speaker": "Peter", "text": "Deployment?"},
            {"speaker": "Stewie", "text": "Maintenance windows, staged rollout, and a rollback plan. Never patch everything at once."},
            {"speaker": "Peter", "text": "And after?"},
            {"speaker": "Stewie", "text": "Verify it worked and nothing broke. Then report."},
            {"speaker": "Peter", "text": "We've got Azure, on-prem, and AWS servers."},
            {"speaker": "Stewie", "text": "Azure Update Manager plus Arc for a unified view. WSUS for legacy Windows if needed."},
            {"speaker": "Peter", "text": "How do I find what's missing?"},
            {"speaker": "Stewie", "text": "Defender for Cloud checks for missing patches and surfaces them as security recommendations."},
            {"speaker": "Peter", "text": "Anything special for AI?"},
            {"speaker": "Stewie", "text": "Patch ML frameworks, base images, and model-serving runtimes too."},
        ],
        "learning_objectives": [
            "Apply discovery, prioritization, deployment, and verification to patch management",
            "Choose update tools for cloud, hybrid, multicloud, and legacy environments",
            "Integrate patch posture with Defender for Cloud and plan AI workload patching",
        ],
        "quiz_questions": [
            {
                "question": "Which of these is NOT one of the four key patch management areas?",
                "answers": [
                    {"id": "a", "text": "Discovery and assessment", "correct": False},
                    {"id": "b", "text": "Prioritization", "correct": False},
                    {"id": "c", "text": "Social media monitoring", "correct": True},
                    {"id": "d", "text": "Verification and reporting", "correct": False},
                ],
            },
            {
                "question": "What should guide patch prioritization?",
                "answers": [
                    {"id": "a", "text": "Severity, exploitability, and asset criticality", "correct": True},
                    {"id": "b", "text": "Alphabetical order", "correct": False},
                    {"id": "c", "text": "Patch file size", "correct": False},
                    {"id": "d", "text": "Release date only", "correct": False},
                ],
            },
            {
                "question": "Which Microsoft solution provides unified patch management for hybrid and multicloud?",
                "answers": [
                    {"id": "a", "text": "Azure Update Manager with Azure Arc", "correct": True},
                    {"id": "b", "text": "Azure DevOps pipelines alone", "correct": False},
                    {"id": "c", "text": "Microsoft Entra Conditional Access", "correct": False},
                    {"id": "d", "text": "Azure Front Door", "correct": False},
                ],
            },
        ],
    },
]
LESSONS = rewrite_lessons_dialogues(LESSONS)
